# Generated by Django 5.2.13 on 2026-07-12 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_alter_dispatcherprofile_created_at_and_more'),
        ('orders', '0014_seed_shop_operation_templates'),
        ('renting', '0018_seed_rental_operation_lifecycle_templates'),
        ('technical_services', '0024_seed_service_operation_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationticket',
            name='rental_operation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_ticket', to='renting.rentaloperation'),
        ),
        migrations.AddField(
            model_name='operationticket',
            name='service_operation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_ticket', to='technical_services.serviceoperation'),
        ),
        migrations.AddField(
            model_name='operationticket',
            name='shipment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_ticket', to='orders.shipment'),
        ),
    ]
