# Generated by Django 5.2.13 on 2026-07-06 14:13

import django.db.models.deletion
import kyc.services.storage
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de verificacion'), ('UNDER_REVIEW', 'En revision'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('BLOCKED', 'Bloqueado'), ('EXPIRED', 'Expirado')], db_index=True, default='PENDING', max_length=15)),
                ('primer_nombre', models.CharField(blank=True, default='', max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, default='', max_length=50)),
                ('primer_apellido', models.CharField(blank=True, default='', max_length=50)),
                ('segundo_apellido', models.CharField(blank=True, default='', max_length=50)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('OTRO', 'Otro'), ('PREFIERO_NO_DECIR', 'Prefiero no decir')], default='', max_length=20)),
                ('nacionalidad', models.CharField(blank=True, default='', max_length=80)),
                ('fecha_expedicion_documento', models.DateField(blank=True, null=True)),
                ('lugar_expedicion_documento', models.CharField(blank=True, default='', max_length=100)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_message', models.CharField(blank=True, default='', max_length=500)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews_done', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'verificacion de identidad (KYC)',
                'verbose_name_plural': 'verificaciones de identidad (KYC)',
            },
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('doc_type', models.CharField(choices=[('CEDULA_FRONTAL', 'Cedula (frontal)'), ('CEDULA_REVERSO', 'Cedula (reverso)'), ('RUT', 'RUT'), ('HOJA_VIDA', 'Hoja de vida / CV'), ('DIPLOMA', 'Diploma'), ('CERTIFICACION', 'Certificacion'), ('ANTECEDENTES_POLICIA', 'Antecedentes de Policia'), ('ANTECEDENTES_CONTRALORIA', 'Antecedentes de Contraloria'), ('ANTECEDENTES_PROCURADURIA', 'Antecedentes de Procuraduria'), ('OTRO', 'Otro')], db_index=True, max_length=30)),
                ('file', models.FileField(blank=True, null=True, storage=kyc.services.storage.kyc_private_storage, upload_to=kyc.services.storage.kyc_upload_path)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('file_hash_sha256', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], db_index=True, default='PENDING', max_length=10)),
                ('scan_status', models.CharField(choices=[('SKIPPED', 'Sin escanear (antivirus no configurado)'), ('CLEAN', 'Limpio'), ('INFECTED', 'Infectado'), ('ERROR', 'Error al escanear')], default='SKIPPED', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=300)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_kyc_docs', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_kyc_docs', to=settings.AUTH_USER_MODEL)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='kyc.userverification')),
            ],
            options={
                'verbose_name': 'documento KYC',
                'verbose_name_plural': 'documentos KYC',
            },
        ),
        migrations.CreateModel(
            name='VerificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('event_type', models.CharField(choices=[('CREATED', 'Verificacion creada'), ('SUBMITTED_FOR_REVIEW', 'Enviado a revision'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('INFO_REQUESTED', 'Informacion solicitada'), ('BLOCKED', 'Bloqueado'), ('DOC_UPLOADED', 'Documento subido'), ('DOC_DELETED', 'Documento eliminado'), ('DOC_OPENED', 'Documento abierto por admin'), ('DOC_APPROVED', 'Documento aprobado'), ('DOC_REJECTED', 'Documento rechazado'), ('NOTE', 'Nota')], db_index=True, max_length=25)),
                ('description', models.TextField(blank=True, default='')),
                ('actor_email', models.EmailField(blank=True, default='', max_length=254)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_events_performed', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='kyc.verificationdocument')),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='kyc.userverification')),
            ],
            options={
                'verbose_name': 'evento de verificacion KYC',
                'verbose_name_plural': 'eventos de verificacion KYC',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('consent_type', models.CharField(choices=[('POLITICA_TRATAMIENTO_DATOS', 'Politica de Tratamiento de Datos Personales'), ('AUTORIZACION_TRATAMIENTO_DATOS', 'Autorizacion de Tratamiento de Datos'), ('TERMINOS_CONDICIONES', 'Terminos y Condiciones')], db_index=True, max_length=40)),
                ('document_version', models.CharField(max_length=20)),
                ('accepted', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de consentimiento (Habeas Data)',
                'verbose_name_plural': 'registros de consentimiento (Habeas Data)',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'consent_type', 'created_at'], name='kyc_consent_user_id_a07696_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='verificationdocument',
            index=models.Index(fields=['verification', 'doc_type'], name='kyc_verific_verific_f072e2_idx'),
        ),
    ]
