# Generated by Django 5.2.13 on 2026-07-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_grandfather_approve_existing_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverification',
            name='requested_user_type',
            field=models.CharField(blank=True, choices=[('TECHNICIAN', 'Tecnico'), ('PROFESSIONAL', 'Profesional'), ('SPECIALIST', 'Especialista'), ('CUSTOMER', 'Comprador'), ('TRANSPORTER', 'Transportista'), ('CONTRACTOR', 'Contratista'), ('ACCOUNTANT', 'Contador')], default=None, max_length=20, null=True),
        ),
    ]
