# Generated by Django 5.2.13 on 2026-07-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0004_userverification_requested_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverification',
            name='first_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
