# Generated by Django 5.2.13 on 2026-07-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0006_backfill_customer_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationdocument',
            name='scan_status',
            field=models.CharField(choices=[('SKIPPED', 'Sin escanear (antivirus no configurado)'), ('CLEAN', 'Limpio'), ('INFECTED', 'Infectado'), ('ERROR', 'Error al escanear')], db_index=True, default='SKIPPED', max_length=10),
        ),
    ]
