# Generated by Django 5.2.13 on 2026-06-25 16:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('email_body', models.TextField(blank=True, default='', help_text='Soporta variables Django Template: {{ order_uuid }}, {{ total }}, etc.')),
                ('whatsapp_template_name', models.CharField(blank=True, default='', help_text='Nombre exacto de la plantilla aprobada en Meta Business Manager.', max_length=255)),
                ('ws_event_type', models.CharField(blank=True, default='', help_text='event_type que recibe el frontend (ej. ORDER_PAID_SUCCESS).', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Plantilla de notificacion',
                'verbose_name_plural': 'Plantillas de notificaciones',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('channel', models.CharField(choices=[('EMAIL', 'Correo electronico'), ('WHATSAPP', 'WhatsApp'), ('WEB_SOCKET', 'Notificacion web en tiempo real')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('SENT', 'Enviado'), ('FAILED', 'Fallido')], db_index=True, default='PENDING', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('payload_context', models.JSONField(default=dict, help_text='Variables de contexto enviadas al motor de plantillas.')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='notifications.notificationtemplate')),
            ],
            options={
                'verbose_name': 'Log de notificacion',
                'verbose_name_plural': 'Logs de notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='notificatio_user_id_d1d348_idx'), models.Index(fields=['template', 'channel', 'status'], name='notificatio_templat_2494ea_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('channel', models.CharField(choices=[('EMAIL', 'Correo electronico'), ('WHATSAPP', 'WhatsApp'), ('WEB_SOCKET', 'Notificacion web en tiempo real')], db_index=True, max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencia de notificacion',
                'verbose_name_plural': 'Preferencias de notificacion',
                'unique_together': {('user', 'channel')},
            },
        ),
    ]
