# Generated by Django 5.2.13 on 2026-07-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='template_slug',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='channel',
            field=models.CharField(blank=True, choices=[('EMAIL', 'Correo electronico'), ('WHATSAPP', 'WhatsApp'), ('WEB_SOCKET', 'Notificacion web en tiempo real')], db_index=True, max_length=20),
        ),
    ]
