# Generated by Django 5.2.13 on 2026-07-09 22:56

from django.db import migrations


def backfill_template_slug(apps, schema_editor):
    NotificationLog = apps.get_model('notifications', 'NotificationLog')
    logs = (
        NotificationLog.objects
        .filter(template_slug='', template__isnull=False)
        .select_related('template')
    )
    for log in logs:
        log.template_slug = log.template.slug
        log.save(update_fields=['template_slug'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationlog_template_slug_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_template_slug, noop_reverse),
    ]
