# Generated by Django 5.2.13 on 2026-07-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_seed_cross_sell_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='sms_body',
            field=models.CharField(blank=True, default='', help_text='Texto del SMS (max 160 caracteres = 1 segmento GSM-7, sin partir en varios mensajes). Soporta variables Django Template.', max_length=160),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='channel',
            field=models.CharField(blank=True, choices=[('EMAIL', 'Correo electronico'), ('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS'), ('WEB_SOCKET', 'Notificacion web en tiempo real')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='usernotificationpreference',
            name='channel',
            field=models.CharField(choices=[('EMAIL', 'Correo electronico'), ('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS'), ('WEB_SOCKET', 'Notificacion web en tiempo real')], db_index=True, max_length=20),
        ),
    ]
