# Generated by Django 5.2.13 on 2026-08-03 19:42

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_add_sms_channel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['template_slug'], name='notificatio_templat_6766a7_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=django.contrib.postgres.indexes.GinIndex(fields=['payload_context'], name='notificatio_payload_c46ece_gin'),
        ),
    ]
