# Generated by Django 6.0.4 on 2026-04-14 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('shop', '0001_initial'),
        ('technical_services', '0002_remove_servicematerial_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='service_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='technical_services.servicevariant'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productvariant'),
        ),
    ]
