# Generated by Django 5.2.13 on 2026-07-03 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_is_deleted_cartitem_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cart',
            name='cart_cart_uuid_49de32_idx',
        ),
        migrations.RemoveIndex(
            model_name='cart',
            name='cart_cart_created_8a2171_idx',
        ),
        migrations.RemoveIndex(
            model_name='cartitem',
            name='cart_cartit_uuid_5d8e5d_idx',
        ),
        migrations.RemoveIndex(
            model_name='cartitem',
            name='cart_cartit_created_10634c_idx',
        ),
    ]
