# Generated by Django 5.2.13 on 2026-07-03 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cart_cart_cart_uuid_49de32_idx_and_more'),
        ('shop', '0008_alter_product_is_active_alter_product_is_featured_and_more'),
        ('technical_services', '0021_remove_serviceconfiguration_technical_s_uuid_1565d1_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('service_variant__isnull', True), ('variant__isnull', False)), models.Q(('service_variant__isnull', False), ('variant__isnull', True)), _connector='OR'), name='cart_cartitem_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', False)), fields=('cart', 'variant'), name='cart_cartitem_unique_variant_per_cart'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('service_variant__isnull', False)), fields=('cart', 'service_variant'), name='cart_cartitem_unique_service_variant_per_cart'),
        ),
    ]
