# Generated by Django 5.2.13 on 2026-09-24 19:37

from django.db import migrations, models


# TTL por categoria (dias) -- debe coincidir con settings.CUSTOMER_MEMORY_TTL_DAYS por defecto (HARDENING F7/C2).
_TTL_DAYS = {'contact_preference': 365, 'communication_style': 365, 'product_interest': 180, 'general_preference': 180}


def backfill_expires_at(apps, schema_editor):
    """Registros existentes: expires_at = created_at + TTL de su categoria (reversible: no se borra nada)."""
    from datetime import timedelta

    Record = apps.get_model('customer_memory', 'CustomerMemoryRecord')
    for category, days in _TTL_DAYS.items():
        for rec in Record.objects.filter(category=category, expires_at__isnull=True).iterator():
            rec.expires_at = rec.created_at + timedelta(days=days)
            rec.save(update_fields=['expires_at'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('customer_memory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermemoryrecord',
            name='channel',
            field=models.CharField(choices=[('web', 'Web'), ('whatsapp', 'WhatsApp'), ('unknown', 'Desconocido')], default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='customermemoryrecord',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='customermemoryrecord',
            name='origin',
            field=models.CharField(default='user_message', max_length=20),
        ),
        migrations.RunPython(backfill_expires_at, noop),
    ]
