# Generated by Django 5.2.13 on 2026-07-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Abierta'), ('CLOSED', 'Cerrada')], db_index=True, default='OPEN', max_length=10),
        ),
    ]
