# Generated by Django 5.2.13 on 2026-07-09 19:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_seed_shop_operation_templates'),
        ('renting', '0018_seed_rental_operation_lifecycle_templates'),
        ('support', '0002_alter_chatroom_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoomContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('context_type', models.CharField(choices=[('ORDER', 'Pedido'), ('RENTAL', 'Alquiler')], max_length=20)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_contexts', to='orders.order')),
                ('rental_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_contexts', to='renting.rentalrequest')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='support.chatroom')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('context_type', 'ORDER'), ('order__isnull', False), ('rental_request__isnull', True)), models.Q(('context_type', 'RENTAL'), ('order__isnull', True), ('rental_request__isnull', False)), _connector='OR'), name='chatroomcontext_exactly_one_target')],
            },
        ),
    ]
