# Generated by Django 5.2.13 on 2026-07-09 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_seed_shop_operation_templates'),
        ('renting', '0018_seed_rental_operation_lifecycle_templates'),
        ('support', '0003_chatroomcontext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroomcontext',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_contexts', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='chatroomcontext',
            name='rental_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_contexts', to='renting.rentalrequest'),
        ),
    ]
