# Generated by Django 5.2.13 on 2026-07-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_alter_chatroomcontext_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='ai_paused',
            field=models.BooleanField(default=False),
        ),
    ]
