# Generated by Django 5.2.13 on 2026-07-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_chatroom_ai_paused'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='ai_metrics',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
