# Generated by Django 5.2.13 on 2026-07-21 00:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_seed_notify_stale_tickets_periodic_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='csat_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='csat_rated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='csat_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
