# Generated by Django 5.2.13 on 2026-08-03 19:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0008_chatroom_csat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['status', 'ai_paused', 'updated_at', 'is_deleted'], name='support_cha_status_3b81c0_idx'),
        ),
    ]
