# Generated by Django 5.2.13 on 2026-09-15 15:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0009_chatroom_support_cha_status_3b81c0_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('ticket_number', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True)),
                ('subject', models.CharField(blank=True, default='', max_length=200)),
                ('summary', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('NEW', 'Nuevo'), ('OPEN', 'Abierto'), ('IN_PROGRESS', 'En proceso'), ('WAITING_CUSTOMER', 'Esperando cliente'), ('RESOLVED', 'Resuelto'), ('CLOSED', 'Cerrado'), ('CANCELLED', 'Cancelado')], db_index=True, default='NEW', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Baja'), ('NORMAL', 'Normal'), ('HIGH', 'Alta'), ('URGENT', 'Urgente')], db_index=True, default='NORMAL', max_length=10)),
                ('category', models.CharField(blank=True, choices=[('ACCOUNT', 'Cuenta'), ('ORDER', 'Pedido'), ('PAYMENT', 'Pago'), ('PRODUCT', 'Producto'), ('RENTING', 'Alquiler'), ('TECHNICAL', 'Tecnico'), ('DELIVERY', 'Entrega'), ('OTHER', 'Otro')], default='', max_length=20)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_tickets', to=settings.AUTH_USER_MODEL)),
                ('chat_room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='support.chatroom')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'priority', 'is_deleted'], name='support_sup_status_64d96c_idx')],
            },
        ),
    ]
