# Generated by Django 5.2.13 on 2026-06-19 15:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technical_services", "0007_orderservicedetail_orderservicetimeline_and_more"),
        ("users", "0002_user_is_deleted_userprofile_is_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Admin"),
                    (2, "Customer"),
                    (3, "Vendor"),
                    (4, "Technician"),
                ],
                default=2,
            ),
        ),
        migrations.CreateModel(
            name="TechnicianProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "specialties",
                    models.ManyToManyField(
                        blank=True,
                        related_name="technicians",
                        to="technical_services.servicecategory",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technician_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(fields=["uuid"], name="users_techn_uuid_99a267_idx"),
                    models.Index(
                        fields=["-created_at"], name="users_techn_created_c57035_idx"
                    ),
                ],
            },
        ),
    ]
