# Generated by Django 5.2.13 on 2026-06-26 22:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_emailverificationcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverificationcode",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="emailverificationcode",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name="emailverificationcode",
            name="uuid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AddField(
            model_name="phoneotp",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="phoneotp",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name="phoneotp",
            name="uuid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="emailverificationcode",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="phoneotp",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="phoneotp",
            index=models.Index(fields=["uuid"], name="users_phone_uuid_9bc53d_idx"),
        ),
        migrations.AddIndex(
            model_name="phoneotp",
            index=models.Index(
                fields=["-created_at"], name="users_phone_created_e186b1_idx"
            ),
        ),
    ]
