# Generated by Django 5.2.13 on 2026-07-03 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_emailverificationcode_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='phoneotp',
            name='users_phone_uuid_9bc53d_idx',
        ),
        migrations.RemoveIndex(
            model_name='phoneotp',
            name='users_phone_created_e186b1_idx',
        ),
    ]
