# Generated by Django 5.2.13 on 2026-07-05 22:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('actor_email', models.EmailField(blank=True, default='', max_length=254)),
                ('target_user_email', models.EmailField(blank=True, default='', max_length=254)),
                ('action', models.CharField(choices=[('created', 'Usuario creado'), ('activated', 'Usuario activado'), ('deactivated', 'Usuario desactivado'), ('updated', 'Usuario actualizado'), ('password_reset', 'Contrasena restablecida'), ('verification_resent', 'Verificacion reenviada'), ('groups_changed', 'Grupos modificados'), ('erased', 'Usuario eliminado permanentemente')], db_index=True, max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions_performed', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de auditoria de usuario',
                'verbose_name_plural': 'registros de auditoria de usuarios',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_user', 'created_at'], name='users_usera_target__6c530c_idx')],
            },
        ),
    ]
