# Generated by Django 5.2.13 on 2026-07-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_userauditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Usuario creado'), ('activated', 'Usuario activado'), ('deactivated', 'Usuario desactivado'), ('updated', 'Usuario actualizado'), ('password_reset', 'Contrasena restablecida'), ('verification_resent', 'Verificacion reenviada'), ('groups_changed', 'Grupos modificados'), ('erased', 'Usuario eliminado permanentemente'), ('kyc_submitted', 'KYC enviado a revision'), ('kyc_approved', 'KYC aprobado'), ('kyc_rejected', 'KYC rechazado'), ('kyc_info_requested', 'KYC informacion solicitada'), ('kyc_blocked', 'KYC bloqueado'), ('kyc_upgrade_requested', 'Solicito upgrade a perfil profesional')], db_index=True, max_length=30),
        ),
    ]
