# Generated by Django 5.2.13 on 2026-07-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_emailverificationcode_composite_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emailverificationcode',
            name='email_verif_email_used_idx',
        ),
        migrations.AddField(
            model_name='emailverificationcode',
            name='purpose',
            field=models.CharField(choices=[('registration', 'Registro'), ('password_reset_customer', 'Restablecimiento de contrasena (cliente)'), ('password_reset_admin', 'Restablecimiento de contrasena (admin)')], db_index=True, default='registration', max_length=30),
        ),
        migrations.AddIndex(
            model_name='emailverificationcode',
            index=models.Index(fields=['email', 'purpose', 'is_used'], name='email_verif_purpose_used_idx'),
        ),
    ]
