# Generated by Django 5.2.13 on 2026-06-19 20:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_migrate_user_data_to_profiles'),
        ('technical_services', '0009_servicepricehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contractor_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('COP', 'COP'), ('MXN', 'MXN')], default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='document_type',
            field=models.CharField(blank=True, choices=[('CC', 'Cedula de Ciudadania'), ('CE', 'Cedula de Extranjeria'), ('NIT', 'Numero de Identificacion Tributaria'), ('PP', 'Pasaporte')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='project_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.CreateModel(
            name='AcademicTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('institution', models.CharField(max_length=150)),
                ('degree', models.CharField(max_length=150)),
                ('field_of_study', models.CharField(blank=True, default='', max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_trainings', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'educacion academica',
                'verbose_name_plural': 'educaciones academicas',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=150)),
                ('issuing_organization', models.CharField(max_length=150)),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, default='', max_length=100)),
                ('credential_url', models.URLField(blank=True, default='')),
                ('document', models.FileField(blank=True, null=True, upload_to='contractors/certifications/')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_certifications', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'certificacion profesional',
                'verbose_name_plural': 'certificaciones profesionales',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=150)),
                ('institution', models.CharField(max_length=150)),
                ('completion_date', models.DateField()),
                ('hours', models.PositiveIntegerField(blank=True, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_courses', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'curso profesional',
                'verbose_name_plural': 'cursos profesionales',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('company', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_experiences', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'experiencia profesional',
                'verbose_name_plural': 'experiencias profesionales',
            },
        ),
        migrations.CreateModel(
            name='SuccessCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='success_cases', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'caso de exito',
                'verbose_name_plural': 'casos de exito',
            },
        ),
        migrations.CreateModel(
            name='SuccessCaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('image', models.ImageField(upload_to='contractors/success_cases/')),
                ('is_before', models.BooleanField(default=False)),
                ('is_after', models.BooleanField(default=False)),
                ('success_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.successcase')),
            ],
            options={
                'verbose_name': 'imagen de caso de exito',
                'verbose_name_plural': 'imagenes de casos de exito',
            },
        ),
        migrations.CreateModel(
            name='ContractorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('comment', models.TextField(blank=True, default='')),
                ('quality_rating', models.PositiveSmallIntegerField(default=5)),
                ('punctuality_rating', models.PositiveSmallIntegerField(default=5)),
                ('professionalism_rating', models.PositiveSmallIntegerField(default=5)),
                ('communication_rating', models.PositiveSmallIntegerField(default=5)),
                ('compliance_rating', models.PositiveSmallIntegerField(default=5)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_reviews', to='accounts.userprofile')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reseña de contratista',
                'verbose_name_plural': 'reseñas de contratista',
                'unique_together': {('contractor', 'reviewer')},
            },
        ),
        migrations.CreateModel(
            name='ContractorSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(blank=True, default='', max_length=50)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_skills', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'habilidad de contratista',
                'verbose_name_plural': 'habilidades de contratista',
                'unique_together': {('user_profile', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ContractorSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_specialties', to='technical_services.servicecategory')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_specialties', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'especialidad de contratista',
                'verbose_name_plural': 'especialidades de contratista',
                'unique_together': {('user_profile', 'category')},
            },
        ),
    ]
