# Generated by Django 5.2.13 on 2026-06-20 00:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_bio_userprofile_birth_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('PENDING_RESERVATION', 'Reserva temporal (15 min)'), ('BOOKED', 'Reservado'), ('BLOCKED', 'Bloqueado'), ('VACATION', 'Vacaciones'), ('SICK_LEAVE', 'Incapacidad')], db_index=True, default='AVAILABLE', max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot_bookings', to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'disponibilidad profesional',
                'verbose_name_plural': 'disponibilidades profesionales',
                'ordering': ['date', 'start_time'],
                'unique_together': {('user_profile', 'date', 'start_time')},
            },
        ),
    ]
