# Generated by Django 5.2.13 on 2026-06-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_professionalavailability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("TECHNICIAN", "Tecnico"),
                    ("PROFESSIONAL", "Profesional"),
                    ("SPECIALIST", "Especialista"),
                    ("CUSTOMER", "Comprador"),
                ],
                default="TECHNICIAN",
                max_length=20,
            ),
        ),
    ]
