# Generated by Django 5.2.13 on 2026-07-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('TECHNICIAN', 'Tecnico'), ('PROFESSIONAL', 'Profesional'), ('SPECIALIST', 'Especialista'), ('CUSTOMER', 'Comprador'), ('TRANSPORTER', 'Transportista'), ('CONTRACTOR', 'Contratista'), ('ACCOUNTANT', 'Contador')], db_index=True, default='TECHNICIAN', max_length=20),
        ),
    ]
