# Generated by Django 5.2.13 on 2026-07-05 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorProfile',
        ),
    ]
