# Generated by Django 5.2.13 on 2026-07-17 02:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userprofile_document_unique_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userprofile',
            name='userprofile_document_unique',
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('document__isnull', False), models.Q(('document', ''), _negated=True)), fields=('document_type', 'document'), name='userprofile_document_unique'),
        ),
    ]
