# Generated by Django 5.2.13 on 2026-08-13 15:03

import django.db.models.deletion
import shared.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('model_id', models.CharField(max_length=200)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('discovered_automatically', models.BooleanField(default=False, help_text='True si se agrego via descubrimiento automatico (ej. GET /api/tags de Ollama).')),
            ],
            options={
                'ordering': ['provider__display_order', 'model_id'],
            },
        ),
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('kind', models.CharField(choices=[('ollama-nativo', 'Ollama (nativo)'), ('openai-compatible', 'OpenAI-compatible (LM Studio, vLLM, OpenAI, DeepSeek, ...)'), ('anthropic', 'Anthropic (Claude)')], max_length=30)),
                ('base_url', models.CharField(blank=True, help_text='Requerido para ollama-nativo/openai-compatible (ej. http://host.docker.internal:11434 para Ollama en Windows, http://host.docker.internal:1234/v1 para LM Studio en Windows, http://sintel_ollama:11434 para Ollama en Docker). No aplica a anthropic.', max_length=500)),
                ('api_key', shared.fields.EncryptedTextField(blank=True, help_text='Cifrada en reposo. Vacia para motores locales.')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_ok', models.BooleanField(null=True)),
                ('last_test_latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('last_test_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AIChannelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('channel', models.CharField(choices=[('support_chat', 'Chat de Soporte')], max_length=50, unique=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('primary_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_for_channels', to='ai_provider.aimodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='aimodel',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='ai_provider.aiprovider'),
        ),
        migrations.CreateModel(
            name='AIChannelFallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('channel_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallbacks', to='ai_provider.aichannelconfig')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallback_for_channels', to='ai_provider.aimodel')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('channel_config', 'order'), name='unique_fallback_order_per_channel')],
            },
        ),
        migrations.AddConstraint(
            model_name='aimodel',
            constraint=models.UniqueConstraint(fields=('provider', 'model_id'), name='unique_model_per_provider'),
        ),
    ]
