# Generated by Django 5.2.13 on 2026-08-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprovider',
            name='last_test_ok',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
