# Generated by Django 5.2.13 on 2026-08-13 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_provider', '0002_alter_aiprovider_last_test_ok'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichannelconfig',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aichannelconfig',
            name='max_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aichannelconfig',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aichannelconfig',
            name='temperature',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)]),
        ),
        migrations.AddField(
            model_name='aichannelconfig',
            name='timeout',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='context_window',
            field=models.PositiveIntegerField(blank=True, help_text='Informativo -- no se envia al proveedor, solo referencia para el admin.', null=True),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='max_tokens',
            field=models.PositiveIntegerField(blank=True, help_text='Vacio = default del motor.', null=True),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='temperature',
            field=models.FloatField(blank=True, help_text='Vacio = usa el default del proveedor/motor (0.1 hoy en llm_factory.py).', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)]),
        ),
        migrations.AddField(
            model_name='aiprovider',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiprovider',
            name='max_retries',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='aiprovider',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aiprovider',
            name='slug',
            field=models.SlugField(blank=True, max_length=110),
        ),
        migrations.AddField(
            model_name='aiprovider',
            name='timeout',
            field=models.PositiveIntegerField(default=90, help_text='Segundos. Entre 5 y 300.', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(300)]),
        ),
    ]
