# Generated by Django 5.2.13 on 2026-08-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_provider', '0004_populate_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprovider',
            name='slug',
            field=models.SlugField(blank=True, max_length=110, unique=True),
        ),
    ]
