# Generated by Django 5.2.13 on 2026-09-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_provider', '0005_alter_aiprovider_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aichannelconfig',
            name='channel',
            field=models.CharField(choices=[('support_chat', 'Chat de Soporte'), ('embeddings', 'Embeddings (RAG)')], max_length=50, unique=True),
        ),
    ]
