# Generated by Django 5.2.13 on 2026-09-25 16:58

import django.core.validators
import shared.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_provider', '0007_config_version_and_revisions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('server_url', models.CharField(max_length=500)),
                ('transport', models.CharField(choices=[('streamable-http', 'Streamable HTTP'), ('sse', 'SSE (legado)')], default='streamable-http', max_length=20)),
                ('auth_type', models.CharField(choices=[('bearer', 'Authorization: Bearer <key>'), ('header', 'Cabecera personalizada'), ('none', 'Sin autenticacion')], default='none', max_length=10)),
                ('api_key_header', models.CharField(blank=True, max_length=60)),
                ('api_key', shared.fields.EncryptedTextField(blank=True, help_text='Cifrada en reposo.')),
                ('verify_tls', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
                ('tools_count', models.PositiveIntegerField(default=0)),
                ('exposes_model_invocation', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('UNKNOWN', 'UNKNOWN'), ('HEALTHY', 'HEALTHY'), ('UNAVAILABLE', 'UNAVAILABLE'), ('MISCONFIGURED', 'MISCONFIGURED'), ('DISABLED', 'DISABLED')], default='UNKNOWN', max_length=15)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('last_latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='aimodel',
            name='capabilities',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='capabilities_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='top_p',
            field=models.FloatField(blank=True, help_text='Vacio = default del proveedor.', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='aiprovider',
            name='api_key_header',
            field=models.CharField(blank=True, help_text='Nombre de la cabecera si auth_type=header (p. ej. x-api-key).', max_length=60),
        ),
        migrations.AddField(
            model_name='aiprovider',
            name='auth_type',
            field=models.CharField(choices=[('bearer', 'Authorization: Bearer <key>'), ('header', 'Cabecera personalizada'), ('none', 'Sin autenticacion')], default='bearer', max_length=10),
        ),
        migrations.AddField(
            model_name='aiprovider',
            name='connect_timeout',
            field=models.PositiveIntegerField(default=5, help_text='Segundos para establecer la conexion (distinto de timeout total).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AddField(
            model_name='aiprovider',
            name='endpoint_path',
            field=models.CharField(blank=True, help_text='Ruta para listar modelos (openai-compatible/generic-rest). Vacio = /models.', max_length=200),
        ),
        migrations.AddField(
            model_name='aiprovider',
            name='health_status',
            field=models.CharField(choices=[('UNKNOWN', 'UNKNOWN'), ('HEALTHY', 'HEALTHY'), ('DEGRADED', 'DEGRADED'), ('UNAVAILABLE', 'UNAVAILABLE'), ('MISCONFIGURED', 'MISCONFIGURED'), ('DISABLED', 'DISABLED')], default='UNKNOWN', max_length=15),
        ),
        migrations.AddField(
            model_name='aiprovider',
            name='last_health_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiprovider',
            name='verify_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='kind',
            field=models.CharField(choices=[('ollama-nativo', 'Ollama (nativo)'), ('openai-compatible', 'OpenAI-compatible (LM Studio, vLLM, OpenAI, DeepSeek, ...)'), ('anthropic', 'Anthropic (Claude)'), ('gemini', 'Google Gemini'), ('generic-rest', 'REST generico (solo registro y prueba)'), ('custom', 'Personalizado (solo registro y prueba)')], max_length=30),
        ),
    ]
