# Generated by Django 5.2.13 on 2026-07-30 22:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


# Squash de technical_services 0001-0006 (DT-M18, migration squashing). Rango
# acotado a 0006 (no mas alla) porque technical_services empieza a depender
# de orders recien en 0007 (OrderServiceDetail/OrderServiceTimeline FK a
# Order) mientras que orders ya depende de technical_services desde su
# propio 0002 (FK a ServiceVariant) -- squashear mas alla de 0006 colapsa
# ambos extremos en un solo nodo y genera un CircularDependencyError real
# (orders.0002 -> squash -> orders.0005 -> squash) que no existe en el grafo
# sin squashear. Se probo primero con rango 0001-0031 y luego 0001-0022,
# ambos fallaron con el mismo tipo de ciclo por la misma razon -- este es el
# rango mas amplio que no lo produce. La funcion de abajo se copio
# manualmente desde su migracion original (0005) por pedido explicito de
# Django ("Manual porting required") -- la original NO se borro (sigue en
# este mismo directorio). Es no-op segura sobre una BD nueva vacia
# (get_or_create idempotente) y Django no la re-ejecuta sobre una BD ya
# migrada.
from django.utils.text import slugify


def seed_categories(apps, schema_editor):
    """Copiada de 0005_seed_categories.py."""
    ServiceCategory = apps.get_model('technical_services', 'ServiceCategory')

    categories_data = [
        {
            "name": "Mantenimiento Preventivo",
            "description": "Servicios de limpieza física y optimización lógica de equipos.",
            "subcategories": [
                {"name": "Limpieza Física de Hardware", "description": "Limpieza profunda de componentes internos y externos."},
                {"name": "Optimización de Software", "description": "Depuración de archivos temporales, virus y actualizaciones."}
            ]
        },
        {
            "name": "CCTV & Seguridad",
            "description": "Instalación y configuración de circuitos cerrados de televisión.",
            "subcategories": [
                {"name": "Instalación de Cámaras", "description": "Montaje y cableado de cámaras de seguridad."},
                {"name": "Configuración de DVR", "description": "Configuración de grabadores y acceso remoto."}
            ]
        },
        {
            "name": "Soporte Técnico",
            "description": "Asistencia técnica especializada para solución de problemas.",
            "subcategories": [
                {"name": "Diagnóstico de Fallas", "description": "Revisión inicial para detectar problemas de hardware/software."},
                {"name": "Reparación de Equipos", "description": "Cambio de partes y reparación física."}
            ]
        }
    ]

    for cat_info in categories_data:
        parent_cat, created = ServiceCategory.objects.get_or_create(
            name=cat_info["name"],
            defaults={
                "slug": slugify(cat_info["name"]),
                "description": cat_info["description"],
                "is_active": True
            }
        )
        for sub_info in cat_info["subcategories"]:
            ServiceCategory.objects.get_or_create(
                name=sub_info["name"],
                defaults={
                    "parent": parent_cat,
                    "slug": slugify(sub_info["name"]),
                    "description": sub_info["description"],
                    "is_active": True
                }
            )


def rollback_categories(apps, schema_editor):
    """Copiada de 0005_seed_categories.py."""
    ServiceCategory = apps.get_model('technical_services', 'ServiceCategory')
    ServiceCategory.objects.filter(
        name__in=[
            "Mantenimiento Preventivo",
            "Limpieza Física de Hardware",
            "Optimización de Software",
            "CCTV & Seguridad",
            "Instalación de Cámaras",
            "Configuración de DVR",
            "Soporte Técnico",
            "Diagnóstico de Fallas",
            "Reparación de Equipos"
        ]
    ).delete()


class Migration(migrations.Migration):

    replaces = [('technical_services', '0001_initial'), ('technical_services', '0002_remove_servicematerial_name_and_more'), ('technical_services', '0003_servicecategory_is_deleted_and_more'), ('technical_services', '0004_servicevariant_max_duration_and_more'), ('technical_services', '0005_seed_categories'), ('technical_services', '0006_serviceconfiguration_iva_rate')]

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(default='Estándar Colombia 2024', max_length=100)),
                ('smlv', models.DecimalField(decimal_places=2, default=1300000.0, max_digits=12)),
                ('transport_subsidy', models.DecimalField(decimal_places=2, default=162000.0, max_digits=12)),
                ('benefit_rate', models.DecimalField(decimal_places=2, default=53.1, help_text='Percentage of social benefits and taxes', max_digits=5)),
                ('indirect_costs_rate', models.DecimalField(decimal_places=2, default=15.0, help_text='Indirect costs / Overhead percentage', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['uuid'], name='technical_s_uuid_1565d1_idx'), models.Index(fields=['-created_at'], name='technical_s_created_72e4bd_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='technical_services.servicecategory')),
            ],
            options={
                'verbose_name': 'categoría de servicio',
                'verbose_name_plural': 'categorías de servicios',
            },
        ),
        migrations.CreateModel(
            name='ServiceLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['uuid'], name='technical_s_uuid_bfa4aa_idx'), models.Index(fields=['-created_at'], name='technical_s_created_e084bc_idx')],
            },
        ),
        migrations.CreateModel(
            name='TechnicalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_purchasable', models.BooleanField(default=True)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technical_services', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='technical_services.servicecategory')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='technical_services.servicelevel')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['uuid'], name='technical_s_uuid_43fda6_idx'), models.Index(fields=['-created_at'], name='technical_s_created_6a7d54_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('sku', models.CharField(db_index=True, max_length=100, unique=True)),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=1.0, max_digits=6)),
                ('complexity_factor', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplier for specialized labor', max_digits=4)),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='technical_services.technicalservice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('image', models.ImageField(upload_to='services/')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='technical_services.technicalservice')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='technical_services.servicevariant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=8)),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_in_services', to='shop.productvariant')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='technical_services.servicevariant')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['uuid'], name='technical_s_uuid_57092d_idx'), models.Index(fields=['-created_at'], name='technical_s_created_f46ac8_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='technical_services.technicalservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['uuid'], name='technical_s_uuid_cad675_idx'), models.Index(fields=['-created_at'], name='technical_s_created_278ba5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='servicevariant',
            index=models.Index(fields=['uuid'], name='technical_s_uuid_a1c101_idx'),
        ),
        migrations.AddIndex(
            model_name='servicevariant',
            index=models.Index(fields=['-created_at'], name='technical_s_created_ebae08_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceimage',
            index=models.Index(fields=['uuid'], name='technical_s_uuid_2f3319_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceimage',
            index=models.Index(fields=['-created_at'], name='technical_s_created_db84de_idx'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='serviceconfiguration',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='servicelevel',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='servicematerial',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='servicereview',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='servicevariant',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='technicalservice',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='servicevariant',
            name='max_duration',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum allowed duration (hours or days depending on pricing strategy)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='servicevariant',
            name='min_duration',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum allowed duration (hours or days depending on pricing strategy)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='servicevariant',
            name='pricing_strategy',
            field=models.CharField(choices=[('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('FIXED', 'Fixed')], default='HOURLY', max_length=10),
        ),
        migrations.RunPython(
            code=seed_categories,
            reverse_code=rollback_categories,
        ),
        migrations.AddField(
            model_name='serviceconfiguration',
            name='iva_rate',
            field=models.DecimalField(decimal_places=2, default=19.0, help_text='Active tax rate (IVA percentage)', max_digits=5),
        ),
    ]
