# Generated by Django 6.0.4 on 2026-04-14 16:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(default='Estándar Colombia 2024', max_length=100)),
                ('smlv', models.DecimalField(decimal_places=2, default=1300000.0, max_digits=12)),
                ('transport_subsidy', models.DecimalField(decimal_places=2, default=162000.0, max_digits=12)),
                ('benefit_rate', models.DecimalField(decimal_places=2, default=53.1, help_text='Percentage of social benefits and taxes (e.g. 53.10)', max_digits=5)),
                ('indirect_costs_rate', models.DecimalField(decimal_places=2, default=15.0, help_text='Indirect costs / Overhead percentage', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['uuid'], name='technical_s_uuid_1565d1_idx'), models.Index(fields=['-created_at'], name='technical_s_created_72e4bd_idx')],
            },
        ),
        migrations.CreateModel(
            name='TechnicalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=1.0, max_digits=6)),
                ('complexity_factor', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplier for specialized labor (e.g. 1.5 for Senior)', max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['uuid'], name='technical_s_uuid_43fda6_idx'), models.Index(fields=['-created_at'], name='technical_s_created_6a7d54_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=8)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='technical_services.technicalservice')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['uuid'], name='technical_s_uuid_57092d_idx'), models.Index(fields=['-created_at'], name='technical_s_created_f46ac8_idx')],
            },
        ),
    ]
