# Generated by Django 6.0.4 on 2026-04-14 17:53

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('technical_services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicematerial',
            name='name',
        ),
        migrations.RemoveField(
            model_name='servicematerial',
            name='service',
        ),
        migrations.RemoveField(
            model_name='servicematerial',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='technicalservice',
            name='complexity_factor',
        ),
        migrations.RemoveField(
            model_name='technicalservice',
            name='estimated_hours',
        ),
        migrations.AddField(
            model_name='servicematerial',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_in_services', to='shop.productvariant'),
        ),
        migrations.AddField(
            model_name='technicalservice',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='technicalservice',
            name='is_purchasable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='technicalservice',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technical_services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serviceconfiguration',
            name='benefit_rate',
            field=models.DecimalField(decimal_places=2, default=53.1, help_text='Percentage of social benefits and taxes', max_digits=5),
        ),
        migrations.AlterField(
            model_name='technicalservice',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='technical_services.servicecategory')),
            ],
            options={
                'verbose_name': 'categoría de servicio',
                'verbose_name_plural': 'categorías de servicios',
            },
        ),
        migrations.AddField(
            model_name='technicalservice',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='technical_services.servicecategory'),
        ),
        migrations.CreateModel(
            name='ServiceLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['uuid'], name='technical_s_uuid_bfa4aa_idx'), models.Index(fields=['-created_at'], name='technical_s_created_e084bc_idx')],
            },
        ),
        migrations.AddField(
            model_name='technicalservice',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='technical_services.servicelevel'),
        ),
        migrations.CreateModel(
            name='ServiceVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('sku', models.CharField(db_index=True, max_length=100, unique=True)),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=1.0, max_digits=6)),
                ('complexity_factor', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplier for specialized labor', max_digits=4)),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='technical_services.technicalservice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('image', models.ImageField(upload_to='services/')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='technical_services.technicalservice')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='technical_services.servicevariant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='servicematerial',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='technical_services.servicevariant'),
        ),
        migrations.CreateModel(
            name='ServiceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='technical_services.technicalservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['uuid'], name='technical_s_uuid_cad675_idx'), models.Index(fields=['-created_at'], name='technical_s_created_278ba5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='servicevariant',
            index=models.Index(fields=['uuid'], name='technical_s_uuid_a1c101_idx'),
        ),
        migrations.AddIndex(
            model_name='servicevariant',
            index=models.Index(fields=['-created_at'], name='technical_s_created_ebae08_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceimage',
            index=models.Index(fields=['uuid'], name='technical_s_uuid_2f3319_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceimage',
            index=models.Index(fields=['-created_at'], name='technical_s_created_db84de_idx'),
        ),
    ]
