# Generated by Django 5.2.13 on 2026-06-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technical_services", "0003_servicecategory_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicevariant",
            name="max_duration",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum allowed duration (hours or days depending on pricing strategy)",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="servicevariant",
            name="min_duration",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minimum allowed duration (hours or days depending on pricing strategy)",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="servicevariant",
            name="pricing_strategy",
            field=models.CharField(
                choices=[("HOURLY", "Hourly"), ("DAILY", "Daily"), ("FIXED", "Fixed")],
                default="HOURLY",
                max_length=10,
            ),
        ),
    ]
