# Generated by Django

from django.db import migrations
from django.utils.text import slugify

def seed_categories(apps, schema_editor):
    ServiceCategory = apps.get_model('technical_services', 'ServiceCategory')
    
    categories_data = [
        {
            "name": "Mantenimiento Preventivo",
            "description": "Servicios de limpieza física y optimización lógica de equipos.",
            "subcategories": [
                {"name": "Limpieza Física de Hardware", "description": "Limpieza profunda de componentes internos y externos."},
                {"name": "Optimización de Software", "description": "Depuración de archivos temporales, virus y actualizaciones."}
            ]
        },
        {
            "name": "CCTV & Seguridad",
            "description": "Instalación y configuración de circuitos cerrados de televisión.",
            "subcategories": [
                {"name": "Instalación de Cámaras", "description": "Montaje y cableado de cámaras de seguridad."},
                {"name": "Configuración de DVR", "description": "Configuración de grabadores y acceso remoto."}
            ]
        },
        {
            "name": "Soporte Técnico",
            "description": "Asistencia técnica especializada para solución de problemas.",
            "subcategories": [
                {"name": "Diagnóstico de Fallas", "description": "Revisión inicial para detectar problemas de hardware/software."},
                {"name": "Reparación de Equipos", "description": "Cambio de partes y reparación física."}
            ]
        }
    ]
    
    for cat_info in categories_data:
        parent_cat, created = ServiceCategory.objects.get_or_create(
            name=cat_info["name"],
            defaults={
                "slug": slugify(cat_info["name"]),
                "description": cat_info["description"],
                "is_active": True
            }
        )
        for sub_info in cat_info["subcategories"]:
            ServiceCategory.objects.get_or_create(
                name=sub_info["name"],
                defaults={
                    "parent": parent_cat,
                    "slug": slugify(sub_info["name"]),
                    "description": sub_info["description"],
                    "is_active": True
                }
            )

def rollback_categories(apps, schema_editor):
    ServiceCategory = apps.get_model('technical_services', 'ServiceCategory')
    ServiceCategory.objects.filter(
        name__in=[
            "Mantenimiento Preventivo",
            "Limpieza Física de Hardware",
            "Optimización de Software",
            "CCTV & Seguridad",
            "Instalación de Cámaras",
            "Configuración de DVR",
            "Soporte Técnico",
            "Diagnóstico de Fallas",
            "Reparación de Equipos"
        ]
    ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ("technical_services", "0004_servicevariant_max_duration_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_categories, rollback_categories),
    ]
