# Generated by Django 5.2.13 on 2026-06-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technical_services", "0005_seed_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceconfiguration",
            name="iva_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=19.0,
                help_text="Active tax rate (IVA percentage)",
                max_digits=5,
            ),
        ),
    ]
