# Generated by Django 5.2.13 on 2026-06-19 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technical_services", "0007_orderservicedetail_orderservicetimeline_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="orderservicedetail",
            name="technician",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_services",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
