# Generated by Django 5.2.13 on 2026-06-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical_services', '0009_servicepricehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicevariant',
            name='pricing_strategy',
            field=models.CharField(choices=[('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('FIXED', 'Fixed'), ('CONTRACTOR_RATES', 'Tarifa de Contratista')], default='HOURLY', max_length=20),
        ),
    ]
