# Generated by Django 5.2.13 on 2026-06-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical_services', '0010_servicevariant_add_contractor_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderservicedetail',
            name='applied_rate_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='orderservicedetail',
            name='applied_rate_type',
            field=models.CharField(blank=True, choices=[('HOURLY', 'Por hora'), ('DAILY', 'Por dia'), ('PROJECT', 'Por proyecto')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderservicedetail',
            name='professional_type_snapshot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
