# Generated by Django 5.2.13 on 2026-06-20 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical_services', '0011_orderservicedetail_snapshot_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderservicedetail',
            name='booked_date',
            field=models.DateField(blank=True, help_text='Fecha del slot reservado.', null=True),
        ),
        migrations.AddField(
            model_name='orderservicedetail',
            name='booked_slot_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='ID del ProfessionalAvailability reservado.', null=True),
        ),
        migrations.AddField(
            model_name='orderservicedetail',
            name='booked_start_time',
            field=models.TimeField(blank=True, help_text='Hora de inicio del slot reservado.', null=True),
        ),
    ]
