# Generated by Django 5.2.13 on 2026-06-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical_services', '0015_servicecostrule_servicecostassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicevariant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
