# Generated by Django 5.2.13 on 2026-06-24 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technical_services', '0017_servicevariant_simultaneous_capacity_servicebooking'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='servicebooking',
            new_name='technical_s_start_t_c17a0b_idx',
            old_name='tech_svc_booking_time_idx',
        ),
        migrations.RenameIndex(
            model_name='servicebooking',
            new_name='technical_s_service_76fbb0_idx',
            old_name='tech_svc_booking_var_status_idx',
        ),
    ]
