# Generated by Django 5.2.13 on 2026-06-30 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technical_services', '0018_orderservicedetail_service_metadata'),
        ('technical_services', '0018_rename_tech_svc_booking_time_idx_technical_s_start_t_c17a0b_idx_and_more'),
    ]

    operations = [
    ]
