# Generated by Django 5.2.13 on 2026-06-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical_services', '0019_merge_20260630_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderservicedetail',
            name='confirmed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderservicedetail',
            name='confirmed_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceattachment',
            name='doc_type',
            field=models.CharField(blank=True, default='', help_text='Tipo de documento: foto, plano, manual, video, otro', max_length=50),
        ),
    ]
