# Generated by Django 5.2.13 on 2026-07-03 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technical_services', '0020_service_visit_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='serviceconfiguration',
            name='technical_s_uuid_1565d1_idx',
        ),
        migrations.RemoveIndex(
            model_name='serviceconfiguration',
            name='technical_s_created_72e4bd_idx',
        ),
        migrations.RemoveIndex(
            model_name='serviceimage',
            name='technical_s_uuid_2f3319_idx',
        ),
        migrations.RemoveIndex(
            model_name='serviceimage',
            name='technical_s_created_db84de_idx',
        ),
        migrations.RemoveIndex(
            model_name='servicelevel',
            name='technical_s_uuid_bfa4aa_idx',
        ),
        migrations.RemoveIndex(
            model_name='servicelevel',
            name='technical_s_created_e084bc_idx',
        ),
        migrations.RemoveIndex(
            model_name='servicematerial',
            name='technical_s_uuid_57092d_idx',
        ),
        migrations.RemoveIndex(
            model_name='servicematerial',
            name='technical_s_created_f46ac8_idx',
        ),
        migrations.RemoveIndex(
            model_name='servicereview',
            name='technical_s_uuid_cad675_idx',
        ),
        migrations.RemoveIndex(
            model_name='servicereview',
            name='technical_s_created_278ba5_idx',
        ),
        migrations.RemoveIndex(
            model_name='servicevariant',
            name='technical_s_uuid_a1c101_idx',
        ),
        migrations.RemoveIndex(
            model_name='servicevariant',
            name='technical_s_created_ebae08_idx',
        ),
        migrations.RemoveIndex(
            model_name='technicalservice',
            name='technical_s_uuid_43fda6_idx',
        ),
        migrations.RemoveIndex(
            model_name='technicalservice',
            name='technical_s_created_6a7d54_idx',
        ),
    ]
