# Generated by Django 5.2.13 on 2026-07-09 14:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_backfill_technician_profile_service_providers'),
        ('orders', '0012_alter_order_status'),
        ('technical_services', '0022_seed_service_payment_confirmed_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('READY_FOR_PLANNING', 'Pendiente de planeacion'), ('PLANNED', 'Planeada'), ('TECHNICIAN_ASSIGNED', 'Tecnico asignado'), ('CUSTOMER_NOTIFIED', 'Cliente notificado'), ('READY_TO_VISIT', 'Lista para visita'), ('ON_THE_WAY', 'Tecnico en camino'), ('ARRIVED', 'Tecnico en sitio'), ('IN_PROGRESS', 'Servicio en progreso'), ('COMPLETED', 'Servicio realizado'), ('CLOSED', 'Cerrada'), ('CANCELLED', 'Cancelada')], db_index=True, default='READY_FOR_PLANNING', max_length=30)),
                ('scheduled_date', models.DateField(blank=True, db_index=True, null=True)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('vehicle', models.CharField(blank=True, default='', max_length=120)),
                ('route', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('customer_signature', models.TextField(blank=True, default='')),
                ('closure_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmado'), ('DISPUTED', 'En disputa')], default='PENDING', max_length=10)),
                ('has_incident', models.BooleanField(db_index=True, default=False)),
                ('incident_notes', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('availability_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_operations', to='accounts.professionalavailability')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='service_operation', to='orders.order')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'operacion de servicio',
                'verbose_name_plural': 'operaciones de servicio',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOperationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_operation_events', to=settings.AUTH_USER_MODEL)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='technical_services.serviceoperation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='serviceoperation',
            index=models.Index(fields=['status', 'scheduled_date'], name='technical_s_status_187cd9_idx'),
        ),
    ]
