# Generated by Django 5.2.13 on 2026-07-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical_services', '0025_workingexception_workingschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingexception',
            name='exception_type',
            field=models.CharField(choices=[('VACATION', 'Vacaciones'), ('PERMIT', 'Permiso'), ('SICK_LEAVE', 'Incapacidad'), ('TRAINING', 'Capacitacion'), ('MAINTENANCE', 'Mantenimiento'), ('EXTRA_HOURS', 'Horas extra')], db_index=True, max_length=20),
        ),
    ]
