# Generated by Django 5.2.13 on 2026-07-16 23:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_seed_shop_operation_templates'),
        ('technical_services', '0026_alter_workingexception_exception_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('package_type', models.CharField(blank=True, default='', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='technical_services/packages/')),
                ('icon', models.CharField(blank=True, default='', max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('estimated_duration', models.DecimalField(blank=True, decimal_places=2, help_text='Duracion estimada en horas', max_digits=6, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='technical_services.technicalservice')),
            ],
            options={
                'verbose_name': 'paquete de servicio',
                'verbose_name_plural': 'paquetes de servicio',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageIncludedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=100)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='included_items', to='technical_services.servicepackage')),
            ],
            options={
                'verbose_name': 'item incluido en el paquete',
                'verbose_name_plural': 'items incluidos en el paquete',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageAdditionalCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('cost_type', models.CharField(choices=[('HERRAMIENTA', 'Herramienta'), ('ESCALERA', 'Escalera'), ('ACCESORIO', 'Accesorio'), ('CONSUMIBLE', 'Consumible'), ('OPERARIO', 'Operario'), ('SUPERVISOR', 'Supervisor'), ('TRABAJO_ALTURA', 'Trabajo en altura'), ('HORARIO_NOCTURNO', 'Horario nocturno'), ('URGENCIA', 'Urgencia'), ('OTRO', 'Otro')], db_index=True, default='OTRO', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(choices=[('FIJO', 'Fijo'), ('HORA', 'Por hora'), ('DIA', 'Por dia'), ('UNIDAD', 'Por unidad'), ('PERSONA', 'Por persona')], default='FIJO', max_length=10)),
                ('is_required', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_costs', to='technical_services.servicepackage')),
            ],
            options={
                'verbose_name': 'costo adicional de paquete',
                'verbose_name_plural': 'costos adicionales de paquete',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('package_name_snapshot', models.CharField(max_length=255)),
                ('package_price_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='request_package', to='orders.order')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='technical_services.servicepackage')),
            ],
            options={
                'verbose_name': 'paquete solicitado',
                'verbose_name_plural': 'paquetes solicitados',
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestAdditionalCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name_snapshot', models.CharField(max_length=255)),
                ('unit_price_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('subtotal_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('additional_cost', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='technical_services.packageadditionalcost')),
                ('request_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_costs', to='technical_services.servicerequestpackage')),
            ],
            options={
                'verbose_name': 'costo adicional solicitado',
                'verbose_name_plural': 'costos adicionales solicitados',
            },
        ),
    ]
