# Generated by Django 5.2.13 on 2026-08-05 17:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical_services', '0031_technicalservice_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalservice',
            name='coverage_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='technicalservice',
            name='scope',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='technicalservice',
            name='warranty',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='ServiceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('document_type', models.CharField(choices=[('MANUAL', 'Manual'), ('FICHA_TECNICA', 'Ficha tecnica'), ('CERTIFICADO', 'Certificado'), ('NORMATIVA', 'Normativa'), ('CATALOGO', 'Catalogo'), ('OTRO', 'Otro')], db_index=True, default='OTRO', max_length=20)),
                ('file', models.FileField(upload_to='services/documents/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='services/documents/covers/')),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='technical_services.technicalservice')),
            ],
            options={
                'verbose_name': 'documento de servicio',
                'verbose_name_plural': 'documentos de servicio',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceExcludedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_items', to='technical_services.technicalservice')),
            ],
            options={
                'verbose_name': 'item no incluido de servicio',
                'verbose_name_plural': 'items no incluidos de servicio',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceIncludedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='included_items', to='technical_services.technicalservice')),
            ],
            options={
                'verbose_name': 'item incluido de servicio',
                'verbose_name_plural': 'items incluidos de servicio',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('step_number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/process/')),
                ('estimated_time', models.CharField(blank=True, default='', help_text='Ej: 30 min, 1-2 horas', max_length=100)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='technical_services.technicalservice')),
            ],
            options={
                'verbose_name': 'paso del proceso de servicio',
                'verbose_name_plural': 'pasos del proceso de servicio',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='technical_services.technicalservice')),
            ],
            options={
                'verbose_name': 'requisito de servicio',
                'verbose_name_plural': 'requisitos de servicio',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceSpecificationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=100)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specification_groups', to='technical_services.technicalservice')),
            ],
            options={
                'verbose_name': 'grupo de ficha tecnica de servicio',
                'verbose_name_plural': 'grupos de ficha tecnica de servicio',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='technical_services.technicalservice')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='technical_services.servicespecificationgroup')),
            ],
            options={
                'verbose_name': 'especificacion de servicio',
                'verbose_name_plural': 'especificaciones de servicio',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('source_type', models.CharField(choices=[('YOUTUBE', 'YouTube'), ('VIMEO', 'Vimeo'), ('MP4', 'Archivo MP4')], default='YOUTUBE', max_length=10)),
                ('video_url', models.URLField(blank=True, default='')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='services/videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='services/videos/thumbs/')),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='technical_services.technicalservice')),
            ],
            options={
                'verbose_name': 'video de servicio',
                'verbose_name_plural': 'videos de servicio',
                'ordering': ['position', 'created_at'],
            },
        ),
    ]
