# Generated by Django 5.2.13 on 2026-08-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical_services', '0032_technicalservice_coverage_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicevariant',
            name='manual_project_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Solo MANUAL_PROJECT: precio total fijo del proyecto, duration no lo modifica.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='servicevariant',
            name='manual_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='MANUAL_GENERAL: precio fijo total. MANUAL_HOURLY: tarifa por hora (se multiplica por duration). No aplica a MANUAL_PROJECT ni AUTOMATIC.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='servicevariant',
            name='pricing_source',
            field=models.CharField(choices=[('AUTOMATIC', 'Automatico'), ('MANUAL_PROJECT', 'Manual - Proyecto completo'), ('MANUAL_GENERAL', 'Manual - Precio general'), ('MANUAL_HOURLY', 'Manual - Por horas')], db_index=True, default='AUTOMATIC', help_text='AUTOMATIC = LaborCostCalculator/SMLV (comportamiento actual). MANUAL_* = precio definido directamente por el administrador, ver ManualPricingCalculator.', max_length=20),
        ),
    ]
