# Generated by Django 5.2.13 on 2026-08-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical_services', '0033_servicevariant_manual_project_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderservicedetail',
            name='duration_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Horas/dias usados en el calculo (irrelevante para MANUAL_PROJECT/MANUAL_GENERAL).', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='orderservicedetail',
            name='pricing_mode_snapshot',
            field=models.CharField(blank=True, help_text='Para AUTOMATIC: pricing_strategy (HOURLY/DAILY/FIXED) usado en el calculo. None para modos MANUAL_* (pricing_source_snapshot ya es suficiente).', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderservicedetail',
            name='pricing_source_snapshot',
            field=models.CharField(blank=True, help_text='ServiceVariant.pricing_source al momento de la orden (AUTOMATIC/MANUAL_*).', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderservicedetail',
            name='project_price_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Solo MANUAL_PROJECT: manual_project_price aplicado.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='orderservicedetail',
            name='quotation_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderservicedetail',
            name='unit_price_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tarifa unitaria aplicada (labor_cost en AUTOMATIC, manual_unit_price en MANUAL_GENERAL/MANUAL_HOURLY). None en MANUAL_PROJECT.', max_digits=12, null=True),
        ),
    ]
