# Generated by Django 5.2.13 on 2026-08-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical_services', '0034_orderservicedetail_duration_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepricehistory',
            name='pricing_source_new',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='servicepricehistory',
            name='pricing_source_old',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='servicepricehistory',
            name='project_price_new',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='servicepricehistory',
            name='project_price_old',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='servicepricehistory',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='servicepricehistory',
            name='unit_price_new',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='servicepricehistory',
            name='unit_price_old',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
