# Generated by Django 5.2.13 on 2026-08-13 22:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical_services', '0035_servicepricehistory_pricing_source_new_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderservicedetail',
            name='confirmed_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total revisado/ajustado por un administrador (solo informativo -- NO reemplaza Order.total_amount, ver OrderPricingCommands).', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='orderservicedetail',
            name='price_status',
            field=models.CharField(choices=[('ESTIMATED', 'Estimado'), ('CONFIRMED', 'Confirmado'), ('OVERRIDDEN', 'Modificado por administrador'), ('LOCKED', 'Bloqueado')], default='ESTIMATED', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderPriceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('old_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('new_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField(blank=True, default='')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_price_overrides', to=settings.AUTH_USER_MODEL)),
                ('order_service_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_adjustments', to='technical_services.orderservicedetail')),
            ],
            options={
                'verbose_name': 'ajuste de precio de orden',
                'verbose_name_plural': 'ajustes de precio de ordenes',
                'ordering': ['-created_at'],
            },
        ),
    ]
