# Generated by Django 5.2.13 on 2026-08-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical_services', '0036_orderservicedetail_confirmed_total_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceimage',
            options={'ordering': ['display_order', 'created_at']},
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
