# Generated by Django 5.2.13 on 2026-07-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login exitoso'), ('LOGIN_FAILED', 'Login fallido'), ('KYC_REJECTED', 'KYC rechazado'), ('KYC_BLOCKED', 'KYC bloqueado'), ('RATE_LIMIT_HIT', 'Limite de tasa alcanzado'), ('FILE_REJECTED', 'Archivo rechazado'), ('PAYMENT_WEBHOOK_INVALID_SIGNATURE', 'Webhook de pago con firma invalida'), ('PAYMENT_DECLINED', 'Pago rechazado'), ('PAYMENT_CARD_REMOVED', 'Tarjeta guardada eliminada'), ('COUPON_REJECTED', 'Cupon invalido rechazado'), ('INVENTORY_MANUAL_ADJUSTMENT', 'Ajuste manual de inventario'), ('OPERATION_FORCE_CANCELLED', 'Operacion cancelada forzosamente')], db_index=True, max_length=40),
        ),
    ]
