# Generated by Django 5.2.13 on 2026-07-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_alter_securityevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login exitoso'), ('LOGIN_FAILED', 'Login fallido'), ('KYC_REJECTED', 'KYC rechazado'), ('KYC_BLOCKED', 'KYC bloqueado'), ('RATE_LIMIT_HIT', 'Limite de tasa alcanzado'), ('FILE_REJECTED', 'Archivo rechazado'), ('PAYMENT_WEBHOOK_INVALID_SIGNATURE', 'Webhook de pago con firma invalida'), ('PAYMENT_APPROVED', 'Pago aprobado'), ('PAYMENT_DECLINED', 'Pago rechazado'), ('PAYMENT_CARD_REMOVED', 'Tarjeta guardada eliminada'), ('PAYMENT_TRANSACTION_ABANDONED', 'Transaccion de pago abandonada (sin wompi_id tras el umbral)'), ('PAYMENT_FEATURE_FLAG_CHANGED', 'Flag operativo de pagos modificado'), ('COUPON_REJECTED', 'Cupon invalido rechazado'), ('INVENTORY_MANUAL_ADJUSTMENT', 'Ajuste manual de inventario'), ('OPERATION_FORCE_CANCELLED', 'Operacion cancelada forzosamente'), ('NOTIFICATION_CHANNEL_FAILED', 'Canal de notificacion con fallo permanente'), ('AI_ACTION_EXECUTED', 'Accion de escritura ejecutada por el AI Core')], db_index=True, max_length=40),
        ),
    ]
