# Generated by Django 5.2.13 on 2026-09-25 18:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0010_ai_security_flag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login exitoso'), ('LOGIN_FAILED', 'Login fallido'), ('KYC_REJECTED', 'KYC rechazado'), ('KYC_BLOCKED', 'KYC bloqueado'), ('RATE_LIMIT_HIT', 'Limite de tasa alcanzado'), ('FILE_REJECTED', 'Archivo rechazado'), ('PAYMENT_WEBHOOK_INVALID_SIGNATURE', 'Webhook de pago con firma invalida'), ('PAYMENT_APPROVED', 'Pago aprobado'), ('PAYMENT_DECLINED', 'Pago rechazado'), ('PAYMENT_CARD_REMOVED', 'Tarjeta guardada eliminada'), ('PAYMENT_TRANSACTION_ABANDONED', 'Transaccion de pago abandonada (sin wompi_id tras el umbral)'), ('PAYMENT_FEATURE_FLAG_CHANGED', 'Flag operativo de pagos modificado'), ('COUPON_REJECTED', 'Cupon invalido rechazado'), ('INVENTORY_MANUAL_ADJUSTMENT', 'Ajuste manual de inventario'), ('OPERATION_FORCE_CANCELLED', 'Operacion cancelada forzosamente'), ('NOTIFICATION_CHANNEL_FAILED', 'Canal de notificacion con fallo permanente'), ('AI_ACTION_EXECUTED', 'Accion de escritura ejecutada por el AI Core'), ('ADMIN_RESOURCE_DELETED', 'Recurso eliminado desde el panel administrativo'), ('PAYMENT_SYNC_REFERENCE_MISMATCH', 'Reconciliacion de pago rechazada: reference/monto no coincide'), ('AI_PROVIDER_CREATED', 'Proveedor de IA creado'), ('AI_PROVIDER_UPDATED', 'Proveedor de IA actualizado'), ('AI_PROVIDER_ACTIVATED', 'Proveedor de IA activado'), ('AI_PROVIDER_DEACTIVATED', 'Proveedor de IA desactivado'), ('AI_PROVIDER_TESTED', 'Conexion de proveedor de IA probada'), ('AI_MODEL_CHANGED', 'Modelo de IA agregado/eliminado'), ('AI_CHANNEL_CHANGED', 'Configuracion de canal de IA modificada (primario/fallback)'), ('AI_SECURITY_FLAG', 'Senal de seguridad en un turno de IA (fuga bloqueada, secreto redactado, inyeccion)'), ('MCP_TOKEN_CREATED', 'Token personal del servidor MCP creado'), ('MCP_TOKEN_REVOKED', 'Token personal del servidor MCP revocado'), ('MCP_TOKEN_EXCHANGED', 'Token del servidor MCP canjeado por un JWT corto'), ('MCP_TOKEN_EXCHANGE_FAILED', 'Canje de token MCP rechazado (invalido, revocado, caducado o sin permisos)'), ('MCP_ACTION', 'Accion ejecutada por un cliente MCP')], db_index=True, max_length=40),
        ),
        migrations.CreateModel(
            name='McpAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=100)),
                ('token_prefix', models.CharField(help_text='Primeros caracteres, solo para identificar el token en listados.', max_length=16)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
