# Generated by Django 5.2.13 on 2026-07-30 22:48

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


# Squash de quotes 0001-0035 (DT-M18, migration squashing). Rango completo:
# a diferencia de technical_services, ninguna app del proyecto depende de
# ninguna migracion de `quotes` (confirmado por grep de "quotes"/'quotes' en
# migrations/*.py de todas las apps -- el unico hit fue un falso positivo,
# un choices tuple de CharField en core/migrations/0001_initial.py, no una
# dependencia real), asi que `quotes` es una app "hoja" en el grafo y no hay
# riesgo de CircularDependencyError sin importar el rango squasheado. Las 9
# funciones RunPython de abajo se copiaron manualmente desde sus migraciones
# originales (0018/0019/0021/0027/0028/0029/0030/0032/0034) por pedido
# explicito de Django ("Manual porting required") -- las originales NO se
# borraron (siguen en este mismo directorio). Renombradas con sufijo por
# migracion de origen (varias compartian nombres genericos como
# seed_questions/remove_questions/TEMPLATE_SLUG/noop_backward). Todas son
# no-op seguras sobre una BD nueva vacia: filter().update()/.delete() sobre
# tablas vacias, bulk_create([]) sobre una queryset vacia, o un `if not
# template: return` temprano (el template "instalacion-cctv" que varias de
# estas migraciones buscan no existe en una BD nueva sin seed previo).
from django.utils.text import slugify


STATUS_REMAP_0018 = {
    'DRAFT': 'BORRADOR',
    'SENT': 'ENVIADA',
    'ACCEPTED': 'ACEPTADA',
    'REJECTED': 'RECHAZADA',
    'EXPIRED': 'VENCIDA',
}


def remap_status_forward_0018(apps, schema_editor):
    """Copiada de 0018_quotation_status_rework.py."""
    Quotation = apps.get_model('quotes', 'Quotation')
    for old, new in STATUS_REMAP_0018.items():
        Quotation.objects.filter(status=old).update(status=new)


def remap_status_backward_0018(apps, schema_editor):
    """Copiada de 0018_quotation_status_rework.py."""
    Quotation = apps.get_model('quotes', 'Quotation')
    for old, new in STATUS_REMAP_0018.items():
        Quotation.objects.filter(status=new).update(status=old)


def backfill_timeline_0019(apps, schema_editor):
    """Copiada de 0019_quotationtimeline.py."""
    Quotation = apps.get_model('quotes', 'Quotation')
    QuotationTimeline = apps.get_model('quotes', 'QuotationTimeline')
    QuotationTimeline.objects.bulk_create([
        QuotationTimeline(quotation=q, status=q.status, notes='Estado inicial migrado.')
        for q in Quotation.objects.filter(is_deleted=False)
    ])


def noop_backward_0019(apps, schema_editor):
    """Copiada de 0019_quotationtimeline.py."""
    pass


def seed_service_types_0021(apps, schema_editor):
    """Copiada de 0021_quotetemplateattribute_and_more.py."""
    QuoteTemplateAttribute = apps.get_model('quotes', 'QuoteTemplateAttribute')
    for i, name in enumerate(['Nueva instalacion', 'Mantenimiento', 'Servicio tecnico']):
        QuoteTemplateAttribute.objects.get_or_create(
            kind='SERVICE_TYPE', slug=slugify(name),
            defaults={'name': name, 'display_order': i},
        )


def noop_backward_0021(apps, schema_editor):
    """Copiada de 0021_quotetemplateattribute_and_more.py."""
    pass


TASK_NAME_0027 = "notify-quotations-without-response"


def create_periodic_task_0027(apps, schema_editor):
    """Copiada de 0027_seed_notify_quotations_periodic_task.py."""
    CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    schedule, _ = CrontabSchedule.objects.get_or_create(
        minute="0", hour="9", day_of_week="*", day_of_month="*", month_of_year="*",
    )
    PeriodicTask.objects.update_or_create(
        name=TASK_NAME_0027,
        defaults={
            "crontab": schedule,
            "task": "quotes.tasks.notify_quotations_without_response",
            "enabled": True,
        },
    )


def remove_periodic_task_0027(apps, schema_editor):
    """Copiada de 0027_seed_notify_quotations_periodic_task.py."""
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    PeriodicTask.objects.filter(name=TASK_NAME_0027).delete()


TEMPLATE_SLUG_0028 = "instalacion-cctv"
GROUP_LABEL_0028 = "Informacion de la Instalacion"

QUESTIONS_0028 = [
    {
        "key": "farthest_equipment_distance",
        "question_type": "NUMBER",
        "label": "Distancia del equipo mas lejano",
        "help_text": "¿Cuantos metros aproximadamente hay desde el punto principal de instalacion hasta el equipo mas lejano?",
        "placeholder": "Ejemplo: 85",
        "unit": "metros",
        "is_required": True,
        "min_value": 1,
        "max_value": 1000,
        "display_order": 1,
    },
    {
        "key": "nearest_equipment_distance",
        "question_type": "NUMBER",
        "label": "Distancia del equipo mas cercano",
        "help_text": "¿Cuantos metros aproximadamente hay desde el punto principal de instalacion hasta el equipo mas cercano?",
        "placeholder": "Ejemplo: 8",
        "unit": "metros",
        "is_required": False,
        "min_value": 0,
        "max_value": 1000,
        "display_order": 2,
    },
    {
        "key": "installation_environment",
        "question_type": "RADIO",
        "label": "Tipo de instalacion",
        "help_text": "¿Donde se realizara la instalacion?",
        "is_required": False,
        "display_order": 3,
        "options": ["Interior", "Exterior", "Mixta (Interior y Exterior)"],
    },
    {
        "key": "project_type",
        "question_type": "SELECT",
        "label": "Tipo de proyecto",
        "help_text": "¿Para que tipo de instalacion necesitas la cotizacion?",
        "is_required": False,
        "allow_other": True,
        "display_order": 4,
        "options": [
            "Hogar", "Empresa", "Oficina", "Local Comercial", "Retail",
            "Centro Comercial", "Conjunto Residencial", "Edificio", "Hospital",
            "Clinica", "Industria", "Bodega", "Parqueadero", "Hotel",
            "Institucion Educativa", "Entidad Publica",
        ],
    },
    {
        "key": "project_location",
        "question_type": "GPS",
        "label": "Comparte tu ubicacion",
        "help_text": "Comparte la ubicacion aproximada donde se realizara la instalacion.",
        "is_required": False,
        "display_order": 5,
    },
    {
        "key": "project_address",
        "question_type": "ADDRESS",
        "label": "Direccion del proyecto",
        "is_required": False,
        "display_order": 6,
        "depends_on_key": "project_location",
        "depends_on_values": ["DENIED"],
    },
    {
        "key": "existing_infrastructure",
        "question_type": "RADIO",
        "label": "¿Existe actualmente infraestructura instalada?",
        "is_required": False,
        "display_order": 7,
        "options": [
            "Si, se puede reutilizar",
            "Si, pero requiere adecuaciones",
            "No existe infraestructura",
            "No estoy seguro",
        ],
    },
]


def seed_questions_0028(apps, schema_editor):
    """Copiada de 0028_seed_installation_info_questions.py."""
    QuoteTemplate = apps.get_model("quotes", "QuoteTemplate")
    QuoteTemplateModule = apps.get_model("quotes", "QuoteTemplateModule")
    QuoteQuestion = apps.get_model("quotes", "QuoteQuestion")
    QuoteQuestionOption = apps.get_model("quotes", "QuoteQuestionOption")

    template = QuoteTemplate.objects.filter(slug=TEMPLATE_SLUG_0028, is_deleted=False).first()
    if not template:
        return

    module = QuoteTemplateModule.objects.filter(
        template=template, module_type="MATERIALS", is_deleted=False,
    ).order_by("display_order", "id").first()
    if not module:
        return

    created_by_key = {}
    for spec in QUESTIONS_0028:
        options = spec.pop("options", None)
        depends_on_key = spec.pop("depends_on_key", None)
        question, _ = QuoteQuestion.objects.get_or_create(
            module=module, key=spec["key"],
            defaults={**spec, "group": GROUP_LABEL_0028},
        )
        created_by_key[spec["key"]] = question
        if options and not question.options.exists():
            for i, label in enumerate(options):
                QuoteQuestionOption.objects.create(
                    question=question, label=label, value=label, display_order=i,
                )

    address_q = created_by_key.get("project_address")
    location_q = created_by_key.get("project_location")
    if address_q and location_q and not address_q.depends_on_question_id:
        address_q.depends_on_question = location_q
        address_q.save(update_fields=["depends_on_question"])


def remove_questions_0028(apps, schema_editor):
    """Copiada de 0028_seed_installation_info_questions.py."""
    QuoteTemplate = apps.get_model("quotes", "QuoteTemplate")
    QuoteTemplateModule = apps.get_model("quotes", "QuoteTemplateModule")
    QuoteQuestion = apps.get_model("quotes", "QuoteQuestion")

    template = QuoteTemplate.objects.filter(slug=TEMPLATE_SLUG_0028).first()
    if not template:
        return
    module = QuoteTemplateModule.objects.filter(template=template, module_type="MATERIALS").first()
    if not module:
        return
    QuoteQuestion.objects.filter(
        module=module, key__in=[q["key"] for q in QUESTIONS_0028] + ["project_address"],
    ).delete()


TEMPLATE_SLUG_0029 = "instalacion-cctv"
MODULE_NAME_0029 = "Condiciones de Instalacion"

QUESTIONS_0029 = [
    {
        "key": "installation_height", "question_type": "NUMBER",
        "label": "Altura de instalacion",
        "help_text": "¿A que altura aproximada se instalaran los equipos?",
        "placeholder": "Ejemplo: 4", "unit": "metros",
        "is_required": True, "min_value": 0, "max_value": 100, "display_order": 1,
    },
    {
        "key": "work_at_height", "question_type": "RADIO",
        "label": "Trabajo en alturas",
        "help_text": "¿La instalacion requiere trabajo seguro en alturas?",
        "is_required": False, "display_order": 2,
        "options": ["Si", "No", "No estoy seguro"],
    },
    {
        "key": "hsq_requirements", "question_type": "CHECKBOX",
        "label": "Nivel de riesgo HSQ",
        "help_text": "¿Que requisitos de Seguridad y Salud en el Trabajo exige el sitio?",
        "is_required": False, "display_order": 3,
        "options": [
            "Ninguno", "Permiso de trabajo", "Induccion HSEQ", "ARL vigente",
            "Curso de alturas", "Uso obligatorio de EPP", "Supervisor SST",
            "Analisis de Riesgos", "ATS", "Permiso de Energia", "LOTO",
            "No conozco los requisitos",
        ],
    },
    {
        "key": "access_equipment", "question_type": "MULTISELECT",
        "label": "Equipos de acceso requeridos",
        "help_text": "¿Que equipos seran necesarios para realizar la instalacion?",
        "is_required": False, "display_order": 4,
        "options": [
            "Escalera", "Andamio", "Plataforma Elevadora", "Manlift",
            "Canastilla", "Grua", "Ninguno", "No estoy seguro",
        ],
    },
    {
        "key": "scaffold_height", "question_type": "NUMBER",
        "label": "Altura estimada del andamio",
        "help_text": "¿Cual es la altura estimada del andamio?",
        "placeholder": "Ejemplo: 3", "unit": "metros",
        "is_required": False, "min_value": 0, "max_value": 100, "display_order": 5,
        "depends_on_key": "access_equipment", "depends_on_values": ["Andamio"],
    },
    {
        "key": "platform_access_type", "question_type": "TEXT",
        "label": "Tipo de plataforma elevadora",
        "help_text": "¿Que tipo de acceso requiere la plataforma elevadora?",
        "placeholder": "Ejemplo: tijera, brazo articulado, autopropulsada...",
        "is_required": False, "display_order": 6,
        "depends_on_key": "access_equipment", "depends_on_values": ["Plataforma Elevadora"],
    },
    {
        "key": "allowed_schedule", "question_type": "MULTISELECT",
        "label": "Horario permitido",
        "help_text": "¿En que horario puede realizarse la instalacion?",
        "is_required": False, "display_order": 7,
        "options": [
            "Horario Diurno", "Horario Nocturno", "Fin de Semana", "Festivos",
            "24 Horas", "Horario Administrativo", "No tengo restriccion",
        ],
    },
    {
        "key": "site_operation_status", "question_type": "RADIO",
        "label": "Disponibilidad del sitio",
        "help_text": "¿El lugar permanecera operativo durante la instalacion?",
        "is_required": False, "display_order": 8,
        "options": ["Si", "No", "Parcialmente"],
    },
    {
        "key": "site_access_requirements", "question_type": "MULTISELECT",
        "label": "Restricciones de ingreso",
        "help_text": "¿Existen restricciones para ingresar al sitio?",
        "is_required": False, "display_order": 9,
        "options": [
            "Registro previo", "Documento de identidad", "Autorizacion previa",
            "Carnet empresarial", "Curso de induccion", "Elementos de proteccion",
            "Vehiculo autorizado", "Ninguna", "No se",
        ],
    },
    {
        "key": "power_available", "question_type": "RADIO",
        "label": "Disponibilidad de energia",
        "help_text": "¿Existe alimentacion electrica disponible en el sitio?",
        "is_required": False, "display_order": 10,
        "options": ["Si", "No", "No estoy seguro"],
    },
    {
        "key": "service_shutdown_required", "question_type": "RADIO",
        "label": "Interrupcion del servicio",
        "help_text": "¿La instalacion requiere suspender temporalmente algun servicio?",
        "is_required": False, "display_order": 11,
        "options": ["Si", "No", "No lo se"],
    },
    {
        "key": "labor_notes", "question_type": "TEXTAREA",
        "label": "Observaciones",
        "help_text": "¿Hay alguna condicion especial que debamos conocer antes de realizar la instalacion?",
        "placeholder": "Ejemplo: El area solo esta disponible despues de las 8:00 p.m.",
        "is_required": False, "display_order": 12,
    },
]


def seed_questions_0029(apps, schema_editor):
    """Copiada de 0029_seed_labor_questions.py."""
    QuoteTemplate = apps.get_model("quotes", "QuoteTemplate")
    QuoteTemplateModule = apps.get_model("quotes", "QuoteTemplateModule")
    QuoteQuestion = apps.get_model("quotes", "QuoteQuestion")
    QuoteQuestionOption = apps.get_model("quotes", "QuoteQuestionOption")

    template = QuoteTemplate.objects.filter(slug=TEMPLATE_SLUG_0029, is_deleted=False).first()
    if not template:
        return

    module = QuoteTemplateModule.objects.filter(
        template=template, module_type="LABOR", is_deleted=False,
    ).order_by("display_order", "id").first()
    if not module:
        module = QuoteTemplateModule.objects.create(
            template=template, module_type="LABOR", name=MODULE_NAME_0029,
            display_order=2,
        )

    created_by_key = {}
    for spec in QUESTIONS_0029:
        options = spec.pop("options", None)
        depends_on_key = spec.pop("depends_on_key", None)
        question, _ = QuoteQuestion.objects.get_or_create(
            module=module, key=spec["key"], defaults=spec,
        )
        created_by_key[spec["key"]] = question
        if options and not question.options.exists():
            for i, label in enumerate(options):
                QuoteQuestionOption.objects.create(
                    question=question, label=label, value=label, display_order=i,
                )
        if depends_on_key:
            spec["_depends_on_key"] = depends_on_key

    for spec in QUESTIONS_0029:
        depends_on_key = spec.get("_depends_on_key")
        if not depends_on_key:
            continue
        question = created_by_key[spec["key"]]
        parent = created_by_key.get(depends_on_key)
        if parent and not question.depends_on_question_id:
            question.depends_on_question = parent
            question.save(update_fields=["depends_on_question"])


def remove_questions_0029(apps, schema_editor):
    """Copiada de 0029_seed_labor_questions.py."""
    QuoteTemplate = apps.get_model("quotes", "QuoteTemplate")
    QuoteTemplateModule = apps.get_model("quotes", "QuoteTemplateModule")
    QuoteQuestion = apps.get_model("quotes", "QuoteQuestion")
    template = QuoteTemplate.objects.filter(slug=TEMPLATE_SLUG_0029).first()
    if not template:
        return
    module = QuoteTemplateModule.objects.filter(template=template, module_type="LABOR", name=MODULE_NAME_0029).first()
    if not module:
        return
    QuoteQuestion.objects.filter(module=module, key__in=[q["key"] for q in QUESTIONS_0029]).delete()
    if not module.questions.exists():
        module.delete()


TEMPLATE_SLUG_0030 = "instalacion-cctv"

REMOVED_KEYS_0030 = [
    "work_at_height",
    "hsq_requirements",
    "access_equipment",
    "scaffold_height",
    "platform_access_type",
    "site_operation_status",
    "service_shutdown_required",
]

NEW_HEIGHT_HELP_TEXT_0030 = (
    "Si la instalacion supera los 2 metros de altura, se considera trabajo "
    "en alturas y el sistema determinara automaticamente las medidas de "
    "seguridad."
)
OLD_HEIGHT_HELP_TEXT_0030 = "¿A que altura aproximada se instalaran los equipos?"

REMOVED_QUESTIONS_ORIGINAL_0030 = [
    {
        "key": "work_at_height", "question_type": "RADIO",
        "label": "Trabajo en alturas",
        "help_text": "¿La instalacion requiere trabajo seguro en alturas?",
        "is_required": False, "display_order": 2,
        "options": ["Si", "No", "No estoy seguro"],
    },
    {
        "key": "hsq_requirements", "question_type": "CHECKBOX",
        "label": "Nivel de riesgo HSQ",
        "help_text": "¿Que requisitos de Seguridad y Salud en el Trabajo exige el sitio?",
        "is_required": False, "display_order": 3,
        "options": [
            "Ninguno", "Permiso de trabajo", "Induccion HSEQ", "ARL vigente",
            "Curso de alturas", "Uso obligatorio de EPP", "Supervisor SST",
            "Analisis de Riesgos", "ATS", "Permiso de Energia", "LOTO",
            "No conozco los requisitos",
        ],
    },
    {
        "key": "access_equipment", "question_type": "MULTISELECT",
        "label": "Equipos de acceso requeridos",
        "help_text": "¿Que equipos seran necesarios para realizar la instalacion?",
        "is_required": False, "display_order": 4,
        "options": [
            "Escalera", "Andamio", "Plataforma Elevadora", "Manlift",
            "Canastilla", "Grua", "Ninguno", "No estoy seguro",
        ],
    },
    {
        "key": "scaffold_height", "question_type": "NUMBER",
        "label": "Altura estimada del andamio",
        "help_text": "¿Cual es la altura estimada del andamio?",
        "placeholder": "Ejemplo: 3", "unit": "metros",
        "is_required": False, "min_value": 0, "max_value": 100, "display_order": 5,
        "depends_on_key": "access_equipment", "depends_on_values": ["Andamio"],
    },
    {
        "key": "platform_access_type", "question_type": "TEXT",
        "label": "Tipo de plataforma elevadora",
        "help_text": "¿Que tipo de acceso requiere la plataforma elevadora?",
        "placeholder": "Ejemplo: tijera, brazo articulado, autopropulsada...",
        "is_required": False, "display_order": 6,
        "depends_on_key": "access_equipment", "depends_on_values": ["Plataforma Elevadora"],
    },
    {
        "key": "site_operation_status", "question_type": "RADIO",
        "label": "Disponibilidad del sitio",
        "help_text": "¿El lugar permanecera operativo durante la instalacion?",
        "is_required": False, "display_order": 8,
        "options": ["Si", "No", "Parcialmente"],
    },
    {
        "key": "service_shutdown_required", "question_type": "RADIO",
        "label": "Interrupcion del servicio",
        "help_text": "¿La instalacion requiere suspender temporalmente algun servicio?",
        "is_required": False, "display_order": 11,
        "options": ["Si", "No", "No lo se"],
    },
]


def simplify_questions_0030(apps, schema_editor):
    """Copiada de 0030_simplify_labor_questions.py."""
    QuoteTemplate = apps.get_model("quotes", "QuoteTemplate")
    QuoteTemplateModule = apps.get_model("quotes", "QuoteTemplateModule")
    QuoteQuestion = apps.get_model("quotes", "QuoteQuestion")

    template = QuoteTemplate.objects.filter(slug=TEMPLATE_SLUG_0030, is_deleted=False).first()
    if not template:
        return
    module = QuoteTemplateModule.objects.filter(template=template, module_type="LABOR").first()
    if not module:
        return

    QuoteQuestion.objects.filter(module=module, key__in=REMOVED_KEYS_0030).delete()
    QuoteQuestion.objects.filter(module=module, key="installation_height").update(
        help_text=NEW_HEIGHT_HELP_TEXT_0030,
    )


def restore_questions_0030(apps, schema_editor):
    """Copiada de 0030_simplify_labor_questions.py."""
    QuoteTemplate = apps.get_model("quotes", "QuoteTemplate")
    QuoteTemplateModule = apps.get_model("quotes", "QuoteTemplateModule")
    QuoteQuestion = apps.get_model("quotes", "QuoteQuestion")
    QuoteQuestionOption = apps.get_model("quotes", "QuoteQuestionOption")

    template = QuoteTemplate.objects.filter(slug=TEMPLATE_SLUG_0030).first()
    if not template:
        return
    module = QuoteTemplateModule.objects.filter(template=template, module_type="LABOR").first()
    if not module:
        return

    QuoteQuestion.objects.filter(module=module, key="installation_height").update(
        help_text=OLD_HEIGHT_HELP_TEXT_0030,
    )

    created_by_key = {}
    for spec in REMOVED_QUESTIONS_ORIGINAL_0030:
        spec = dict(spec)
        options = spec.pop("options", None)
        depends_on_key = spec.pop("depends_on_key", None)
        question, _ = QuoteQuestion.objects.get_or_create(
            module=module, key=spec["key"], defaults=spec,
        )
        created_by_key[spec["key"]] = question
        if options and not question.options.exists():
            for i, label in enumerate(options):
                QuoteQuestionOption.objects.create(
                    question=question, label=label, value=label, display_order=i,
                )
        if depends_on_key:
            parent = created_by_key.get(depends_on_key) or QuoteQuestion.objects.filter(
                module=module, key=depends_on_key,
            ).first()
            if parent and not question.depends_on_question_id:
                question.depends_on_question = parent
                question.save(update_fields=["depends_on_question"])


TEMPLATE_SLUG_0032 = "instalacion-cctv"
INSTALLATION_GROUP_0032 = "Informacion de la Instalacion"
DOCUMENT_GROUP_0032 = "Documentacion Adjunta"

COLOMBIA_CITIES_0032 = [
    "Acacías", "Aguachica", "Aguazul", "Arauca", "Arauquita", "Armenia",
    "Barrancabermeja", "Barranquilla", "Bello", "Bogotá, D.C.", "Bosconia",
    "Bucaramanga", "Buenaventura", "Buga", "Cajicá", "Calarcá", "Caldas",
    "Cali", "Cartagena de Indias", "Cartago", "Cereté", "Chaparral", "Chía",
    "Chinchiná", "Chiquinquirá", "Ciénaga", "Copacabana", "Corozal", "Cúcuta",
    "Dosquebradas", "Duitama", "El Carmen de Bolívar", "Envigado", "Espinal",
    "Facatativá", "Florencia", "Floridablanca", "Fundación", "Funza",
    "Fusagasugá", "Galapa", "Garzón", "Girardot", "Girón", "Granada", "Honda",
    "Ibagué", "Inírida", "Ipiales", "Istmina", "Itagüí", "Jamundí",
    "La Dorada", "La Estrella", "La Paz", "La Plata", "La Virginia",
    "Leticia", "Lorica", "Los Patios", "Madrid", "Magangué", "Maicao",
    "Malambo", "Manaure", "Manizales", "Medellín", "Melgar", "Mitú", "Mocoa",
    "Mompox", "Montenegro", "Montería", "Mosquera", "Neiva", "Ocaña",
    "Orito", "Paipa", "Palmira", "Pamplona", "Pasto", "Pereira",
    "Piedecuesta", "Pitalito", "Plato", "Popayán", "Providencia",
    "Puerto Asís", "Puerto Carreño", "Puerto Colombia", "Puerto López",
    "Puerto Nariño", "Puerto Tejada", "Quibdó", "Quimbaya", "Riohacha",
    "Rionegro", "Riosucio", "Sabanalarga", "Sabaneta", "Sampués",
    "San Andrés", "San Gil", "San José del Guaviare", "San Marcos",
    "San Martín", "San Vicente del Caguán", "Santa Marta",
    "Santa Rosa de Cabal", "Santander de Quilichao", "Saravena", "Sincelejo",
    "Soacha", "Sogamoso", "Soledad", "Tame", "Tauramena", "Tierralta",
    "Tuluá", "Tumaco", "Tunja", "Túquerres", "Turbaco", "Uribia",
    "Valle del Guamuez", "Valledupar", "Villa del Rosario", "Villanueva",
    "Villavicencio", "Yopal", "Yumbo", "Zipaquirá",
]

MATERIALS_MODULE_UUID_0032 = "ca7d3530-f228-4baa-a434-5ed35d3e8428"
EQUIPMENT_MODULE_UUID_0032 = "a914c992-7c7b-4cb8-b712-29d72b3797da"
MATERIALS_MODULE_NEW_NAME_0032 = "Informacion del Proyecto"

MATERIALS_REORDER_0032 = {
    "farthest_equipment_distance": 1,
    "nearest_equipment_distance": 2,
    "installation_environment": 3,
    "project_type": 4,
    "project_location": 7,
    "project_address": 8,
    "existing_infrastructure": 9,
}

NEW_MATERIALS_QUESTIONS_0032 = [
    {
        "key": "installation_city", "question_type": "SELECT",
        "label": "Ciudad de la instalacion",
        "help_text": "¿En que ciudad se realizara la instalacion?",
        "is_required": False, "display_order": 5,
        "options": COLOMBIA_CITIES_0032,
    },
    {
        "key": "installation_address", "question_type": "TEXT",
        "label": "Direccion de la instalacion",
        "help_text": "¿Cual es la direccion donde se realizara la instalacion?",
        "is_required": False, "display_order": 6,
    },
]

NEW_EQUIPMENT_QUESTIONS_0032 = [
    {
        "key": "has_requirement_document", "question_type": "RADIO",
        "label": "¿Ya tienes un documento con los requerimientos?",
        "help_text": (
            "Si ya tienes un documento con las especificaciones tecnicas, pliego "
            "de condiciones, lista de requerimientos o cualquier informacion "
            "relacionada con la instalacion, puedes adjuntarlo aqui. Nuestro "
            "equipo utilizara esta informacion para complementar el analisis "
            "de tu solicitud."
        ),
        "is_required": False, "display_order": 0,
        "options": ["Si, deseo adjuntar un documento.", "No, continuare diligenciando el formulario."],
    },
    {
        "key": "requirement_documents", "question_type": "FILE",
        "label": "Documentos de requerimientos",
        "help_text": "PDF, DOC, DOCX, XLS, XLSX o TXT -- maximo 20 MB por archivo.",
        "is_required": False, "display_order": 1,
        "depends_on_key": "has_requirement_document",
        "depends_on_values": ["Si, deseo adjuntar un documento."],
    },
]


def optimize_flow_0032(apps, schema_editor):
    """Copiada de 0032_optimize_installation_flow.py."""
    QuoteTemplate = apps.get_model("quotes", "QuoteTemplate")
    QuoteTemplateModule = apps.get_model("quotes", "QuoteTemplateModule")
    QuoteQuestion = apps.get_model("quotes", "QuoteQuestion")
    QuoteQuestionOption = apps.get_model("quotes", "QuoteQuestionOption")

    template = QuoteTemplate.objects.filter(slug=TEMPLATE_SLUG_0032, is_deleted=False).first()
    if not template:
        return

    materials_module = QuoteTemplateModule.objects.filter(uuid=MATERIALS_MODULE_UUID_0032).first()
    equipment_module = QuoteTemplateModule.objects.filter(uuid=EQUIPMENT_MODULE_UUID_0032).first()

    if materials_module:
        materials_module.name = MATERIALS_MODULE_NEW_NAME_0032
        materials_module.save(update_fields=["name"])

        for key, order in MATERIALS_REORDER_0032.items():
            QuoteQuestion.objects.filter(module=materials_module, key=key).update(display_order=order)

        for spec in NEW_MATERIALS_QUESTIONS_0032:
            spec = dict(spec)
            options = spec.pop("options", None)
            question, _ = QuoteQuestion.objects.get_or_create(
                module=materials_module, key=spec["key"],
                defaults={**spec, "group": INSTALLATION_GROUP_0032},
            )
            if options and not question.options.exists():
                for i, label in enumerate(options):
                    QuoteQuestionOption.objects.create(
                        question=question, label=label, value=label, display_order=i,
                    )

    if equipment_module:
        QuoteQuestion.objects.filter(module=equipment_module, key="height").delete()

        QuoteQuestion.objects.filter(module=equipment_module, key="tipo_de_inmueble").update(display_order=10)
        QuoteQuestion.objects.filter(module=equipment_module, key="camera_count").update(display_order=11)

        created_by_key = {}
        pending_deps = []
        for spec in NEW_EQUIPMENT_QUESTIONS_0032:
            spec = dict(spec)
            options = spec.pop("options", None)
            depends_on_key = spec.pop("depends_on_key", None)
            question, _ = QuoteQuestion.objects.get_or_create(
                module=equipment_module, key=spec["key"],
                defaults={**spec, "group": DOCUMENT_GROUP_0032},
            )
            created_by_key[spec["key"]] = question
            if options and not question.options.exists():
                for i, label in enumerate(options):
                    QuoteQuestionOption.objects.create(
                        question=question, label=label, value=label, display_order=i,
                    )
            if depends_on_key:
                pending_deps.append((question, depends_on_key))

        for question, depends_on_key in pending_deps:
            parent = created_by_key.get(depends_on_key)
            if parent and not question.depends_on_question_id:
                question.depends_on_question = parent
                question.save(update_fields=["depends_on_question"])


def revert_flow_0032(apps, schema_editor):
    """Copiada de 0032_optimize_installation_flow.py."""
    QuoteTemplateModule = apps.get_model("quotes", "QuoteTemplateModule")
    QuoteQuestion = apps.get_model("quotes", "QuoteQuestion")

    materials_module = QuoteTemplateModule.objects.filter(uuid=MATERIALS_MODULE_UUID_0032).first()
    if materials_module:
        materials_module.name = "Cableado"
        materials_module.save(update_fields=["name"])
        QuoteQuestion.objects.filter(
            module=materials_module, key__in=["installation_city", "installation_address"],
        ).delete()

    equipment_module = QuoteTemplateModule.objects.filter(uuid=EQUIPMENT_MODULE_UUID_0032).first()
    if equipment_module:
        QuoteQuestion.objects.filter(
            module=equipment_module, key__in=["has_requirement_document", "requirement_documents"],
        ).delete()
        QuoteQuestion.objects.get_or_create(
            module=equipment_module, key="height",
            defaults={
                "question_type": "NUMBER", "label": "Altura de instalacion (m)",
                "is_required": False, "display_order": 0,
            },
        )


QA_TEMPLATE_SLUG_0034 = "instalacion-cctv-qa"


def hide_qa_and_fix_camera_count_0034(apps, schema_editor):
    """Copiada de 0034_hide_qa_template_and_fix_camera_count.py."""
    QuoteTemplate = apps.get_model("quotes", "QuoteTemplate")
    QuoteQuestion = apps.get_model("quotes", "QuoteQuestion")

    QuoteTemplate.objects.filter(slug=QA_TEMPLATE_SLUG_0034).update(
        is_published=False, is_internal=True,
    )

    QuoteQuestion.objects.filter(
        module__template__slug="instalacion-cctv", key="camera_count",
    ).update(min_value=1, max_value=5000, placeholder="Ejemplo: 8")


def reverse_0034(apps, schema_editor):
    """Copiada de 0034_hide_qa_template_and_fix_camera_count.py."""
    QuoteTemplate = apps.get_model("quotes", "QuoteTemplate")
    QuoteQuestion = apps.get_model("quotes", "QuoteQuestion")
    QuoteTemplate.objects.filter(slug=QA_TEMPLATE_SLUG_0034).update(
        is_published=True, is_internal=False,
    )
    QuoteQuestion.objects.filter(
        module__template__slug="instalacion-cctv", key="camera_count",
    ).update(min_value=None, max_value=None, placeholder="")


class Migration(migrations.Migration):

    replaces = [('quotes', '0001_initial'), ('quotes', '0002_remove_quotationservice_material_cost_and_more'), ('quotes', '0003_remove_quotationitem_product_quotationitem_sku_and_more'), ('quotes', '0004_quotation_user'), ('quotes', '0005_alter_quotationitem_variant_quoteproduct_and_more'), ('quotes', '0006_quotation_is_deleted_quotationitem_is_deleted_and_more'), ('quotes', '0007_additionalcost_quotationitem_unit_price_final_and_more'), ('quotes', '0008_remove_costassignment_cost_and_more'), ('quotes', '0009_quotation_rental_attachment_custom_fields'), ('quotes', '0010_quotequestion_quoterule_quotetemplate_and_more'), ('quotes', '0011_quoteruleaction_description_fragment_and_more'), ('quotes', '0012_quoteequipmenttype_quotetemplateequipment_and_more'), ('quotes', '0013_quotation_address_quotation_answers_quotation_city_and_more'), ('quotes', '0014_quotequestion_allow_other'), ('quotes', '0015_rename_equipment_to_module'), ('quotes', '0016_subcategory_and_question_fields'), ('quotes', '0017_remove_calc_engine_models'), ('quotes', '0018_quotation_status_rework'), ('quotes', '0019_quotationtimeline'), ('quotes', '0020_alter_quotation_template_and_more'), ('quotes', '0021_quotetemplateattribute_and_more'), ('quotes', '0022_remove_quotetemplate_service_type_and_more'), ('quotes', '0023_remove_quotationitem_quotes_quot_uuid_43c2db_idx_and_more'), ('quotes', '0024_alter_quotetemplate_is_active_and_more'), ('quotes', '0025_quotation_status_db_index'), ('quotes', '0026_quotequestion_depends_on_question_and_more'), ('quotes', '0027_seed_notify_quotations_periodic_task'), ('quotes', '0028_seed_installation_info_questions'), ('quotes', '0029_seed_labor_questions'), ('quotes', '0030_simplify_labor_questions'), ('quotes', '0031_attachment_filefield'), ('quotes', '0032_optimize_installation_flow'), ('quotes', '0033_add_is_internal_flag'), ('quotes', '0034_hide_qa_template_and_fix_camera_count'), ('quotes', '0035_add_quotation_idempotency_key')]

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('django_celery_beat', '0001_initial'),
        ('renting', '0008_multipayment'),
        ('shop', '0001_initial'),
        ('technical_services', '0001_initial'),
        ('technical_services', '0018_rename_tech_svc_booking_time_idx_technical_s_start_t_c17a0b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.EmailField(max_length=254)),
                ('valid_until', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=20)),
                ('subtotal_products', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('subtotal_services', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='Registered client (optional for anonymous quotes)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('service_name', models.CharField(max_length=255)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('labor_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='quotes.quotation')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='technical_services.technicalservice')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['uuid'], name='quotes_quot_uuid_688751_idx'), models.Index(fields=['-created_at'], name='quotes_quot_created_bd13af_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuotationMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('material_name', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quotation_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='quotes.quotationservice')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['uuid'], name='quotes_quot_uuid_8ce687_idx'), models.Index(fields=['-created_at'], name='quotes_quot_created_bbafd7_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuoteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['uuid'], name='quotes_quot_uuid_b69811_idx'), models.Index(fields=['-created_at'], name='quotes_quot_created_abba17_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuoteProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='quotes.quoteproduct')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotes.quotation')),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.productvariant')),
                ('quote_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.quoteproductvariant')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['uuid'], name='quotes_quot_uuid_43c2db_idx'), models.Index(fields=['-created_at'], name='quotes_quot_created_91148e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='quoteproductvariant',
            index=models.Index(fields=['uuid'], name='quotes_quot_uuid_2c1160_idx'),
        ),
        migrations.AddIndex(
            model_name='quoteproductvariant',
            index=models.Index(fields=['-created_at'], name='quotes_quot_created_63863a_idx'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='quotationmaterial',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='quotationservice',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='quoteproduct',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='quoteproductvariant',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='unit_price_final',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio unitario con costos adicionales aplicados (snapshot del motor de precios).', max_digits=12),
        ),
        migrations.CreateModel(
            name='QuotationItemCostSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('cost_name', models.CharField(max_length=150)),
                ('context', models.CharField(max_length=20)),
                ('cost_type', models.CharField(max_length=10)),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('computed_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_discount', models.BooleanField(default=False)),
                ('quotation_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_snapshots', to='quotes.quotationitem')),
            ],
            options={
                'verbose_name': 'Snapshot de Costo en Cotizacion',
                'verbose_name_plural': 'Snapshots de Costos en Cotizaciones',
            },
        ),
        migrations.AddField(
            model_name='quotation',
            name='is_custom',
            field=models.BooleanField(default=False, help_text='True when the quotation includes custom (non-catalog) services or materials.'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='subtotal_rentals',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='quotationservice',
            name='custom_service_type',
            field=models.CharField(blank=True, help_text='Type label for a custom service (e.g. "Instalacion", "Mantenimiento").', max_length=100),
        ),
        migrations.AddField(
            model_name='quotationservice',
            name='estimated_time_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated hours for custom service (may differ from billable hours).', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='quotationservice',
            name='labor_description',
            field=models.TextField(blank=True, help_text='Detailed description of the labor scope for custom services.'),
        ),
        migrations.AddField(
            model_name='quotationservice',
            name='requires_full_cost_installation',
            field=models.BooleanField(default=False, help_text='True when installation cost must be included in the total.'),
        ),
        migrations.AlterField(
            model_name='quotationservice',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='technical_services.technicalservice'),
        ),
        migrations.CreateModel(
            name='QuotationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('file', models.ImageField(upload_to='quotations/attachments/')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='quotes.quotation')),
            ],
            options={
                'verbose_name': 'Adjunto de Cotizacion',
                'verbose_name_plural': 'Adjuntos de Cotizaciones',
            },
        ),
        migrations.CreateModel(
            name='QuotationRentalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('equipment_name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('rental_price_per_day', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('rental_price_per_hour', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('rent_start_date', models.DateField()),
                ('rent_end_date', models.DateField()),
                ('computed_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_items', to='quotes.quotation')),
                ('variant', models.ForeignKey(blank=True, help_text='Source variant; nullable so the snapshot remains if the variant is deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='renting.equipmentvariant')),
            ],
            options={
                'verbose_name': 'Item de Alquiler en Cotizacion',
                'verbose_name_plural': 'Items de Alquiler en Cotizaciones',
            },
        ),
        migrations.CreateModel(
            name='QuoteQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('key', models.SlugField(help_text='Identificador usado por las reglas para referenciar esta pregunta (unico dentro de la plantilla).', max_length=100)),
                ('question_type', models.CharField(choices=[('TEXT', 'Texto'), ('NUMBER', 'Numero'), ('DECIMAL', 'Decimal'), ('BOOLEAN', 'Booleano'), ('DATE', 'Fecha'), ('TIME', 'Hora'), ('SELECT', 'Select'), ('MULTISELECT', 'Multiselect'), ('RADIO', 'Radio'), ('CHECKBOX', 'Checkbox'), ('IMAGE', 'Imagen'), ('FILE', 'Archivo'), ('GPS', 'GPS'), ('ADDRESS', 'Direccion')], default='TEXT', max_length=20)),
                ('label', models.CharField(max_length=500)),
                ('help_text', models.CharField(blank=True, default='', max_length=500)),
                ('placeholder', models.CharField(blank=True, default='', max_length=255)),
                ('is_required', models.BooleanField(default=False)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pregunta de Plantilla',
                'verbose_name_plural': 'Preguntas de Plantilla',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('condition_logic', models.CharField(choices=[('ALL', 'Todas las condiciones (AND)'), ('ANY', 'Cualquier condicion (OR)')], default='ALL', max_length=10)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Regla de Cotizacion',
                'verbose_name_plural': 'Reglas de Cotizacion',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuoteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('service_type', models.CharField(blank=True, default='', max_length=100)),
                ('installation_type', models.CharField(blank=True, default='', max_length=100)),
                ('system_type', models.CharField(blank=True, default='', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Cotizacion',
                'verbose_name_plural': 'Plantillas de Cotizacion',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuoteTemplateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', help_text="Clase de icono, ej. 'bi-camera-video'.", max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria de Plantilla de Cotizacion',
                'verbose_name_plural': 'Categorias de Plantillas de Cotizacion',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuoteQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('label', models.CharField(max_length=255)),
                ('value', models.CharField(help_text='Valor usado por las condiciones de reglas.', max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quotes.quotequestion')),
            ],
            options={
                'verbose_name': 'Opcion de Pregunta',
                'verbose_name_plural': 'Opciones de Pregunta',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRuleAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('action_type', models.CharField(choices=[('ADD_MATERIAL', 'Agregar material'), ('ADD_SERVICE', 'Agregar servicio'), ('ADD_EQUIPMENT', 'Agregar equipo'), ('ADD_TOOL', 'Agregar herramienta'), ('ADD_LABOR', 'Agregar mano de obra'), ('ADD_TRANSPORT', 'Agregar transporte/viaticos'), ('ADD_COST', 'Agregar costo'), ('ADD_TIME', 'Agregar tiempo'), ('SHOW_QUESTION', 'Mostrar pregunta'), ('HIDE_QUESTION', 'Ocultar pregunta'), ('SET_REQUIRED', 'Marcar obligatoria'), ('SET_OPTIONAL', 'Marcar no obligatoria')], max_length=20)),
                ('item_name', models.CharField(blank=True, default='', help_text='Nombre del item a agregar (acciones ADD_*).', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='quotes.quoterule')),
                ('target_question', models.ForeignKey(blank=True, help_text='Solo para acciones sobre preguntas (mostrar/ocultar/obligatoria).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rule_actions', to='quotes.quotequestion')),
            ],
            options={
                'verbose_name': 'Accion de Regla',
                'verbose_name_plural': 'Acciones de Regla',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRuleCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('operator', models.CharField(choices=[('EQUALS', 'Igual a'), ('NOT_EQUALS', 'Distinto de'), ('GREATER_THAN', 'Mayor que'), ('GREATER_THAN_OR_EQUAL', 'Mayor o igual que'), ('LESS_THAN', 'Menor que'), ('LESS_THAN_OR_EQUAL', 'Menor o igual que'), ('CONTAINS', 'Contiene'), ('IN', 'Esta en')], default='EQUALS', max_length=25)),
                ('value', models.CharField(help_text='Valor de comparacion en texto; se interpreta segun el tipo de la pregunta al evaluar la regla.', max_length=500)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_conditions', to='quotes.quotequestion')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='quotes.quoterule')),
            ],
            options={
                'verbose_name': 'Condicion de Regla',
                'verbose_name_plural': 'Condiciones de Regla',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='quoterule',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='quotes.quotetemplate'),
        ),
        migrations.AddField(
            model_name='quotetemplate',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='quotes.quotetemplatecategory'),
        ),
        migrations.CreateModel(
            name='QuoteTemplateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='quotes.quotetemplate')),
            ],
            options={
                'verbose_name': 'Seccion de Plantilla',
                'verbose_name_plural': 'Secciones de Plantilla',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='quotequestion',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quotes.quotetemplatesection'),
        ),
        migrations.AddConstraint(
            model_name='quotequestion',
            constraint=models.UniqueConstraint(fields=('section', 'key'), name='unique_question_key_per_section'),
        ),
        migrations.AddField(
            model_name='quoteruleaction',
            name='description_fragment',
            field=models.TextField(blank=True, default='', help_text='Fragmento de texto que se concatena en la descripcion tecnica generada cuando esta accion se dispara.'),
        ),
        migrations.AddField(
            model_name='quoteruleaction',
            name='install_hours_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Horas de instalacion por unidad de este material/equipo/herramienta (asociadas por el administrador).', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='quoteruleaction',
            name='quantity_source_question',
            field=models.ForeignKey(blank=True, help_text='Si esta seteado, la cantidad real se toma de la respuesta a esta pregunta (en vez del campo quantity fijo).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quantity_driven_actions', to='quotes.quotequestion'),
        ),
        migrations.CreateModel(
            name='QuoteEquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Equipo',
                'verbose_name_plural': 'Tipos de Equipo',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuoteTemplateEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('unit', models.CharField(blank=True, default='unidad', max_length=50)),
                ('min_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('max_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Equipo de Plantilla',
                'verbose_name_plural': 'Equipos de Plantilla',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuoteTemplateMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('base_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('is_calculated', models.BooleanField(default=False, help_text='Informativo: True si la cantidad depende de quantity_source_question.')),
                ('is_visible', models.BooleanField(default=True, help_text='Se muestra en el resumen de la cotizacion.')),
                ('is_editable_by_client', models.BooleanField(default=False, help_text='El cliente puede modificar la cantidad.')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Material de Plantilla',
                'verbose_name_plural': 'Materiales de Plantilla',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='quotequestion',
            name='unique_question_key_per_section',
        ),
        migrations.RemoveField(
            model_name='quotetemplatesection',
            name='template',
        ),
        migrations.RemoveField(
            model_name='quotequestion',
            name='section',
        ),
        migrations.AddField(
            model_name='quotetemplateequipment',
            name='equipment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_items', to='quotes.quoteequipmenttype'),
        ),
        migrations.AddField(
            model_name='quotetemplateequipment',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_items', to='quotes.quotetemplate'),
        ),
        migrations.AddField(
            model_name='quotequestion',
            name='equipment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quotes.quotetemplateequipment'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='quotequestion',
            constraint=models.UniqueConstraint(fields=('equipment', 'key'), name='unique_question_key_per_equipment'),
        ),
        migrations.AddField(
            model_name='quotetemplatematerial',
            name='quantity_source_question',
            field=models.ForeignKey(blank=True, help_text='Si esta seteado, la cantidad real se toma de la respuesta a esta pregunta (en vez de base_quantity).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quantity_driven_materials', to='quotes.quotequestion'),
        ),
        migrations.AddField(
            model_name='quotetemplatematerial',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='quotes.quotetemplate'),
        ),
        migrations.DeleteModel(
            name='QuoteTemplateSection',
        ),
        migrations.AddField(
            model_name='quotation',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='answers',
            field=models.JSONField(blank=True, default=dict, help_text='Respuestas del cliente, keyed por question.key.'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='company',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='document_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='quotation',
            name='document_type',
            field=models.CharField(blank=True, choices=[('NIT', 'NIT'), ('CC', 'CC')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='generated_summary',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot del resultado de LaborCalculationEngine.generate_preview() al momento de crear la cotizacion.'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='gps_location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='quotation',
            name='project_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Plantilla usada para generar esta cotizacion (motor CPQ). Null para el flujo catalogo/personalizado legacy.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='quotes.quotetemplate'),
        ),
        migrations.AddField(
            model_name='quotequestion',
            name='allow_other',
            field=models.BooleanField(default=False, help_text="Para SELECT/RADIO: agrega la opcion 'Otro' que permite al cliente escribir un valor libre."),
        ),
        migrations.RemoveConstraint(
            model_name='quotequestion',
            name='unique_question_key_per_equipment',
        ),
        migrations.RenameModel(
            old_name='QuoteTemplateEquipment',
            new_name='QuoteTemplateModule',
        ),
        migrations.RenameField(
            model_name='quotequestion',
            old_name='equipment',
            new_name='module',
        ),
        migrations.AlterField(
            model_name='quotequestion',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quotes.quotetemplatemodule'),
        ),
        migrations.AddConstraint(
            model_name='quotequestion',
            constraint=models.UniqueConstraint(fields=('module', 'key'), name='unique_question_key_per_module'),
        ),
        migrations.AddField(
            model_name='quotetemplatemodule',
            name='module_type',
            field=models.CharField(choices=[('EQUIPMENT', 'Equipos'), ('MATERIALS', 'Materiales'), ('LABOR', 'Mano de Obra')], default='EQUIPMENT', max_length=20),
        ),
        migrations.AlterModelOptions(
            name='quotetemplatemodule',
            options={'ordering': ['module_type', 'display_order', 'id'], 'verbose_name': 'Modulo de Plantilla', 'verbose_name_plural': 'Modulos de Plantilla'},
        ),
        migrations.AlterField(
            model_name='quotequestion',
            name='key',
            field=models.SlugField(help_text='Identificador unico de la pregunta dentro de su modulo.', max_length=100),
        ),
        migrations.CreateModel(
            name='QuoteTemplateSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='quotes.quotetemplatecategory')),
            ],
            options={
                'verbose_name': 'Subcategoria de Plantilla de Cotizacion',
                'verbose_name_plural': 'Subcategorias de Plantillas de Cotizacion',
                'ordering': ['display_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('category', 'slug'), name='unique_subcategory_slug_per_category')],
            },
        ),
        migrations.AddField(
            model_name='quotetemplate',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='quotes.quotetemplatesubcategory'),
        ),
        migrations.AddField(
            model_name='quotetemplate',
            name='code',
            field=models.CharField(blank=True, help_text='Codigo corto interno, ej. CCTV-INST-001.', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='quotetemplate',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quotetemplate',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Visible en /cotizar. Una plantilla no publicada solo se ve en el panel admin.'),
        ),
        migrations.AddField(
            model_name='quotequestion',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Explicacion larga de la pregunta (distinta del texto de ayuda corto).'),
        ),
        migrations.AddField(
            model_name='quotequestion',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Se muestra al cliente en /cotizar. Desactivar para ocultarla sin borrarla.'),
        ),
        migrations.AddField(
            model_name='quotequestion',
            name='default_value',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='quotequestion',
            name='unit',
            field=models.CharField(blank=True, default='', help_text="Unidad de medida, ej. 'metros', 'm2'.", max_length=50),
        ),
        migrations.AddField(
            model_name='quotequestion',
            name='group',
            field=models.CharField(blank=True, default='', help_text='Etiqueta de agrupacion visual dentro del modulo.', max_length=150),
        ),
        migrations.AddField(
            model_name='quotequestion',
            name='validation_regex',
            field=models.CharField(blank=True, default='', help_text='Patron opcional de validacion (ej. para NIT/CC/Email).', max_length=255),
        ),
        migrations.AddField(
            model_name='quotequestion',
            name='table_columns',
            field=models.JSONField(blank=True, default=list, help_text="Solo para TABLE: lista de nombres de columna, ej. ['Item', 'Cantidad']."),
        ),
        migrations.AlterField(
            model_name='quotequestion',
            name='question_type',
            field=models.CharField(choices=[('TEXT', 'Texto'), ('TEXTAREA', 'Texto largo'), ('NUMBER', 'Numero'), ('DECIMAL', 'Decimal'), ('CURRENCY', 'Moneda'), ('BOOLEAN', 'Booleano'), ('DATE', 'Fecha'), ('TIME', 'Hora'), ('SELECT', 'Select'), ('MULTISELECT', 'Multiselect'), ('RADIO', 'Radio'), ('CHECKBOX', 'Checkbox'), ('IMAGE', 'Imagen'), ('FILE', 'Archivo'), ('SIGNATURE', 'Firma'), ('GPS', 'GPS'), ('ADDRESS', 'Direccion'), ('EMAIL', 'Email'), ('PHONE', 'Telefono'), ('NIT', 'NIT'), ('CC', 'Cedula (CC)'), ('COLOR', 'Color'), ('SLIDER', 'Deslizador'), ('TABLE', 'Tabla'), ('DYNAMIC_LIST', 'Lista dinamica'), ('AUTOCOMPLETE', 'Autocompletar')], default='TEXT', max_length=20),
        ),
        migrations.DeleteModel(
            name='QuoteRuleAction',
        ),
        migrations.DeleteModel(
            name='QuoteRuleCondition',
        ),
        migrations.DeleteModel(
            name='QuoteRule',
        ),
        migrations.DeleteModel(
            name='QuoteTemplateMaterial',
        ),
        migrations.RunPython(
            code=remap_status_forward_0018,
            reverse_code=remap_status_backward_0018,
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('RECIBIDA', 'Recibida'), ('EN_REVISION', 'En revision'), ('PENDIENTE_INFORMACION', 'Pendiente informacion'), ('COTIZADA', 'Cotizada'), ('ENVIADA', 'Enviada'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=25),
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='generated_summary',
        ),
        migrations.AlterField(
            model_name='quotation',
            name='answers',
            field=models.JSONField(blank=True, default=dict, help_text='Respuestas del cliente organizadas por modulo: {"<module_uuid>": {"<question_key>": valor}}.'),
        ),
        migrations.AddField(
            model_name='quotationattachment',
            name='note',
            field=models.CharField(blank=True, default='', help_text="Contexto del adjunto, ej. 'module_uuid:question_key' para respuestas de preguntas tipo archivo.", max_length=255),
        ),
        migrations.CreateModel(
            name='QuotationTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('BORRADOR', 'Borrador'), ('RECIBIDA', 'Recibida'), ('EN_REVISION', 'En revision'), ('PENDIENTE_INFORMACION', 'Pendiente informacion'), ('COTIZADA', 'Cotizada'), ('ENVIADA', 'Enviada'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada')], max_length=25)),
                ('notes', models.TextField(blank=True, default='')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_status_changes', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='quotes.quotation')),
            ],
            options={
                'verbose_name': 'Evento de Cotizacion',
                'verbose_name_plural': 'Historial de Cotizacion',
                'ordering': ['created_at'],
            },
        ),
        migrations.RunPython(
            code=backfill_timeline_0019,
            reverse_code=noop_backward_0019,
        ),
        migrations.AlterField(
            model_name='quotation',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Plantilla usada para capturar el requerimiento. Null para el flujo catalogo/personalizado legacy.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='quotes.quotetemplate'),
        ),
        migrations.AlterField(
            model_name='quotequestionoption',
            name='value',
            field=models.CharField(help_text='Valor almacenado en la respuesta.', max_length=255),
        ),
        migrations.AlterField(
            model_name='quotetemplatemodule',
            name='equipment_type',
            field=models.ForeignKey(blank=True, help_text='Solo aplica cuando module_type=EQUIPMENT.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_items', to='quotes.quoteequipmenttype'),
        ),
        migrations.AlterField(
            model_name='quotetemplatemodule',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='quotes.quotetemplate'),
        ),
        migrations.CreateModel(
            name='QuoteTemplateAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('kind', models.CharField(choices=[('SERVICE_TYPE', 'Tipo de Servicio'), ('INSTALLATION_TYPE', 'Tipo de Instalacion'), ('SYSTEM_TYPE', 'Tipo de Sistema')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Atributo de Plantilla',
                'verbose_name_plural': 'Atributos de Plantilla',
                'ordering': ['kind', 'display_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'slug'), name='unique_attribute_slug_per_kind')],
            },
        ),
        migrations.RemoveField(
            model_name='quotetemplate',
            name='installation_type',
        ),
        migrations.RemoveField(
            model_name='quotetemplate',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='quotetemplate',
            name='system_type',
        ),
        migrations.AddField(
            model_name='quotetemplate',
            name='installation_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'INSTALLATION_TYPE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='quotes.quotetemplateattribute'),
        ),
        migrations.AddField(
            model_name='quotetemplate',
            name='service_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'SERVICE_TYPE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='quotes.quotetemplateattribute'),
        ),
        migrations.AddField(
            model_name='quotetemplate',
            name='system_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'SYSTEM_TYPE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='quotes.quotetemplateattribute'),
        ),
        migrations.RunPython(
            code=seed_service_types_0021,
            reverse_code=noop_backward_0021,
        ),
        migrations.RemoveField(
            model_name='quotetemplate',
            name='service_type',
        ),
        migrations.AddField(
            model_name='quotetemplateattribute',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Solo aplica cuando kind=INSTALLATION_TYPE: subcategoria dueña de esta opcion.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installation_types', to='quotes.quotetemplatesubcategory'),
        ),
        migrations.AddField(
            model_name='quotetemplatecategory',
            name='service_type',
            field=models.ForeignKey(blank=True, help_text='Tipo de Servicio al que pertenece esta categoria.', limit_choices_to={'kind': 'SERVICE_TYPE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='quotes.quotetemplateattribute'),
        ),
        migrations.RemoveIndex(
            model_name='quotationitem',
            name='quotes_quot_uuid_43c2db_idx',
        ),
        migrations.RemoveIndex(
            model_name='quotationitem',
            name='quotes_quot_created_91148e_idx',
        ),
        migrations.RemoveIndex(
            model_name='quotationmaterial',
            name='quotes_quot_uuid_8ce687_idx',
        ),
        migrations.RemoveIndex(
            model_name='quotationmaterial',
            name='quotes_quot_created_bbafd7_idx',
        ),
        migrations.RemoveIndex(
            model_name='quotationservice',
            name='quotes_quot_uuid_688751_idx',
        ),
        migrations.RemoveIndex(
            model_name='quotationservice',
            name='quotes_quot_created_bd13af_idx',
        ),
        migrations.RemoveIndex(
            model_name='quoteproduct',
            name='quotes_quot_uuid_b69811_idx',
        ),
        migrations.RemoveIndex(
            model_name='quoteproduct',
            name='quotes_quot_created_abba17_idx',
        ),
        migrations.RemoveIndex(
            model_name='quoteproductvariant',
            name='quotes_quot_uuid_2c1160_idx',
        ),
        migrations.RemoveIndex(
            model_name='quoteproductvariant',
            name='quotes_quot_created_63863a_idx',
        ),
        migrations.AlterField(
            model_name='quotetemplate',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='quotetemplate',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, help_text='Visible en /cotizar. Una plantilla no publicada solo se ve en el panel admin.'),
        ),
        migrations.AlterField(
            model_name='quotetemplatecategory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('RECIBIDA', 'Recibida'), ('EN_REVISION', 'En revision'), ('PENDIENTE_INFORMACION', 'Pendiente informacion'), ('COTIZADA', 'Cotizada'), ('ENVIADA', 'Enviada'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada')], db_index=True, default='BORRADOR', max_length=25),
        ),
        migrations.AddField(
            model_name='quotequestion',
            name='depends_on_question',
            field=models.ForeignKey(blank=True, help_text='Pregunta cuya respuesta controla la visibilidad de esta (debe ser del mismo modulo).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependents', to='quotes.quotequestion'),
        ),
        migrations.AddField(
            model_name='quotequestion',
            name='depends_on_values',
            field=models.JSONField(blank=True, default=list, help_text='Lista de valores de depends_on_question que activan la visibilidad de esta pregunta.'),
        ),
        migrations.AddField(
            model_name='quotetemplate',
            name='complexity_hint',
            field=models.CharField(blank=True, choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta')], default='', max_length=10),
        ),
        migrations.RunPython(
            code=create_periodic_task_0027,
            reverse_code=remove_periodic_task_0027,
        ),
        migrations.RunPython(
            code=seed_questions_0028,
            reverse_code=remove_questions_0028,
        ),
        migrations.RunPython(
            code=seed_questions_0029,
            reverse_code=remove_questions_0029,
        ),
        migrations.RunPython(
            code=simplify_questions_0030,
            reverse_code=restore_questions_0030,
        ),
        migrations.AlterField(
            model_name='quotationattachment',
            name='file',
            field=models.FileField(upload_to='quotations/attachments/'),
        ),
        migrations.RunPython(
            code=optimize_flow_0032,
            reverse_code=revert_flow_0032,
        ),
        migrations.AddField(
            model_name='quotetemplate',
            name='is_internal',
            field=models.BooleanField(db_index=True, default=False, help_text='Plantilla reservada para pruebas internas de QA. Nunca aparece en /cotizar ni es seleccionable por un cliente, sin importar el valor de is_published -- defensa adicional para que una plantilla de pruebas no vuelva a filtrarse a produccion por error (ver hallazgo H5, auditoria E2E 2026-07-23).'),
        ),
        migrations.RunPython(
            code=hide_qa_and_fix_camera_count_0034,
            reverse_code=reverse_0034,
        ),
        migrations.AddField(
            model_name='quotation',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, help_text='UUID generado por el wizard antes del primer intento de envio (header X-Idempotency-Key). Un reintento con la misma llave -- doble clic, F5, reconexion -- devuelve la Quotation ya creada en vez de duplicarla (defensa en profundidad detras del guard sincrono del frontend, ver H1, auditoria E2E 2026-07-23).', max_length=100, null=True, unique=True),
        ),
    ]
