# Generated by Django 6.0.4 on 2026-04-14 16:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationservice',
            name='material_cost',
        ),
        migrations.CreateModel(
            name='QuotationMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('material_name', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quotation_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='quotes.quotationservice')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['uuid'], name='quotes_quot_uuid_8ce687_idx'), models.Index(fields=['-created_at'], name='quotes_quot_created_bbafd7_idx')],
            },
        ),
    ]
