# Generated by Django 6.0.4 on 2026-04-14 19:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_quotation_user'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.productvariant'),
        ),
        migrations.CreateModel(
            name='QuoteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['uuid'], name='quotes_quot_uuid_b69811_idx'), models.Index(fields=['-created_at'], name='quotes_quot_created_abba17_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuoteProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='quotes.quoteproduct')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='quote_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.quoteproductvariant'),
        ),
        migrations.AddIndex(
            model_name='quoteproductvariant',
            index=models.Index(fields=['uuid'], name='quotes_quot_uuid_2c1160_idx'),
        ),
        migrations.AddIndex(
            model_name='quoteproductvariant',
            index=models.Index(fields=['-created_at'], name='quotes_quot_created_63863a_idx'),
        ),
    ]
