# Generated by Django 5.2.13 on 2026-06-22 15:11

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('quotes', '0006_quotation_is_deleted_quotationitem_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('cost_type', models.CharField(choices=[('FIXED', 'Valor fijo (COP)'), ('PERCENTAGE', 'Porcentaje (%)')], db_index=True, max_length=10)),
                ('context', models.CharField(choices=[('TAX', 'Impuesto'), ('TRANSPORT', 'Transporte'), ('DISCOUNT', 'Descuento'), ('LOGISTICS', 'Logistica'), ('OPERATIONAL', 'Operativo'), ('SETUP', 'Configuracion / Instalacion')], db_index=True, max_length=20)),
                ('value', models.DecimalField(decimal_places=4, help_text='Porcentaje (0-100) si PERCENTAGE. Monto fijo COP si FIXED.', max_digits=12)),
                ('applies_globally', models.BooleanField(db_index=True, default=False, help_text='Si True, se aplica a TODOS los items sin necesidad de CostAssignment.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Costo Adicional',
                'verbose_name_plural': 'Costos Adicionales',
                'ordering': ['context', 'name'],
            },
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='unit_price_final',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio unitario con costos adicionales aplicados (snapshot del motor de precios).', max_digits=12),
        ),
        migrations.CreateModel(
            name='QuotationItemCostSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('cost_name', models.CharField(max_length=150)),
                ('context', models.CharField(max_length=20)),
                ('cost_type', models.CharField(max_length=10)),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('computed_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_discount', models.BooleanField(default=False)),
                ('quotation_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_snapshots', to='quotes.quotationitem')),
            ],
            options={
                'verbose_name': 'Snapshot de Costo en Cotizacion',
                'verbose_name_plural': 'Snapshots de Costos en Cotizaciones',
            },
        ),
        migrations.CreateModel(
            name='CostAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('object_id', models.UUIDField(db_index=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='quotes.additionalcost')),
            ],
            options={
                'verbose_name': 'Asignacion de Costo',
                'verbose_name_plural': 'Asignaciones de Costos',
                'unique_together': {('cost', 'content_type', 'object_id')},
            },
        ),
    ]
