# Generated by Django 5.2.13 on 2026-06-22 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_additionalcost_quotationitem_unit_price_final_and_more'),
    ]

    operations = [
        # Must clear unique_together BEFORE removing the fields it references
        migrations.AlterUniqueTogether(
            name='costassignment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='costassignment',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='costassignment',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='CostAssignment',
        ),
        migrations.DeleteModel(
            name='AdditionalCost',
        ),
    ]
