# Generated by Django 5.2.13 on 2026-06-26 16:52

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_remove_costassignment_cost_and_more'),
        ('renting', '0008_multipayment'),
        ('technical_services', '0018_rename_tech_svc_booking_time_idx_technical_s_start_t_c17a0b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='is_custom',
            field=models.BooleanField(default=False, help_text='True when the quotation includes custom (non-catalog) services or materials.'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='subtotal_rentals',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='quotationservice',
            name='custom_service_type',
            field=models.CharField(blank=True, help_text='Type label for a custom service (e.g. "Instalacion", "Mantenimiento").', max_length=100),
        ),
        migrations.AddField(
            model_name='quotationservice',
            name='estimated_time_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated hours for custom service (may differ from billable hours).', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='quotationservice',
            name='labor_description',
            field=models.TextField(blank=True, help_text='Detailed description of the labor scope for custom services.'),
        ),
        migrations.AddField(
            model_name='quotationservice',
            name='requires_full_cost_installation',
            field=models.BooleanField(default=False, help_text='True when installation cost must be included in the total.'),
        ),
        migrations.AlterField(
            model_name='quotationservice',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='technical_services.technicalservice'),
        ),
        migrations.CreateModel(
            name='QuotationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('file', models.ImageField(upload_to='quotations/attachments/')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='quotes.quotation')),
            ],
            options={
                'verbose_name': 'Adjunto de Cotizacion',
                'verbose_name_plural': 'Adjuntos de Cotizaciones',
            },
        ),
        migrations.CreateModel(
            name='QuotationRentalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('equipment_name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('rental_price_per_day', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('rental_price_per_hour', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('rent_start_date', models.DateField()),
                ('rent_end_date', models.DateField()),
                ('computed_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_items', to='quotes.quotation')),
                ('variant', models.ForeignKey(blank=True, help_text='Source variant; nullable so the snapshot remains if the variant is deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='renting.equipmentvariant')),
            ],
            options={
                'verbose_name': 'Item de Alquiler en Cotizacion',
                'verbose_name_plural': 'Items de Alquiler en Cotizaciones',
            },
        ),
    ]
