# Generated by Django 5.2.13 on 2026-07-02 14:41

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0009_quotation_rental_attachment_custom_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('key', models.SlugField(help_text='Identificador usado por las reglas para referenciar esta pregunta (unico dentro de la plantilla).', max_length=100)),
                ('question_type', models.CharField(choices=[('TEXT', 'Texto'), ('NUMBER', 'Numero'), ('DECIMAL', 'Decimal'), ('BOOLEAN', 'Booleano'), ('DATE', 'Fecha'), ('TIME', 'Hora'), ('SELECT', 'Select'), ('MULTISELECT', 'Multiselect'), ('RADIO', 'Radio'), ('CHECKBOX', 'Checkbox'), ('IMAGE', 'Imagen'), ('FILE', 'Archivo'), ('GPS', 'GPS'), ('ADDRESS', 'Direccion')], default='TEXT', max_length=20)),
                ('label', models.CharField(max_length=500)),
                ('help_text', models.CharField(blank=True, default='', max_length=500)),
                ('placeholder', models.CharField(blank=True, default='', max_length=255)),
                ('is_required', models.BooleanField(default=False)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pregunta de Plantilla',
                'verbose_name_plural': 'Preguntas de Plantilla',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('condition_logic', models.CharField(choices=[('ALL', 'Todas las condiciones (AND)'), ('ANY', 'Cualquier condicion (OR)')], default='ALL', max_length=10)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Regla de Cotizacion',
                'verbose_name_plural': 'Reglas de Cotizacion',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuoteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('service_type', models.CharField(blank=True, default='', max_length=100)),
                ('installation_type', models.CharField(blank=True, default='', max_length=100)),
                ('system_type', models.CharField(blank=True, default='', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Cotizacion',
                'verbose_name_plural': 'Plantillas de Cotizacion',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuoteTemplateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', help_text="Clase de icono, ej. 'bi-camera-video'.", max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria de Plantilla de Cotizacion',
                'verbose_name_plural': 'Categorias de Plantillas de Cotizacion',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuoteQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('label', models.CharField(max_length=255)),
                ('value', models.CharField(help_text='Valor usado por las condiciones de reglas.', max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quotes.quotequestion')),
            ],
            options={
                'verbose_name': 'Opcion de Pregunta',
                'verbose_name_plural': 'Opciones de Pregunta',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRuleAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('action_type', models.CharField(choices=[('ADD_MATERIAL', 'Agregar material'), ('ADD_SERVICE', 'Agregar servicio'), ('ADD_EQUIPMENT', 'Agregar equipo'), ('ADD_TOOL', 'Agregar herramienta'), ('ADD_LABOR', 'Agregar mano de obra'), ('ADD_TRANSPORT', 'Agregar transporte/viaticos'), ('ADD_COST', 'Agregar costo'), ('ADD_TIME', 'Agregar tiempo'), ('SHOW_QUESTION', 'Mostrar pregunta'), ('HIDE_QUESTION', 'Ocultar pregunta'), ('SET_REQUIRED', 'Marcar obligatoria'), ('SET_OPTIONAL', 'Marcar no obligatoria')], max_length=20)),
                ('item_name', models.CharField(blank=True, default='', help_text='Nombre del item a agregar (acciones ADD_*).', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='quotes.quoterule')),
                ('target_question', models.ForeignKey(blank=True, help_text='Solo para acciones sobre preguntas (mostrar/ocultar/obligatoria).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rule_actions', to='quotes.quotequestion')),
            ],
            options={
                'verbose_name': 'Accion de Regla',
                'verbose_name_plural': 'Acciones de Regla',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRuleCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('operator', models.CharField(choices=[('EQUALS', 'Igual a'), ('NOT_EQUALS', 'Distinto de'), ('GREATER_THAN', 'Mayor que'), ('GREATER_THAN_OR_EQUAL', 'Mayor o igual que'), ('LESS_THAN', 'Menor que'), ('LESS_THAN_OR_EQUAL', 'Menor o igual que'), ('CONTAINS', 'Contiene'), ('IN', 'Esta en')], default='EQUALS', max_length=25)),
                ('value', models.CharField(help_text='Valor de comparacion en texto; se interpreta segun el tipo de la pregunta al evaluar la regla.', max_length=500)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_conditions', to='quotes.quotequestion')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='quotes.quoterule')),
            ],
            options={
                'verbose_name': 'Condicion de Regla',
                'verbose_name_plural': 'Condiciones de Regla',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='quoterule',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='quotes.quotetemplate'),
        ),
        migrations.AddField(
            model_name='quotetemplate',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='quotes.quotetemplatecategory'),
        ),
        migrations.CreateModel(
            name='QuoteTemplateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='quotes.quotetemplate')),
            ],
            options={
                'verbose_name': 'Seccion de Plantilla',
                'verbose_name_plural': 'Secciones de Plantilla',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='quotequestion',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quotes.quotetemplatesection'),
        ),
        migrations.AddConstraint(
            model_name='quotequestion',
            constraint=models.UniqueConstraint(fields=('section', 'key'), name='unique_question_key_per_section'),
        ),
    ]
