# Generated by Django 5.2.13 on 2026-07-02 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0010_quotequestion_quoterule_quotetemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteruleaction',
            name='description_fragment',
            field=models.TextField(blank=True, default='', help_text='Fragmento de texto que se concatena en la descripcion tecnica generada cuando esta accion se dispara.'),
        ),
        migrations.AddField(
            model_name='quoteruleaction',
            name='install_hours_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Horas de instalacion por unidad de este material/equipo/herramienta (asociadas por el administrador).', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='quoteruleaction',
            name='quantity_source_question',
            field=models.ForeignKey(blank=True, help_text='Si esta seteado, la cantidad real se toma de la respuesta a esta pregunta (en vez del campo quantity fijo).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quantity_driven_actions', to='quotes.quotequestion'),
        ),
    ]
