# Generated by Django 5.2.13 on 2026-07-02 16:04

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0011_quoteruleaction_description_fragment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteEquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Equipo',
                'verbose_name_plural': 'Tipos de Equipo',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuoteTemplateEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('unit', models.CharField(blank=True, default='unidad', max_length=50)),
                ('min_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('max_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Equipo de Plantilla',
                'verbose_name_plural': 'Equipos de Plantilla',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuoteTemplateMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('base_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('is_calculated', models.BooleanField(default=False, help_text='Informativo: True si la cantidad depende de quantity_source_question.')),
                ('is_visible', models.BooleanField(default=True, help_text='Se muestra en el resumen de la cotizacion.')),
                ('is_editable_by_client', models.BooleanField(default=False, help_text='El cliente puede modificar la cantidad.')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Material de Plantilla',
                'verbose_name_plural': 'Materiales de Plantilla',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='quotequestion',
            name='unique_question_key_per_section',
        ),
        migrations.RemoveField(
            model_name='quotetemplatesection',
            name='template',
        ),
        migrations.RemoveField(
            model_name='quotequestion',
            name='section',
        ),
        migrations.AddField(
            model_name='quotetemplateequipment',
            name='equipment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_items', to='quotes.quoteequipmenttype'),
        ),
        migrations.AddField(
            model_name='quotetemplateequipment',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_items', to='quotes.quotetemplate'),
        ),
        migrations.AddField(
            model_name='quotequestion',
            name='equipment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quotes.quotetemplateequipment'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='quotequestion',
            constraint=models.UniqueConstraint(fields=('equipment', 'key'), name='unique_question_key_per_equipment'),
        ),
        migrations.AddField(
            model_name='quotetemplatematerial',
            name='quantity_source_question',
            field=models.ForeignKey(blank=True, help_text='Si esta seteado, la cantidad real se toma de la respuesta a esta pregunta (en vez de base_quantity).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quantity_driven_materials', to='quotes.quotequestion'),
        ),
        migrations.AddField(
            model_name='quotetemplatematerial',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='quotes.quotetemplate'),
        ),
        migrations.DeleteModel(
            name='QuoteTemplateSection',
        ),
    ]
