# Generated by Django 5.2.13 on 2026-07-02 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0012_quoteequipmenttype_quotetemplateequipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='answers',
            field=models.JSONField(blank=True, default=dict, help_text='Respuestas del cliente, keyed por question.key.'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='company',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='document_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='quotation',
            name='document_type',
            field=models.CharField(blank=True, choices=[('NIT', 'NIT'), ('CC', 'CC')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='generated_summary',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot del resultado de LaborCalculationEngine.generate_preview() al momento de crear la cotizacion.'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='gps_location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='quotation',
            name='project_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Plantilla usada para generar esta cotizacion (motor CPQ). Null para el flujo catalogo/personalizado legacy.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='quotes.quotetemplate'),
        ),
    ]
