# Generated by Django 5.2.13 on 2026-07-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0013_quotation_address_quotation_answers_quotation_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotequestion',
            name='allow_other',
            field=models.BooleanField(default=False, help_text="Para SELECT/RADIO: agrega la opcion 'Otro' que permite al cliente escribir un valor libre."),
        ),
    ]
