# Generated by Django 5.2.13 on 2026-07-02 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0019_quotationtimeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Plantilla usada para capturar el requerimiento. Null para el flujo catalogo/personalizado legacy.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='quotes.quotetemplate'),
        ),
        migrations.AlterField(
            model_name='quotequestionoption',
            name='value',
            field=models.CharField(help_text='Valor almacenado en la respuesta.', max_length=255),
        ),
        migrations.AlterField(
            model_name='quotetemplatemodule',
            name='equipment_type',
            field=models.ForeignKey(blank=True, help_text='Solo aplica cuando module_type=EQUIPMENT.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_items', to='quotes.quoteequipmenttype'),
        ),
        migrations.AlterField(
            model_name='quotetemplatemodule',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='quotes.quotetemplate'),
        ),
    ]
