# Generated by Django 5.2.13 on 2026-07-02 18:53

import django.db.models.deletion
import uuid
from django.db import migrations, models
from django.utils.text import slugify


def seed_service_types(apps, schema_editor):
    QuoteTemplateAttribute = apps.get_model('quotes', 'QuoteTemplateAttribute')
    for i, name in enumerate(['Nueva instalacion', 'Mantenimiento', 'Servicio tecnico']):
        QuoteTemplateAttribute.objects.get_or_create(
            kind='SERVICE_TYPE', slug=slugify(name),
            defaults={'name': name, 'display_order': i},
        )


def noop_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0020_alter_quotation_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteTemplateAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('kind', models.CharField(choices=[('SERVICE_TYPE', 'Tipo de Servicio'), ('INSTALLATION_TYPE', 'Tipo de Instalacion'), ('SYSTEM_TYPE', 'Tipo de Sistema')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Atributo de Plantilla',
                'verbose_name_plural': 'Atributos de Plantilla',
                'ordering': ['kind', 'display_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'slug'), name='unique_attribute_slug_per_kind')],
            },
        ),
        # CharField -> ForeignKey no es un cast seguro en Postgres (no se puede
        # convertir 'Instalacion' a un id numerico). Se elimina la columna de
        # texto y se agrega la FK nueva en su lugar; son valores de prueba de
        # esta sesion, sin datos reales en juego (mismo criterio ya aplicado
        # al resto del refactor de quotes).
        migrations.RemoveField(model_name='quotetemplate', name='installation_type'),
        migrations.RemoveField(model_name='quotetemplate', name='service_type'),
        migrations.RemoveField(model_name='quotetemplate', name='system_type'),
        migrations.AddField(
            model_name='quotetemplate',
            name='installation_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'INSTALLATION_TYPE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='quotes.quotetemplateattribute'),
        ),
        migrations.AddField(
            model_name='quotetemplate',
            name='service_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'SERVICE_TYPE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='quotes.quotetemplateattribute'),
        ),
        migrations.AddField(
            model_name='quotetemplate',
            name='system_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'SYSTEM_TYPE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='quotes.quotetemplateattribute'),
        ),
        migrations.RunPython(seed_service_types, noop_backward),
    ]
