# Generated by Django 5.2.13 on 2026-07-02 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0021_quotetemplateattribute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotetemplate',
            name='service_type',
        ),
        migrations.AddField(
            model_name='quotetemplateattribute',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Solo aplica cuando kind=INSTALLATION_TYPE: subcategoria dueña de esta opcion.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installation_types', to='quotes.quotetemplatesubcategory'),
        ),
        migrations.AddField(
            model_name='quotetemplatecategory',
            name='service_type',
            field=models.ForeignKey(blank=True, help_text='Tipo de Servicio al que pertenece esta categoria.', limit_choices_to={'kind': 'SERVICE_TYPE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='quotes.quotetemplateattribute'),
        ),
    ]
