# Generated by Django 5.2.13 on 2026-07-03 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0022_remove_quotetemplate_service_type_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='quotationitem',
            name='quotes_quot_uuid_43c2db_idx',
        ),
        migrations.RemoveIndex(
            model_name='quotationitem',
            name='quotes_quot_created_91148e_idx',
        ),
        migrations.RemoveIndex(
            model_name='quotationmaterial',
            name='quotes_quot_uuid_8ce687_idx',
        ),
        migrations.RemoveIndex(
            model_name='quotationmaterial',
            name='quotes_quot_created_bbafd7_idx',
        ),
        migrations.RemoveIndex(
            model_name='quotationservice',
            name='quotes_quot_uuid_688751_idx',
        ),
        migrations.RemoveIndex(
            model_name='quotationservice',
            name='quotes_quot_created_bd13af_idx',
        ),
        migrations.RemoveIndex(
            model_name='quoteproduct',
            name='quotes_quot_uuid_b69811_idx',
        ),
        migrations.RemoveIndex(
            model_name='quoteproduct',
            name='quotes_quot_created_abba17_idx',
        ),
        migrations.RemoveIndex(
            model_name='quoteproductvariant',
            name='quotes_quot_uuid_2c1160_idx',
        ),
        migrations.RemoveIndex(
            model_name='quoteproductvariant',
            name='quotes_quot_created_63863a_idx',
        ),
    ]
