# Generated by Django 5.2.13 on 2026-07-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0023_remove_quotationitem_quotes_quot_uuid_43c2db_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotetemplate',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='quotetemplate',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, help_text='Visible en /cotizar. Una plantilla no publicada solo se ve en el panel admin.'),
        ),
        migrations.AlterField(
            model_name='quotetemplatecategory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
