# Generated by Django 5.2.13 on 2026-07-18 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0025_quotation_status_db_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotequestion',
            name='depends_on_question',
            field=models.ForeignKey(blank=True, help_text='Pregunta cuya respuesta controla la visibilidad de esta (debe ser del mismo modulo).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependents', to='quotes.quotequestion'),
        ),
        migrations.AddField(
            model_name='quotequestion',
            name='depends_on_values',
            field=models.JSONField(blank=True, default=list, help_text='Lista de valores de depends_on_question que activan la visibilidad de esta pregunta.'),
        ),
        migrations.AddField(
            model_name='quotetemplate',
            name='complexity_hint',
            field=models.CharField(blank=True, choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta')], default='', max_length=10),
        ),
    ]
