# Generated by Django 5.2.13 on 2026-07-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0030_simplify_labor_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationattachment',
            name='file',
            field=models.FileField(upload_to='quotations/attachments/'),
        ),
    ]
