# Generated by Django 5.2.13 on 2026-07-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0032_optimize_installation_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotetemplate',
            name='is_internal',
            field=models.BooleanField(db_index=True, default=False, help_text='Plantilla reservada para pruebas internas de QA. Nunca aparece en /cotizar ni es seleccionable por un cliente, sin importar el valor de is_published -- defensa adicional para que una plantilla de pruebas no vuelva a filtrarse a produccion por error (ver hallazgo H5, auditoria E2E 2026-07-23).'),
        ),
    ]
