# Generated by Django 5.2.13 on 2026-07-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0034_hide_qa_template_and_fix_camera_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, help_text='UUID generado por el wizard antes del primer intento de envio (header X-Idempotency-Key). Un reintento con la misma llave -- doble clic, F5, reconexion -- devuelve la Quotation ya creada en vez de duplicarla (defensa en profundidad detras del guard sincrono del frontend, ver H1, auditoria E2E 2026-07-23).', max_length=100, null=True, unique=True),
        ),
    ]
