# Generated by Django 6.0.4 on 2026-04-14 16:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('movement_type', models.CharField(choices=[('ENTRY', 'Entry (Purchase/Restock)'), ('EXIT', 'Exit (Sale/Adjustment)')], max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('balance_after', models.IntegerField(help_text='Stock level after this transaction')),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transactions', to='shop.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', '-created_at'], name='inventory_i_product_c769c0_idx')],
            },
        ),
    ]
