# Generated by Django 6.0.4 on 2026-04-14 19:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('object_id', models.UUIDField()),
                ('sku', models.CharField(db_index=True, max_length=100, unique=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'registro de stock',
                'verbose_name_plural': 'registros de stock',
            },
        ),
        migrations.RemoveIndex(
            model_name='inventorytransaction',
            name='inventory_i_product_c769c0_idx',
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='movement_type',
            field=models.CharField(choices=[('ENTRY', 'Entry (Purchase/Restock)'), ('EXIT', 'Exit (Sale/Adjustment)'), ('RESERVE', 'Reserve (Quote)')], max_length=10),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='stock_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.stockrecord'),
        ),
        migrations.RemoveField(
            model_name='inventorytransaction',
            name='product',
        ),
        migrations.AddIndex(
            model_name='stockrecord',
            index=models.Index(fields=['content_type', 'object_id'], name='inventory_s_content_91e5d7_idx'),
        ),
        migrations.AddIndex(
            model_name='stockrecord',
            index=models.Index(fields=['sku'], name='inventory_s_sku_c48d2c_idx'),
        ),
    ]
