# Generated by Django 5.2.13 on 2026-05-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
