# Generated by Django 5.2.13 on 2026-06-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("inventory", "0003_inventorytransaction_is_deleted"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="stockrecord",
            name="inventory_s_content_91e5d7_idx",
        ),
        migrations.RemoveIndex(
            model_name="stockrecord",
            name="inventory_s_sku_c48d2c_idx",
        ),
        migrations.AlterField(
            model_name="stockrecord",
            name="object_id",
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name="stockrecord",
            name="sku",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name="inventorytransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="quantity_must_be_greater_than_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockrecord",
            constraint=models.UniqueConstraint(
                fields=("content_type", "object_id"),
                name="unique_stock_record_per_variant",
            ),
        ),
    ]
