# Generated by Django 5.2.13 on 2026-07-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_stockrecord_inventory_s_content_91e5d7_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrecord',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
