# Generated by Django 5.2.13 on 2026-07-31 18:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMetaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(choices=[('meta', 'Meta Business Suite'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('google_search_console', 'Google Search Console'), ('google_tag_manager', 'Google Tag Manager'), ('google_analytics', 'Google Analytics'), ('bing', 'Microsoft Bing'), ('pinterest', 'Pinterest'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn'), ('apple', 'Apple'), ('cloudflare', 'Cloudflare'), ('custom', 'Personalizado')], db_index=True, max_length=30)),
                ('tag_type', models.CharField(choices=[('domain_verification', 'Verificacion de dominio'), ('analytics', 'Analytics'), ('pixel', 'Pixel de conversion'), ('seo', 'SEO'), ('social', 'Redes sociales'), ('custom', 'Personalizado')], db_index=True, max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('meta_name', models.CharField(blank=True, default='', max_length=255)),
                ('meta_content', models.CharField(blank=True, default='', max_length=500)),
                ('html_snippet', models.TextField(blank=True, default='', help_text='HTML crudo alternativo (solo etiquetas <meta>, sanitizado al guardar).')),
                ('priority', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('target_page', models.CharField(blank=True, default='', help_text='Prefijo de ruta donde se renderiza (ej. /tienda). Vacio = todas las paginas.', max_length=255)),
                ('environment', models.CharField(choices=[('all', 'Todos los entornos'), ('development', 'Development'), ('testing', 'Testing'), ('staging', 'Staging'), ('production', 'Production')], db_index=True, default='all', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'metaetiqueta del sitio',
                'verbose_name_plural': 'metaetiquetas del sitio',
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeoMetaTagAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('meta_tag_name', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.CharField(choices=[('created', 'Creada'), ('updated', 'Actualizada'), ('activated', 'Activada'), ('deactivated', 'Desactivada'), ('duplicated', 'Duplicada'), ('deleted', 'Eliminada'), ('reordered', 'Reordenada'), ('imported', 'Importada'), ('exported', 'Exportada')], db_index=True, max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('meta_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='seo.sitemetatag')),
            ],
            options={
                'verbose_name': 'auditoria de metaetiqueta',
                'verbose_name_plural': 'auditorias de metaetiquetas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sitemetatag',
            index=models.Index(fields=['is_active', 'environment', 'priority'], name='seo_sitemet_is_acti_0434ab_idx'),
        ),
        migrations.AddIndex(
            model_name='seometatagauditlog',
            index=models.Index(fields=['meta_tag', '-created_at'], name='seo_seometa_meta_ta_e4074f_idx'),
        ),
    ]
