# Generated by Django 5.2.13 on 2026-07-31 19:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_seed_meta_business_verification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVerificationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(choices=[('meta', 'Meta Business Suite'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('google_search_console', 'Google Search Console'), ('google_tag_manager', 'Google Tag Manager'), ('google_analytics', 'Google Analytics'), ('bing', 'Microsoft Bing'), ('pinterest', 'Pinterest'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn'), ('apple', 'Apple'), ('cloudflare', 'Cloudflare'), ('custom', 'Personalizado')], db_index=True, max_length=30)),
                ('filename', models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='El nombre de archivo debe terminar en .html y usar solo letras, numeros, puntos, guiones y guion bajo.', regex='^[A-Za-z0-9._-]+\\.html$')])),
                ('content', models.TextField(help_text='Contenido exacto que debe devolver el archivo.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'archivo de verificacion del sitio',
                'verbose_name_plural': 'archivos de verificacion del sitio',
                'ordering': ['filename'],
            },
        ),
    ]
