# Generated by Django 6.0.4 on 2026-04-14 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('renting', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='equipment_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='renting.equipmentvariant'),
        ),
    ]
