# Generated by Django 5.2.13 on 2026-05-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_equipment_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
