# Generated by Django 5.2.13 on 2026-06-22 15:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_shipping_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemCostSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('cost_name', models.CharField(max_length=150)),
                ('context', models.CharField(max_length=20)),
                ('cost_type', models.CharField(max_length=10)),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('computed_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_discount', models.BooleanField(default=False)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_snapshots', to='orders.orderitem')),
            ],
            options={
                'verbose_name': 'Snapshot de Costo en Orden',
                'verbose_name_plural': 'Snapshots de Costos en Ordenes',
            },
        ),
    ]
