# Generated by Django 5.2.13 on 2026-06-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('WOMPI', 'Wompi (online)'), ('COD', 'Pago contra entrega'), ('NEQUI', 'Nequi Push')], db_index=True, default='WOMPI', max_length=10),
        ),
    ]
