# Generated by Django 5.2.13 on 2026-06-30 13:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('tracking_url_template', models.CharField(blank=True, default='', max_length=300)),
                ('sla', models.CharField(blank=True, default='', max_length=255)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'transportadora',
                'verbose_name_plural': 'transportadoras',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Creado'), ('PENDING_PAYMENT', 'Pendiente de pago'), ('pending', 'Pending (legacy)'), ('processing', 'En procesamiento (legacy)'), ('paid', 'Pagado'), ('PREPARING', 'Preparando'), ('READY_FOR_DISPATCH', 'Listo para despacho'), ('ASSIGNED', 'Asignado'), ('PICKED_UP', 'Recogido'), ('IN_TRANSIT', 'En tránsito'), ('OUT_FOR_DELIVERY', 'En reparto'), ('delivered', 'Entregado'), ('COMPLETED', 'Completado'), ('cancelled', 'Cancelado'), ('RETURN_REQUESTED', 'Devolución solicitada'), ('RETURNED', 'Devuelto'), ('FAILED_DELIVERY', 'Entrega fallida'), ('LOST', 'Perdido')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='DeliveryDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('driver_type', models.CharField(choices=[('EMPLOYEE', 'Empleado'), ('EXTERNAL', 'Externo'), ('CONTRACTOR', 'Contratista')], default='EMPLOYEE', max_length=20)),
                ('vehicle', models.CharField(blank=True, default='', max_length=100)),
                ('plate', models.CharField(blank=True, default='', max_length=30)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('current_location', models.CharField(blank=True, default='', max_length=255)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='orders.carrier')),
            ],
            options={
                'verbose_name': 'repartidor',
                'verbose_name_plural': 'repartidores',
            },
        ),
        migrations.CreateModel(
            name='DispatchCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('hours', models.CharField(blank=True, default='', max_length=200)),
                ('daily_capacity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_centers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'centro de despacho',
                'verbose_name_plural': 'centros de despacho',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('shipment_number', models.CharField(db_index=True, max_length=60, unique=True)),
                ('status', models.CharField(choices=[('PREPARING', 'Preparando'), ('READY_FOR_DISPATCH', 'Listo para despacho'), ('ASSIGNED', 'Asignado'), ('PICKED_UP', 'Recogido'), ('IN_TRANSIT', 'En tránsito'), ('OUT_FOR_DELIVERY', 'En reparto'), ('delivered', 'Entregado'), ('COMPLETED', 'Completado'), ('FAILED_DELIVERY', 'Entrega fallida'), ('LOST', 'Perdido')], db_index=True, default='PREPARING', max_length=20)),
                ('vehicle', models.CharField(blank=True, default='', max_length=100)),
                ('tracking_code', models.CharField(blank=True, max_length=120, null=True)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery', models.DateTimeField(blank=True, null=True)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='orders.carrier')),
                ('dispatch_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='orders.dispatchcenter')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='orders.deliverydriver')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='orders.order')),
            ],
            options={
                'verbose_name': 'envío',
                'verbose_name_plural': 'envíos',
            },
        ),
        migrations.CreateModel(
            name='ShipmentTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('event_type', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_timeline', to='orders.order')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='orders.shipment')),
            ],
            options={
                'verbose_name': 'evento de línea de tiempo de envío',
                'verbose_name_plural': 'eventos de línea de tiempo de envíos',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentTrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField()),
                ('accuracy', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='orders.order')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_points', to='orders.shipment')),
            ],
            options={
                'verbose_name': 'evento de tracking de envío',
                'verbose_name_plural': 'eventos de tracking de envíos',
                'ordering': ['timestamp'],
            },
        ),
    ]
