# Generated by Django 5.2.13 on 2026-07-03 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_fulfillment_models'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='coupon',
            name='orders_coup_uuid_0a43c8_idx',
        ),
        migrations.RemoveIndex(
            model_name='coupon',
            name='orders_coup_created_9b1aa7_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_uuid_254377_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_created_f0ce29_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='orders_orde_uuid_1dbf37_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='orders_orde_created_054581_idx',
        ),
        migrations.RemoveIndex(
            model_name='shippingaddress',
            name='orders_ship_uuid_9a8418_idx',
        ),
        migrations.RemoveIndex(
            model_name='shippingaddress',
            name='orders_ship_created_69e1c5_idx',
        ),
    ]
