# Generated by Django 5.2.13 on 2026-07-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_coupon_orders_coup_uuid_0a43c8_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Creado'), ('PENDING_PAYMENT', 'Pendiente de pago'), ('pending', 'Pending (legacy)'), ('processing', 'En procesamiento (legacy)'), ('paid', 'Pagado'), ('PREPARING', 'Preparando'), ('READY_FOR_DISPATCH', 'Listo para despacho'), ('ASSIGNED', 'Asignado'), ('PICKED_UP', 'Recogido'), ('IN_TRANSIT', 'En tránsito'), ('OUT_FOR_DELIVERY', 'En reparto'), ('delivered', 'Entregado'), ('COMPLETED', 'Completado'), ('cancelled', 'Cancelado'), ('RETURN_REQUESTED', 'Devolución solicitada'), ('RETURNED', 'Devuelto'), ('FAILED_DELIVERY', 'Entrega fallida'), ('LOST', 'Perdido')], db_index=True, default='pending', max_length=20),
        ),
    ]
