# Generated by Django 5.2.13 on 2026-07-09 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_alter_dispatcherprofile_created_at_and_more'),
        ('orders', '0012_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='assigned_dispatcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='operations.dispatcherprofile'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='customer_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_signature',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='shipment',
            name='dispatch_scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='evidence_photos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='shipment',
            name='package_dimensions',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shipment',
            name='package_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shipment',
            name='package_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='package_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_shipments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipment',
            name='route',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipping_method',
            field=models.CharField(blank=True, choices=[('OWN_DELIVERY', 'Entrega propia'), ('INTERNAL_DISPATCHER', 'Transportista interno'), ('URBAN_COURIER', 'Mensajería urbana'), ('CARRIER_COMPANY', 'Empresa transportadora'), ('CERTIFIED_MAIL', 'Correo certificado'), ('STORE_PICKUP', 'Recogida en tienda'), ('SCHEDULED_DELIVERY', 'Entrega programada')], default='', max_length=30),
        ),
    ]
