# Generated by Django 5.2.13 on 2026-07-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_seed_shop_operation_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='label',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
