# Generated by Django 5.2.13 on 2026-07-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_seed_notify_frequent_customers_periodic_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('WOMPI', 'Wompi (online)'), ('COD', 'Pago contra entrega'), ('NEQUI', 'Nequi Push'), ('COMODATO', 'Comodato (sin costo)')], db_index=True, default='WOMPI', max_length=10),
        ),
    ]
