# Generated by Django 6.0.4 on 2026-04-14 17:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        ('technical_services', '0002_remove_servicematerial_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('push', 'Push Notification')], max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('target_audience', models.JSONField(default=dict, help_text="Filters for users (e.g. 'spent_more_than': 1000)")),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['uuid'], name='marketing_m_uuid_85d1d3_idx'), models.Index(fields=['-created_at'], name='marketing_m_created_38df8a_idx')],
            },
        ),
        migrations.CreateModel(
            name='FlashOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('service_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='technical_services.servicevariant')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productvariant')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['uuid'], name='marketing_f_uuid_fdb203_idx'), models.Index(fields=['-created_at'], name='marketing_f_created_550e35_idx')],
            },
        ),
        migrations.CreateModel(
            name='SalesAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('total_sales_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('conversion_rate', models.DecimalField(decimal_places=2, help_text='Cart to Order conversion', max_digits=5)),
                ('top_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.productvariant')),
                ('top_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='technical_services.servicevariant')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['uuid'], name='marketing_s_uuid_89d538_idx'), models.Index(fields=['-created_at'], name='marketing_s_created_07f1a1_idx')],
            },
        ),
    ]
