# Generated by Django 6.0.4 on 2026-04-14 19:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
        ('renting', '__first__'),
        ('shop', '0001_initial'),
        ('technical_services', '0002_remove_servicematerial_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketingcampaign',
            name='channel',
        ),
        migrations.AddField(
            model_name='flashoffer',
            name='equipment_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='renting.equipmentvariant'),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='channels',
            field=models.JSONField(default=list, help_text='List of active channels: email, whatsapp, facebook, instagram, youtube'),
        ),
        migrations.AddField(
            model_name='salesanalysis',
            name='renting_snapshot',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='salesanalysis',
            name='services_snapshot',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='salesanalysis',
            name='shop_snapshot',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='salesanalysis',
            name='top_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='renting.equipmentvariant'),
        ),
        migrations.AlterField(
            model_name='salesanalysis',
            name='top_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shop.productvariant'),
        ),
        migrations.AlterField(
            model_name='salesanalysis',
            name='top_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='technical_services.servicevariant'),
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('triggered_by', models.CharField(default='manual', max_length=20)),
                ('status', models.CharField(choices=[('running', 'Ejecutando'), ('completed_no_action', 'Completado — Sin acción'), ('completed_dispatched', 'Completado — Campaña despachada'), ('failed', 'Fallido')], default='running', max_length=30)),
                ('llm_provider', models.CharField(blank=True, max_length=30, null=True)),
                ('llm_decision', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs', to='marketing.marketingcampaign')),
            ],
            options={
                'verbose_name': 'ejecución del agente',
                'verbose_name_plural': 'ejecuciones del agente',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('channel', models.CharField(max_length=20)),
                ('recipient', models.CharField(help_text='Email, phone number, or page/account ID', max_length=255)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='marketing.marketingcampaign')),
            ],
            options={
                'verbose_name': 'log de campaña',
                'verbose_name_plural': 'logs de campaña',
                'unique_together': {('campaign', 'channel', 'recipient')},
            },
        ),
        migrations.CreateModel(
            name='PersonalOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reason', models.CharField(help_text='Ej: Cliente recurrente, Interés en tecnología', max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('is_redeemed', models.BooleanField(default=False)),
                ('equipment_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='renting.equipmentvariant')),
                ('service_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='technical_services.servicevariant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_offers', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productvariant')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['uuid'], name='marketing_p_uuid_050a91_idx'), models.Index(fields=['-created_at'], name='marketing_p_created_ba3311_idx')],
            },
        ),
    ]
