# Generated by Django 5.2.13 on 2026-05-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_remove_marketingcampaign_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='campaignlog',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='flashoffer',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='personaloffer',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='salesanalysis',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
