# Generated by Django 5.2.13 on 2026-07-03 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_agentrun_is_deleted_campaignlog_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='flashoffer',
            name='marketing_f_uuid_fdb203_idx',
        ),
        migrations.RemoveIndex(
            model_name='flashoffer',
            name='marketing_f_created_550e35_idx',
        ),
        migrations.RemoveIndex(
            model_name='marketingcampaign',
            name='marketing_m_uuid_85d1d3_idx',
        ),
        migrations.RemoveIndex(
            model_name='marketingcampaign',
            name='marketing_m_created_38df8a_idx',
        ),
        migrations.RemoveIndex(
            model_name='personaloffer',
            name='marketing_p_uuid_050a91_idx',
        ),
        migrations.RemoveIndex(
            model_name='personaloffer',
            name='marketing_p_created_ba3311_idx',
        ),
        migrations.RemoveIndex(
            model_name='salesanalysis',
            name='marketing_s_uuid_89d538_idx',
        ),
        migrations.RemoveIndex(
            model_name='salesanalysis',
            name='marketing_s_created_07f1a1_idx',
        ),
    ]
