# Generated by Django 5.2.13 on 2026-07-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_remove_flashoffer_marketing_f_uuid_fdb203_idx_and_more'),
        ('renting', '0012_alter_equipment_is_active_and_more'),
        ('shop', '0008_alter_product_is_active_alter_product_is_featured_and_more'),
        ('technical_services', '0021_remove_serviceconfiguration_technical_s_uuid_1565d1_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashoffer',
            name='end_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='flashoffer',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='flashoffer',
            name='start_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddConstraint(
            model_name='flashoffer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('equipment_variant__isnull', True), ('service_variant__isnull', True)), models.Q(('equipment_variant__isnull', True), ('variant__isnull', True)), models.Q(('service_variant__isnull', True), ('variant__isnull', True)), _connector='OR'), name='marketing_flashoffer_at_most_one_target'),
        ),
    ]
