# Generated by Django 5.2.13 on 2026-09-23 20:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('marketing', '0005_alter_flashoffer_end_time_alter_flashoffer_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('benefit_type', models.CharField(choices=[('FREE_SHIPPING', 'Transporte gratis'), ('FREE_INSTALLATION', 'Instalacion gratis'), ('DISCOUNT_PERCENT', 'Descuento porcentual'), ('DISCOUNT_FIXED', 'Descuento fijo')], max_length=20)),
                ('label', models.CharField(help_text='Texto libre mostrado al cliente, ej. "Transporte gratis".', max_length=255)),
                ('value', models.DecimalField(blank=True, decimal_places=2, help_text='Solo para DISCOUNT_PERCENT/DISCOUNT_FIXED -- porcentaje o monto fijo.', max_digits=10, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='marketing.marketingcampaign')),
            ],
            options={
                'verbose_name': 'beneficio de campana',
                'verbose_name_plural': 'beneficios de campana',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('object_uuid', models.UUIDField(db_index=True, help_text='UUID de la entidad de catalogo referenciada.')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketing.marketingcampaign')),
                ('content_type', models.ForeignKey(help_text='Tipo de entidad de catalogo referenciada (ej. shop.Product).', on_delete=django.db.models.deletion.CASCADE, related_name='marketing_campaign_items', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'item de campana',
                'verbose_name_plural': 'items de campana',
                'ordering': ['created_at'],
            },
        ),
    ]
