# Generated by Django 5.2.13 on 2026-09-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_campaignbenefit_campaignitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingcampaign',
            name='cta_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='cta_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='subheadline',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='terms',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
