# Generated by Django 5.2.13 on 2026-09-23 23:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_marketingcampaign_cta_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('media_type', models.CharField(choices=[('IMAGE', 'Imagen'), ('VIDEO', 'Video')], db_index=True, max_length=10)),
                ('file', models.FileField(upload_to='marketing/campaigns/')),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('size', models.PositiveIntegerField(default=0, help_text='Tamano real en bytes.')),
                ('width', models.PositiveIntegerField(blank=True, help_text='Solo imagen/video, leido del archivo real.', null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Solo imagen/video, leido del archivo real.', null=True)),
                ('duration', models.DecimalField(blank=True, decimal_places=2, help_text='Segundos, solo video -- NO validado, ver docstring de este modelo.', max_digits=8, null=True)),
                ('file_hash', models.CharField(blank=True, db_index=True, default='', help_text='SHA-256 del contenido real, para deduplicacion.', max_length=64)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='marketing.marketingcampaign')),
            ],
            options={
                'verbose_name': 'media de campana',
                'verbose_name_plural': 'media de campanas',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
