# Generated by Django 5.2.13 on 2026-09-14 15:02

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # FASE 1 (mision de simplificacion arquitectonica, 2026-09-14): habilita
        # la extension pgvector -- requiere la imagen pgvector/pgvector:pg16
        # (ver docker-compose.yml), no postgres:16-alpine. Sin esto, el
        # CreateModel de AIKnowledgeChunk (que usa VectorField) falla.
        VectorExtension(),
        migrations.CreateModel(
            name='AIKnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=255)),
                ('app_name', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('source', models.CharField(blank=True, default='', help_text='Origen del contenido (ruta de archivo, URL, o "manual" si se escribio en el panel).', max_length=500)),
                ('language', models.CharField(choices=[('markdown', 'Markdown')], default='markdown', max_length=30)),
                ('visibility', models.CharField(choices=[('public', 'Publico (puede llegar a un cliente via /chat)'), ('internal', 'Interno (documentacion de ingenieria, nunca al chat de clientes)')], db_index=True, default='internal', max_length=20)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIKnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('chunk_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True)),
                ('embedding_model', models.CharField(blank=True, default='', max_length=200)),
                ('embedded_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ai_knowledge.aiknowledgedocument')),
            ],
            options={
                'ordering': ['document_id', 'chunk_index'],
            },
        ),
        migrations.AddIndex(
            model_name='aiknowledgedocument',
            index=models.Index(fields=['app_name', 'visibility', 'is_active'], name='ai_knowledg_app_nam_0b5e05_idx'),
        ),
        migrations.AddIndex(
            model_name='aiknowledgechunk',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='aik_chunk_embed_hnsw', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddConstraint(
            model_name='aiknowledgechunk',
            constraint=models.UniqueConstraint(fields=('document', 'chunk_index'), name='unique_chunk_index_per_document'),
        ),
    ]
