# Generated by Django 5.2.13 on 2026-09-24 19:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiknowledgechunk',
            name='content_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='aiknowledgedocument',
            name='authority',
            field=models.CharField(choices=[('official', 'Oficial (politica/contenido aprobado por la empresa)'), ('internal', 'Interno'), ('third_party', 'Tercero (menor autoridad)')], default='internal', max_length=20),
        ),
        migrations.AddField(
            model_name='aiknowledgedocument',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='aiknowledgedocument',
            name='document_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='aiknowledgedocument',
            name='effective_from',
            field=models.DateTimeField(blank=True, help_text='Vigencia: no se recupera antes de esta fecha.', null=True),
        ),
        migrations.AddField(
            model_name='aiknowledgedocument',
            name='effective_until',
            field=models.DateTimeField(blank=True, help_text='Vigencia: no se recupera despues de esta fecha.', null=True),
        ),
        migrations.AddField(
            model_name='aiknowledgedocument',
            name='injection_flags',
            field=models.JSONField(blank=True, default=list, help_text='Categorias de inyeccion halladas al ingerir (sin el texto).'),
        ),
        migrations.AddField(
            model_name='aiknowledgedocument',
            name='review_status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('needs_review', 'Requiere revision (el analisis de ingesta encontro banderas)'), ('approved', 'Aprobado')], db_index=True, default='approved', max_length=20),
        ),
        migrations.CreateModel(
            name='AIKnowledgeDocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('version', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('authority', models.CharField(blank=True, default='', max_length=20)),
                ('review_status', models.CharField(blank=True, default='', max_length=20)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='ai_knowledge.aiknowledgedocument')),
                ('saved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['document_id', '-version'],
                'constraints': [models.UniqueConstraint(fields=('document', 'version'), name='unique_version_per_document')],
            },
        ),
    ]
