# Generated by Django 5.2.13 on 2026-06-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_brand_is_deleted_category_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
        migrations.AddField(
            model_name='brand',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, default='', help_text='Descripcion para motores de busqueda (max 160 caracteres recomendados).'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, default='', help_text='Titulo para motores de busqueda (max 70 caracteres).', max_length=70),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, default='', help_text='Descripcion SEO del producto (max 160 caracteres recomendados).'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, default='', help_text='Titulo SEO del producto (max 70 caracteres).', max_length=70),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Atributos dinamicos en formato JSON. Ej: {"color": "Rojo", "talla": "M"}.'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='discount_end_date',
            field=models.DateTimeField(blank=True, help_text='Fecha de fin del descuento. Si es null, el descuento no tiene restriccion de fin.', null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='discount_start_date',
            field=models.DateTimeField(blank=True, help_text='Fecha de inicio del descuento. Si es null, el descuento no tiene restriccion de inicio.', null=True),
        ),
    ]
