# Generated by Django 5.2.13 on 2026-06-22 17:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCostRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('cost_type', models.CharField(choices=[('FIXED', 'Valor fijo (COP)'), ('PERCENTAGE', 'Porcentaje (%)')], db_index=True, max_length=10)),
                ('context', models.CharField(choices=[('TAX', 'Impuesto'), ('DISCOUNT', 'Descuento')], db_index=True, max_length=20)),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('applies_globally', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'regla de costo de producto',
                'verbose_name_plural': 'reglas de costo de producto',
            },
        ),
        migrations.CreateModel(
            name='ProductCostAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_assignments', to='shop.productvariant')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='shop.productcostrule')),
            ],
            options={
                'verbose_name': 'asignacion de regla de costo',
                'verbose_name_plural': 'asignaciones de reglas de costo',
                'unique_together': {('rule', 'variant')},
            },
        ),
    ]
