# Generated by Django 5.2.13 on 2026-06-22 21:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productcostrule_productcostassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Alto en cm', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Largo en cm', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso en kg', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ancho en cm', max_digits=12, null=True),
        ),
    ]
