# Generated by Django 5.2.13 on 2026-07-03 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_extend_productvariant_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='brand',
            name='shop_brand_uuid_488a13_idx',
        ),
        migrations.RemoveIndex(
            model_name='brand',
            name='shop_brand_created_f3f8b2_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='shop_produc_uuid_c5199e_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='shop_produc_created_ddfb00_idx',
        ),
        migrations.RemoveIndex(
            model_name='productreview',
            name='shop_produc_uuid_406101_idx',
        ),
        migrations.RemoveIndex(
            model_name='productreview',
            name='shop_produc_created_2ce4bd_idx',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='shop_produc_uuid_48c190_idx',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='shop_produc_created_a444fa_idx',
        ),
        migrations.RemoveIndex(
            model_name='tax',
            name='shop_tax_uuid_23a23d_idx',
        ),
        migrations.RemoveIndex(
            model_name='tax',
            name='shop_tax_created_bfeeec_idx',
        ),
    ]
