# Generated by Django 5.2.13 on 2026-08-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_productimage_image_type_productdocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='scope',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.TextField(blank=True, default=''),
        ),
    ]
