# Generated by Django 5.2.13 on 2026-08-06 17:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_scope_product_warranty'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFunctioningStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('step_number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/functioning/')),
                ('estimated_time', models.CharField(blank=True, default='', help_text='Ej: 30 min, 1-2 horas', max_length=100)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functioning_steps', to='shop.product')),
            ],
            options={
                'verbose_name': 'paso de funcionamiento de producto',
                'verbose_name_plural': 'pasos de funcionamiento de producto',
                'ordering': ['position', 'created_at'],
            },
        ),
    ]
