# Generated by Django 5.2.13 on 2026-07-30 23:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


NOTIFICATION_TEMPLATES = [
    {
        'slug': 'rental_payment_confirmed',
        'name': 'Alquiler confirmado (pago en linea)',
        'ws_event_type': 'rental_payment_confirmed',
        'subject': 'Tu alquiler fue confirmado - Ticket {{ticket_number}}',
        'email_body': (
            'Hola {{user_name}},\n\n'
            'Tu pago fue aprobado y tu solicitud de alquiler para {{equipment_name}} '
            'quedo confirmada.\n\n'
            'Detalle de tu reserva:\n'
            '- Periodo: {{start_date}} al {{end_date}}\n'
            '- Total pagado: ${{grand_total}} COP\n\n'
            'NUMERO DE TICKET DE SERVICIO: {{ticket_number}}\n\n'
            'Usa este numero de ticket para dar seguimiento a la entrega de tu equipo '
            'desde Mi Cuenta > Operaciones.\n\n'
            'Gracias por confiar en Sintel.'
        ),
        'whatsapp_template_name': '',
        'is_active': True,
    },
    {
        'slug': 'rental_cod_confirmed',
        'name': 'Alquiler confirmado (contra entrega, aprobado por admin)',
        'ws_event_type': 'rental_cod_confirmed',
        'subject': 'Tu alquiler fue confirmado - Ticket {{ticket_number}}',
        'email_body': (
            'Hola {{user_name}},\n\n'
            'Tu solicitud de alquiler para {{equipment_name}} fue aprobada y quedo '
            'confirmada. El pago se realiza contra entrega.\n\n'
            'Detalle de tu reserva:\n'
            '- Periodo: {{start_date}} al {{end_date}}\n'
            '- Total a pagar: ${{grand_total}} COP\n\n'
            'NUMERO DE TICKET DE SERVICIO: {{ticket_number}}\n\n'
            'Usa este numero de ticket para dar seguimiento a la entrega de tu equipo '
            'desde Mi Cuenta > Operaciones.\n\n'
            'Gracias por confiar en Sintel.'
        ),
        'whatsapp_template_name': '',
        'is_active': True,
    },
]


def seed_notification_templates(apps, schema_editor):
    NotificationTemplate = apps.get_model('notifications', 'NotificationTemplate')
    for data in NOTIFICATION_TEMPLATES:
        NotificationTemplate.objects.update_or_create(
            slug=data['slug'],
            defaults={k: v for k, v in data.items() if k != 'slug'},
        )


def reverse_notification_templates(apps, schema_editor):
    NotificationTemplate = apps.get_model('notifications', 'NotificationTemplate')
    NotificationTemplate.objects.filter(
        slug__in=[t['slug'] for t in NOTIFICATION_TEMPLATES]
    ).delete()


class Migration(migrations.Migration):

    replaces = [('renting', '0001_initial'), ('renting', '0002_equipment_is_deleted_equipmentimage_is_deleted_and_more'), ('renting', '0003_rental_request_model'), ('renting', '0004_equipment_logistics_config'), ('renting', '0005_rentalcostrule_rentalcostassignment'), ('renting', '0006_rentalperiod'), ('renting', '0007_rename_renting_ren_start_d_idx_renting_ren_start_d_66c104_idx_and_more'), ('renting', '0008_multipayment'), ('renting', '0009_rentalrequest_priority'), ('renting', '0010_rentalprojectattachment'), ('renting', '0011_remove_equipmentimage_renting_equ_uuid_dafff2_idx_and_more'), ('renting', '0012_alter_equipment_is_active_and_more'), ('renting', '0013_rental_lifecycle_v2'), ('renting', '0014_seed_notification_templates')]

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_offered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'equipo',
                'verbose_name_plural': 'equipos',
            },
        ),
        migrations.CreateModel(
            name='EquipmentVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('sku', models.CharField(db_index=True, max_length=100, unique=True)),
                ('rental_price_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rental_price_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='renting.equipment')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'variante de equipo',
                'verbose_name_plural': 'variantes de equipos',
            },
        ),
        migrations.CreateModel(
            name='RentingBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['uuid'], name='renting_ren_uuid_6be1b6_idx'), models.Index(fields=['-created_at'], name='renting_ren_created_ffc2d4_idx')],
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='renting.rentingbrand'),
        ),
        migrations.CreateModel(
            name='RentingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='renting.rentingcategory')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'categoría de renta',
                'verbose_name_plural': 'categorías de rentas',
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='renting.rentingcategory'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='EquipmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('image', models.ImageField(upload_to='renting/')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='renting.equipment')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='renting.equipmentvariant')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['uuid'], name='renting_equ_uuid_dafff2_idx'), models.Index(fields=['-created_at'], name='renting_equ_created_627cf6_idx')],
            },
        ),
        migrations.CreateModel(
            name='EquipmentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='renting.equipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_reviews', to=settings.AUTH_USER_MODEL)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['uuid'], name='renting_equ_uuid_29416b_idx'), models.Index(fields=['-created_at'], name='renting_equ_created_ca9e60_idx')],
            },
        ),
        migrations.CreateModel(
            name='RentalLabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'mano de obra de renta',
                'verbose_name_plural': 'mano de obra de rentas',
            },
        ),
        migrations.CreateModel(
            name='RentalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('pending_validation', 'Pendiente de validacion'), ('pending_payment', 'Pendiente de pago'), ('paid', 'Pagado'), ('confirmed', 'Confirmado'), ('in_operation', 'En operacion'), ('finished', 'Finalizado'), ('cancelled', 'Cancelado')], db_index=True, default='draft', max_length=30)),
                ('location_address', models.CharField(blank=True, default='', max_length=500)),
                ('location_city', models.CharField(blank=True, default='', max_length=100)),
                ('location_department', models.CharField(blank=True, default='', max_length=100)),
                ('location_coordinates', models.CharField(blank=True, default='', max_length=100)),
                ('project_type', models.CharField(blank=True, default='', max_length=255)),
                ('access_conditions', models.TextField(blank=True, default='')),
                ('location_notes', models.TextField(blank=True, default='')),
                ('contact_full_name', models.CharField(blank=True, default='', max_length=255)),
                ('contact_doc_type', models.CharField(choices=[('CC', 'Cedula de ciudadania'), ('NIT', 'NIT'), ('CE', 'Cedula de extranjeria'), ('PP', 'Pasaporte')], default='CC', max_length=10)),
                ('contact_doc_number', models.CharField(blank=True, default='', max_length=50)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=30)),
                ('contact_company', models.CharField(blank=True, default='', max_length=255)),
                ('contact_position', models.CharField(blank=True, default='', max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('rental_mode', models.CharField(choices=[('days', 'Por dias'), ('hours', 'Por horas')], default='days', max_length=10)),
                ('operational_notes', models.TextField(blank=True, default='')),
                ('terms_accepted', models.BooleanField(default=False)),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pickup_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('installation_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('calibration_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('training_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('startup_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_rental_days', models.PositiveIntegerField(blank=True, null=True)),
                ('base_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('labor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('transport_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('setup_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('grand_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('wompi_reference', models.CharField(blank=True, default='', max_length=255)),
                ('wompi_transaction_id', models.CharField(blank=True, default='', max_length=255)),
                ('payment_status', models.CharField(blank=True, default='', max_length=50)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('equipment_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_requests', to='renting.equipmentvariant')),
                ('labor_items', models.ManyToManyField(blank=True, related_name='rental_requests', to='renting.rentallabor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'solicitud de alquiler',
                'verbose_name_plural': 'solicitudes de alquiler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentLogisticsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('delivery_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='costo de entrega')),
                ('pickup_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='costo de recogida')),
                ('installation_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='costo de instalacion')),
                ('calibration_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='costo de calibracion')),
                ('training_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='costo de capacitacion')),
                ('startup_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='costo de puesta en marcha')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notas adicionales')),
                ('equipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_config', to='renting.equipment')),
            ],
            options={
                'verbose_name': 'configuracion de logistica',
                'verbose_name_plural': 'configuraciones de logistica',
            },
        ),
        migrations.CreateModel(
            name='RentalCostRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('cost_type', models.CharField(choices=[('FIXED', 'Valor fijo (COP)'), ('PERCENTAGE', 'Porcentaje (%)')], db_index=True, max_length=10)),
                ('context', models.CharField(choices=[('TAX', 'Impuesto (IVA)'), ('DISCOUNT', 'Descuento'), ('DEPOSIT', 'Deposito de garantia'), ('INSURANCE', 'Seguro del equipo'), ('SURCHARGE', 'Recargo adicional')], db_index=True, max_length=20)),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('applies_globally', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'regla de costo de alquiler',
                'verbose_name_plural': 'reglas de costo de alquiler',
            },
        ),
        migrations.CreateModel(
            name='RentalCostAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_assignments', to='renting.equipmentvariant')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='renting.rentalcostrule')),
            ],
            options={
                'verbose_name': 'asignacion de regla de costo de alquiler',
                'verbose_name_plural': 'asignaciones de reglas de costo de alquiler',
                'unique_together': {('rule', 'variant')},
            },
        ),
        migrations.CreateModel(
            name='RentalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('scheduled', 'Programado'), ('active', 'Activo'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], db_index=True, default='scheduled', max_length=20)),
                ('equipment_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_periods', to='renting.equipmentvariant')),
                ('rental_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='renting.rentalrequest')),
            ],
            options={
                'verbose_name': 'periodo de alquiler',
                'verbose_name_plural': 'periodos de alquiler',
                'indexes': [models.Index(fields=['start_date', 'end_date'], name='renting_ren_start_d_66c104_idx'), models.Index(fields=['equipment_variant', 'status'], name='renting_ren_equipme_aa3ef9_idx')],
            },
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='payment_method',
            field=models.CharField(choices=[('WOMPI', 'Wompi'), ('NEQUI', 'Nequi'), ('COD', 'Contra entrega')], default='WOMPI', max_length=20),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Baja'), ('HIGH', 'Alta')], db_index=True, default='LOW', max_length=10),
        ),
        migrations.CreateModel(
            name='RentalProjectAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('file', models.FileField(upload_to='renting/project_attachments/%Y/%m/')),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('rental_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_attachments', to='renting.rentalrequest')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_project_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='equipmentimage',
            name='renting_equ_uuid_dafff2_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipmentimage',
            name='renting_equ_created_627cf6_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipmentreview',
            name='renting_equ_uuid_29416b_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipmentreview',
            name='renting_equ_created_ca9e60_idx',
        ),
        migrations.RemoveIndex(
            model_name='rentingbrand',
            name='renting_ren_uuid_6be1b6_idx',
        ),
        migrations.RemoveIndex(
            model_name='rentingbrand',
            name='renting_ren_created_ffc2d4_idx',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='rentalperiod',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalperiod',
            name='rental_mode',
            field=models.CharField(choices=[('days', 'Por dias'), ('hours', 'Por horas')], db_index=True, default='days', max_length=10),
        ),
        migrations.AddField(
            model_name='rentalperiod',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='admin_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='delivery_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='refund_required',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='rentalrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('pending_validation', 'Pendiente de validacion'), ('pending_payment', 'Pendiente de pago'), ('paid', 'Pagado'), ('confirmed', 'Confirmado'), ('in_operation', 'En operacion'), ('finished', 'Finalizado'), ('cancelled', 'Cancelado'), ('payment_conflict', 'Conflicto de pago')], db_index=True, default='draft', max_length=30),
        ),
        migrations.AddIndex(
            model_name='rentalperiod',
            index=models.Index(fields=['equipment_variant', 'start_date', 'end_date'], name='renting_period_var_range_idx'),
        ),
        migrations.RunPython(
            code=seed_notification_templates,
            reverse_code=reverse_notification_templates,
        ),
    ]
