# Generated by Django 5.2.13 on 2026-06-20 15:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0002_equipment_is_deleted_equipmentimage_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('pending_validation', 'Pendiente de validacion'), ('pending_payment', 'Pendiente de pago'), ('paid', 'Pagado'), ('confirmed', 'Confirmado'), ('in_operation', 'En operacion'), ('finished', 'Finalizado'), ('cancelled', 'Cancelado')], db_index=True, default='draft', max_length=30)),
                ('location_address', models.CharField(blank=True, default='', max_length=500)),
                ('location_city', models.CharField(blank=True, default='', max_length=100)),
                ('location_department', models.CharField(blank=True, default='', max_length=100)),
                ('location_coordinates', models.CharField(blank=True, default='', max_length=100)),
                ('project_type', models.CharField(blank=True, default='', max_length=255)),
                ('access_conditions', models.TextField(blank=True, default='')),
                ('location_notes', models.TextField(blank=True, default='')),
                ('contact_full_name', models.CharField(blank=True, default='', max_length=255)),
                ('contact_doc_type', models.CharField(choices=[('CC', 'Cedula de ciudadania'), ('NIT', 'NIT'), ('CE', 'Cedula de extranjeria'), ('PP', 'Pasaporte')], default='CC', max_length=10)),
                ('contact_doc_number', models.CharField(blank=True, default='', max_length=50)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=30)),
                ('contact_company', models.CharField(blank=True, default='', max_length=255)),
                ('contact_position', models.CharField(blank=True, default='', max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('rental_mode', models.CharField(choices=[('days', 'Por dias'), ('hours', 'Por horas')], default='days', max_length=10)),
                ('operational_notes', models.TextField(blank=True, default='')),
                ('terms_accepted', models.BooleanField(default=False)),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pickup_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('installation_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('calibration_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('training_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('startup_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_rental_days', models.PositiveIntegerField(blank=True, null=True)),
                ('base_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('labor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('transport_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('setup_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('grand_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('wompi_reference', models.CharField(blank=True, default='', max_length=255)),
                ('wompi_transaction_id', models.CharField(blank=True, default='', max_length=255)),
                ('payment_status', models.CharField(blank=True, default='', max_length=50)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('equipment_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_requests', to='renting.equipmentvariant')),
                ('labor_items', models.ManyToManyField(blank=True, related_name='rental_requests', to='renting.rentallabor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'solicitud de alquiler',
                'verbose_name_plural': 'solicitudes de alquiler',
                'ordering': ['-created_at'],
            },
        ),
    ]
