# Generated by Django 5.2.13 on 2026-06-20 16:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0003_rental_request_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentLogisticsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('delivery_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='costo de entrega')),
                ('pickup_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='costo de recogida')),
                ('installation_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='costo de instalacion')),
                ('calibration_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='costo de calibracion')),
                ('training_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='costo de capacitacion')),
                ('startup_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='costo de puesta en marcha')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notas adicionales')),
                ('equipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_config', to='renting.equipment')),
            ],
            options={
                'verbose_name': 'configuracion de logistica',
                'verbose_name_plural': 'configuraciones de logistica',
            },
        ),
    ]
