# Generated by Django 5.2.13 on 2026-06-24 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0006_rentalperiod'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rentalperiod',
            new_name='renting_ren_start_d_66c104_idx',
            old_name='renting_ren_start_d_idx',
        ),
        migrations.RenameIndex(
            model_name='rentalperiod',
            new_name='renting_ren_equipme_aa3ef9_idx',
            old_name='renting_ren_equip_st_idx',
        ),
    ]
