# Generated by Django 5.2.13 on 2026-06-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0007_rename_renting_ren_start_d_idx_renting_ren_start_d_66c104_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrequest',
            name='payment_method',
            field=models.CharField(choices=[('WOMPI', 'Wompi'), ('NEQUI', 'Nequi'), ('COD', 'Contra entrega')], default='WOMPI', max_length=20),
        ),
    ]
