# Generated by Django 5.2.13 on 2026-07-03 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0010_rentalprojectattachment'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='equipmentimage',
            name='renting_equ_uuid_dafff2_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipmentimage',
            name='renting_equ_created_627cf6_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipmentreview',
            name='renting_equ_uuid_29416b_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipmentreview',
            name='renting_equ_created_ca9e60_idx',
        ),
        migrations.RemoveIndex(
            model_name='rentingbrand',
            name='renting_ren_uuid_6be1b6_idx',
        ),
        migrations.RemoveIndex(
            model_name='rentingbrand',
            name='renting_ren_created_ffc2d4_idx',
        ),
    ]
