# Generated by Django 5.2.13 on 2026-07-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0011_remove_equipmentimage_renting_equ_uuid_dafff2_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
