# Generated by Django 5.2.13 on 2026-07-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0012_alter_equipment_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalperiod',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalperiod',
            name='rental_mode',
            field=models.CharField(choices=[('days', 'Por dias'), ('hours', 'Por horas')], db_index=True, default='days', max_length=10),
        ),
        migrations.AddField(
            model_name='rentalperiod',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='admin_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='delivery_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='refund_required',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='rentalrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('pending_validation', 'Pendiente de validacion'), ('pending_payment', 'Pendiente de pago'), ('paid', 'Pagado'), ('confirmed', 'Confirmado'), ('in_operation', 'En operacion'), ('finished', 'Finalizado'), ('cancelled', 'Cancelado'), ('payment_conflict', 'Conflicto de pago')], db_index=True, default='draft', max_length=30),
        ),
        migrations.AddIndex(
            model_name='rentalperiod',
            index=models.Index(fields=['equipment_variant', 'start_date', 'end_date'], name='renting_period_var_range_idx'),
        ),
    ]
