# Generated by Django 5.2.13 on 2026-07-07 17:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0003_alter_dispatcherprofile_created_at_and_more"),
        ("renting", "0014_seed_notification_templates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RentalOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("READY_FOR_SCHEDULING", "Pendiente de programar"),
                            ("SCHEDULED", "Programada"),
                            ("TRANSPORT_ASSIGNED", "Transportista asignado"),
                            ("READY_FOR_DELIVERY", "Lista para entrega"),
                            ("DELIVERED", "Entregada"),
                            ("IN_OPERATION", "En operacion"),
                            ("READY_FOR_PICKUP", "Lista para recogida"),
                            ("PICKED_UP", "Recogida"),
                            ("RETURN_INSPECTION", "Inspeccion de devolucion"),
                            ("COMPLETED", "Completada"),
                        ],
                        db_index=True,
                        default="READY_FOR_SCHEDULING",
                        max_length=30,
                    ),
                ),
                (
                    "assigned_vehicle",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "delivery_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("delivery_time", models.TimeField(blank=True, null=True)),
                ("pickup_date", models.DateField(blank=True, db_index=True, null=True)),
                ("pickup_time", models.TimeField(blank=True, null=True)),
                (
                    "estimated_duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("route", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "priority",
                    models.CharField(
                        choices=[("LOW", "Baja"), ("HIGH", "Alta")],
                        db_index=True,
                        default="LOW",
                        max_length=10,
                    ),
                ),
                (
                    "assigned_dispatcher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rental_operations",
                        to="operations.dispatcherprofile",
                    ),
                ),
                (
                    "rental_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rental_operation",
                        to="renting.rentalrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RentalOperationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("event_type", models.CharField(db_index=True, max_length=50)),
                ("description", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rental_operation_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline",
                        to="renting.rentaloperation",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="rentaloperation",
            index=models.Index(
                fields=["status", "delivery_date"], name="renting_ren_status_f8588d_idx"
            ),
        ),
    ]
