# Generated by Django 5.2.13 on 2026-07-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0016_seed_rental_operation_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentaloperation',
            name='has_incident',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='rentaloperation',
            name='incident_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
