# Generated by Django 5.2.13 on 2026-07-14 14:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0018_seed_rental_operation_lifecycle_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('block_type', models.CharField(choices=[('MAINTENANCE', 'Mantenimiento'), ('DAMAGE', 'Daño'), ('INVENTORY', 'Conteo de inventario'), ('OTHER', 'Otro')], db_index=True, default='MAINTENANCE', max_length=20)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('released', 'Liberado')], db_index=True, default='active', max_length=10)),
                ('reason', models.TextField()),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('release_reason', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_blocks_created', to=settings.AUTH_USER_MODEL)),
                ('equipment_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='renting.equipmentvariant')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_blocks_released', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'bloqueo de equipo',
                'verbose_name_plural': 'bloqueos de equipo',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['equipment_variant', 'status'], name='renting_equ_equipme_3b8335_idx'), models.Index(fields=['equipment_variant', 'start_date', 'end_date'], name='renting_block_var_range_idx')],
            },
        ),
    ]
