# Generated by Django 5.2.13 on 2026-07-14 15:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0020_seed_expire_pending_payment_periodic_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentReturnInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('has_damage', models.BooleanField(db_index=True, default=False)),
                ('condition_notes', models.TextField(blank=True, default='')),
                ('missing_accessories', models.TextField(blank=True, default='')),
                ('inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_return_inspections', to=settings.AUTH_USER_MODEL)),
                ('rental_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_inspection', to='renting.rentalrequest')),
                ('resulting_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_inspections', to='renting.equipmentblock')),
            ],
            options={
                'verbose_name': 'inspeccion de devolucion',
                'verbose_name_plural': 'inspecciones de devolucion',
                'ordering': ['-created_at'],
            },
        ),
    ]
