# Generated by Django 5.2.13 on 2026-07-16 21:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0022_catalog_detail_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentreview',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='equipmentreview',
            unique_together={('user', 'equipment')},
        ),
    ]
