# Generated by Django 5.2.13 on 2026-07-17 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0025_update_payment_result_notification_templates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentimage',
            name='variant',
        ),
    ]
