# Generated by Django 5.2.13 on 2026-07-17 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0026_remove_equipmentimage_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalcostrule',
            name='applies_globally',
        ),
    ]
