# Generated by Django 5.2.13 on 2026-07-17 22:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0027_remove_applies_globally_from_rentalcostrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('reference_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='precio de referencia (anterior)')),
                ('promo_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='precio promocional')),
                ('show_discount_percentage', models.BooleanField(default=True, verbose_name='mostrar porcentaje de descuento')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='etiquetas comerciales')),
                ('main_message', models.TextField(blank=True, default='', verbose_name='mensaje principal')),
                ('featured_benefit', models.CharField(blank=True, default='', max_length=255, verbose_name='beneficio destacado')),
                ('trust_message', models.CharField(blank=True, default='', max_length=255, verbose_name='mensaje de confianza')),
                ('urgency_message', models.CharField(blank=True, default='', max_length=255, verbose_name='mensaje de urgencia')),
                ('social_proof_message', models.CharField(blank=True, default='', max_length=255, verbose_name='prueba social')),
                ('purchase_price_reference', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='precio estimado de compra')),
                ('financial_message', models.CharField(blank=True, default='', max_length=255, verbose_name='mensaje financiero')),
                ('use_cases', models.JSONField(blank=True, default=list, verbose_name='casos de uso')),
                ('cta_label', models.CharField(blank=True, default='', max_length=100, verbose_name='texto del CTA')),
                ('promo_banner_message', models.CharField(blank=True, default='', max_length=255, verbose_name='banner promocional')),
                ('quick_benefits', models.JSONField(blank=True, default=list, verbose_name='beneficios rapidos')),
                ('equipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketing', to='renting.equipment')),
            ],
            options={
                'verbose_name': 'marketing de equipo',
                'verbose_name_plural': 'marketing de equipos',
            },
        ),
    ]
