# Generated by Django 5.2.13 on 2026-07-22 19:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0029_seed_notify_rentals_expiring_periodic_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalperiod',
            name='commercial_type',
            field=models.CharField(choices=[('RENTAL', 'Renting'), ('COMODATO', 'Comodato')], db_index=True, default='RENTAL', max_length=10),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='commercial_type',
            field=models.CharField(choices=[('RENTAL', 'Renting'), ('COMODATO', 'Comodato')], db_index=True, default='RENTAL', max_length=10),
        ),
        migrations.CreateModel(
            name='EquipmentCommercialConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('renting_enabled', models.BooleanField(default=True, verbose_name='renting habilitado')),
                ('comodato_enabled', models.BooleanField(default=False, verbose_name='comodato habilitado')),
                ('comodato_notes', models.TextField(blank=True, default='', verbose_name='notas de comodato')),
                ('equipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_config', to='renting.equipment')),
            ],
            options={
                'verbose_name': 'configuracion comercial',
                'verbose_name_plural': 'configuraciones comerciales',
            },
        ),
        migrations.CreateModel(
            name='EquipmentCommercialOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('modality', models.CharField(choices=[('RENTAL', 'Renting'), ('COMODATO', 'Comodato')], default='COMODATO', max_length=10)),
                ('term_months', models.PositiveSmallIntegerField(choices=[(6, '6 meses'), (12, '12 meses'), (18, '18 meses'), (24, '24 meses'), (36, '36 meses')])),
                ('is_enabled', models.BooleanField(default=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_options', to='renting.equipment')),
            ],
            options={
                'verbose_name': 'opcion comercial',
                'verbose_name_plural': 'opciones comerciales',
                'ordering': ['modality', 'term_months'],
                'constraints': [models.UniqueConstraint(fields=('equipment', 'modality', 'term_months'), name='renting_commercialoption_unique_term')],
            },
        ),
    ]
