# Generated by Django 5.2.13 on 2026-07-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0031_seed_comodato_notification_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalrequest',
            name='payment_method',
            field=models.CharField(choices=[('WOMPI', 'Wompi'), ('NEQUI', 'Nequi'), ('COD', 'Contra entrega'), ('COMODATO', 'Comodato (sin costo)')], default='WOMPI', max_length=20),
        ),
    ]
