# Generated by Django 5.2.13 on 2026-07-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0032_alter_rentalrequest_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrequest',
            name='price_per_day_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot de EquipmentVariant.rental_price_per_day al crear la solicitud.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='price_per_hour_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot de EquipmentVariant.rental_price_per_hour al crear la solicitud.', max_digits=14, null=True),
        ),
    ]
