# Generated by Django 5.2.13 on 2026-07-27 14:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0033_add_rental_request_price_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalRequestContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('contact_full_name', models.CharField(blank=True, default='', max_length=255)),
                ('contact_doc_type', models.CharField(choices=[('CC', 'Cedula de ciudadania'), ('NIT', 'NIT'), ('CE', 'Cedula de extranjeria'), ('PP', 'Pasaporte')], default='CC', max_length=10)),
                ('contact_doc_number', models.CharField(blank=True, default='', max_length=50)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=30)),
                ('contact_company', models.CharField(blank=True, default='', max_length=255)),
                ('contact_position', models.CharField(blank=True, default='', max_length=255)),
                ('rental_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='renting.rentalrequest')),
            ],
            options={
                'verbose_name': 'responsable de solicitud',
                'verbose_name_plural': 'responsables de solicitudes',
            },
        ),
        migrations.CreateModel(
            name='RentalRequestCosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pickup_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('installation_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('calibration_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('training_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('startup_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_rental_days', models.PositiveIntegerField(blank=True, null=True)),
                ('base_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('price_per_day_snapshot', models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot de EquipmentVariant.rental_price_per_day al crear la solicitud.', max_digits=14, null=True)),
                ('price_per_hour_snapshot', models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot de EquipmentVariant.rental_price_per_hour al crear la solicitud.', max_digits=14, null=True)),
                ('labor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('transport_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('setup_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('grand_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('rental_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='costs_info', to='renting.rentalrequest')),
            ],
            options={
                'verbose_name': 'costos de solicitud',
                'verbose_name_plural': 'costos de solicitudes',
            },
        ),
        migrations.CreateModel(
            name='RentalRequestLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('location_address', models.CharField(blank=True, default='', max_length=500)),
                ('location_city', models.CharField(blank=True, default='', max_length=100)),
                ('location_department', models.CharField(blank=True, default='', max_length=100)),
                ('location_coordinates', models.CharField(blank=True, default='', max_length=100)),
                ('project_type', models.CharField(blank=True, default='', max_length=255)),
                ('access_conditions', models.TextField(blank=True, default='')),
                ('location_notes', models.TextField(blank=True, default='')),
                ('rental_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location_info', to='renting.rentalrequest')),
            ],
            options={
                'verbose_name': 'lugar de operacion de solicitud',
                'verbose_name_plural': 'lugares de operacion de solicitudes',
            },
        ),
        migrations.CreateModel(
            name='RentalRequestPaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('payment_method', models.CharField(choices=[('WOMPI', 'Wompi'), ('NEQUI', 'Nequi'), ('COD', 'Contra entrega'), ('COMODATO', 'Comodato (sin costo)')], default='WOMPI', max_length=20)),
                ('wompi_reference', models.CharField(blank=True, default='', max_length=255)),
                ('wompi_transaction_id', models.CharField(blank=True, default='', max_length=255)),
                ('payment_status', models.CharField(blank=True, default='', max_length=50)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('rental_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_info', to='renting.rentalrequest')),
            ],
            options={
                'verbose_name': 'pago de solicitud',
                'verbose_name_plural': 'pagos de solicitudes',
            },
        ),
    ]
