# Generated by Django 5.2.13 on 2026-07-27 14:30
#
# Cierra el split de RentalRequest (auditoria DB-H1): estas 35 columnas ya
# viven en las 4 tablas hijas creadas en 0034 y backfilleadas en 0035 (los
# datos historicos ya estan copiados, confirmado 61/61 filas antes de aplicar
# esta migracion). renting/models.py ya las expone solo como @property que
# delega a los sub-modelos -- este RemoveField solo pone al dia el estado de
# migraciones para que coincida con eso, y elimina las columnas huerfanas que
# quedaban NOT NULL sin default, lo que rompia todo INSERT nuevo de
# RentalRequest (bug real: 500 en todo el backend, ver auditoria 2026-07-27).

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0035_backfill_rental_request_submodels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalrequest',
            name='access_conditions',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='base_cost',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='calibration_cost',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='contact_company',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='contact_doc_number',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='contact_doc_type',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='contact_full_name',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='contact_position',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='delivery_cost',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='distance_km',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='grand_total',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='installation_cost',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='labor_total',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='location_address',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='location_city',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='location_coordinates',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='location_department',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='location_notes',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='paid_at',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='pickup_cost',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='price_per_day_snapshot',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='price_per_hour_snapshot',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='project_type',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='setup_total',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='startup_cost',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='total_rental_days',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='training_cost',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='transport_total',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='wompi_reference',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='wompi_transaction_id',
        ),
    ]
