# Generated by Django 5.2.13 on 2026-07-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0036_remove_rentalrequest_access_conditions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalrequestpaymentinfo',
            name='payment_status',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
    ]
