# Generated by Django 5.2.13 on 2026-08-05 15:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('object_uuid', models.UUIDField(db_index=True)),
                ('related_object_uuid', models.UUIDField(db_index=True)),
                ('relation_type', models.CharField(choices=[('related', 'Relacionado'), ('compatible', 'Compatible'), ('accessory', 'Accesorio')], db_index=True, max_length=20)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_relations_from', to='contenttypes.contenttype')),
                ('related_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_relations_to', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'relacion de catalogo',
                'verbose_name_plural': 'relaciones de catalogo',
                'ordering': ['display_order'],
                'unique_together': {('content_type', 'object_uuid', 'related_content_type', 'related_object_uuid', 'relation_type')},
            },
        ),
        migrations.CreateModel(
            name='ContentBlockConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('object_uuid', models.UUIDField(db_index=True)),
                ('block_type', models.CharField(choices=[('description', 'Descripcion general'), ('scope', 'Alcance'), ('included', 'Que incluye'), ('excluded', 'Que NO incluye'), ('installation', 'Instalacion'), ('support', 'Soporte'), ('benefits', 'Beneficios'), ('warranty', 'Garantia'), ('specs', 'Ficha tecnica'), ('documents', 'Documentacion'), ('videos', 'Videos'), ('faq', 'FAQ'), ('compatible', 'Productos compatibles'), ('accessories', 'Accesorios recomendados'), ('related', 'Productos relacionados')], db_index=True, max_length=20)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'configuracion de bloque de contenido',
                'verbose_name_plural': 'configuraciones de bloques de contenido',
                'ordering': ['display_order'],
                'unique_together': {('content_type', 'object_uuid', 'block_type')},
            },
        ),
    ]
