# Generated by Django 5.2.13 on 2026-08-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblockconfig',
            name='block_type',
            field=models.CharField(choices=[('description', 'Descripcion general'), ('scope', 'Alcance'), ('included', 'Que incluye'), ('excluded', 'Que NO incluye'), ('installation', 'Instalacion'), ('support', 'Soporte'), ('benefits', 'Beneficios'), ('warranty', 'Garantia'), ('specs', 'Ficha tecnica'), ('documents', 'Documentacion'), ('videos', 'Videos'), ('faq', 'FAQ'), ('compatible', 'Productos compatibles'), ('accessories', 'Accesorios recomendados'), ('related', 'Productos relacionados'), ('coverage', 'Cobertura'), ('process', 'Proceso del servicio'), ('materials', 'Materiales utilizados'), ('technicians', 'Tecnicos especializados'), ('recommended_products', 'Productos recomendados')], db_index=True, max_length=20),
        ),
    ]
