# Generated by Django 5.2.13 on 2026-08-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_seed_domain_settings'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='branding',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_deleted', False)), fields=('is_active',), name='unique_active_branding'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_deleted', False)), fields=('is_active',), name='unique_active_company'),
        ),
        migrations.AddConstraint(
            model_name='contactinfo',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_deleted', False)), fields=('is_active',), name='unique_active_contactinfo'),
        ),
        migrations.AddConstraint(
            model_name='domainsettings',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_deleted', False)), fields=('is_active',), name='unique_active_domainsettings'),
        ),
        migrations.AddConstraint(
            model_name='emailsettings',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_deleted', False)), fields=('is_active',), name='unique_active_emailsettings'),
        ),
        migrations.AddConstraint(
            model_name='legalentityinfo',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_deleted', False)), fields=('is_active',), name='unique_active_legalentityinfo'),
        ),
        migrations.AddConstraint(
            model_name='seosettings',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_deleted', False)), fields=('is_active',), name='unique_active_seosettings'),
        ),
    ]
