# Generated by Django 5.2.13 on 2026-08-15 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_branding_unique_active_branding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='trade_name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
