# Generated by Django 5.2.13 on 2026-08-16 16:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_alter_company_trade_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('doc_type', models.CharField(choices=[('terminos', 'Terminos y Condiciones'), ('politica', 'Politica de Privacidad y Tratamiento de Datos'), ('garantia', 'Politica de Garantia'), ('devoluciones', 'Politica de Devoluciones y Derecho de Retracto'), ('autorizacion', 'Autorizacion de Tratamiento de Datos')], max_length=30, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('updated_label', models.CharField(blank=True, default='', max_length=100)),
                ('sections', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Documento legal',
                'verbose_name_plural': 'Documentos legales',
            },
        ),
    ]
