# Generated by Django 5.2.13 on 2026-08-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_seed_legal_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='branding',
            name='accent_color',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='branding',
            name='primary_color',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
