# Generated by Django 5.2.13 on 2026-07-30 22:24
#
# Squash de core 0001-0026 (DT-M18, migration squashing). Las 3 funciones
# RunPython de abajo se copiaron manualmente desde sus migraciones originales
# (0017/0019/0024) por pedido explicito de Django ("Manual porting required")
# -- las originales NO se borraron (ver los propios archivos en este mismo
# directorio), solo se copiaron aqui para que esta migracion squasheada sea
# autocontenida y sirva para instalaciones nuevas. Las 3 son no-op seguras
# sobre una BD nueva vacia (get_or_create / listas vacias si no hay filas
# previas que migrar) y Django no las re-ejecuta sobre una BD ya migrada
# (las marca aplicadas via `replaces` sin correr el SQL/Python de nuevo).

import django.db.models.deletion
import uuid
from django.db import migrations, models


def copy_data_forward(apps, schema_editor):
    """
    Copia el registro activo de SiteBrandConfig/CompanyContactInfo y las filas
    de FooterLink(category='social') hacia organization. Las filas sociales de
    FooterLink se eliminan aqui (ya migradas); SiteBrandConfig/CompanyContactInfo
    se eliminan como modelos completos en la siguiente migracion.
    (copiada de 0017_migrate_company_data_to_organization.py)
    """
    SiteBrandConfig = apps.get_model('core', 'SiteBrandConfig')
    CompanyContactInfo = apps.get_model('core', 'CompanyContactInfo')
    FooterLink = apps.get_model('core', 'FooterLink')

    Company = apps.get_model('organization', 'Company')
    Branding = apps.get_model('organization', 'Branding')
    ContactInfo = apps.get_model('organization', 'ContactInfo')
    SocialLink = apps.get_model('organization', 'SocialLink')

    brand = SiteBrandConfig.objects.filter(is_active=True, is_deleted=False).first()
    if brand:
        Company.objects.create(trade_name=brand.site_name, is_active=True)
        Branding.objects.create(logo=brand.logo, tagline=brand.tagline, is_active=True)

    contact = CompanyContactInfo.objects.filter(is_active=True, is_deleted=False).first()
    if contact:
        ContactInfo.objects.create(
            phone=contact.phone,
            email=contact.email,
            address=contact.address,
            working_hours=contact.working_hours,
            is_active=True,
        )

    social_links = FooterLink.objects.filter(category='social', is_deleted=False)
    for link in social_links:
        SocialLink.objects.create(
            platform=link.title,
            url=link.url,
            icon_class=link.icon_class,
            display_order=link.display_order,
            is_active=link.is_active,
        )
    social_links.delete()


def copy_data_backward(apps, schema_editor):
    """No-op deliberado (copiada de 0017_migrate_company_data_to_organization.py)."""
    pass


def seed_renting_home_cards(apps, schema_editor):
    """Copiada de 0019_seed_renting_home_cards.py."""
    HomeCard = apps.get_model('core', 'HomeCard')
    HomeCardGroup = apps.get_model('core', 'HomeCardGroup')

    groups = [
        {
            'name': 'renting_home_solutions',
            'title': 'Soluciones premium de renting',
            'subtitle': 'Cards superiores del marketplace de alquiler.',
            'display_order': 210,
            'columns': 4,
        },
        {
            'name': 'renting_home_use_cases',
            'title': 'Renta tecnologia lista para operar en campo',
            'subtitle': 'Aplicaciones recomendadas',
            'display_order': 220,
            'columns': 6,
        },
        {
            'name': 'renting_home_availability',
            'title': 'Reserva por dias u horas con verificacion automatica',
            'subtitle': 'Disponibilidad inteligente',
            'display_order': 230,
            'columns': 2,
        },
        {
            'name': 'renting_home_process',
            'title': 'Del equipo a la solucion instalada',
            'subtitle': 'Proceso',
            'display_order': 240,
            'columns': 4,
        },
        {
            'name': 'renting_home_brands',
            'title': 'Marcas y ecosistemas compatibles',
            'subtitle': 'Compatibilidad',
            'display_order': 250,
            'columns': 6,
        },
    ]

    for group in groups:
        HomeCardGroup.objects.get_or_create(
            name=group['name'],
            defaults={
                'title': group['title'],
                'subtitle': group['subtitle'],
                'display_order': group['display_order'],
                'is_visible': True,
                'layout_type': 'grid',
                'columns': group['columns'],
            },
        )

    cards = [
        ('renting_home_solutions', 'Seguridad temporal', 'CCTV, control perimetral y monitoreo para eventos, obras y sedes temporales.', 'bi-camera-video', '#0369a1', 1),
        ('renting_home_solutions', 'Conectividad por proyecto', 'Redes, WiFi, switching y enlaces listos para operar durante el periodo contratado.', 'bi-router', '#2563eb', 2),
        ('renting_home_solutions', 'Infraestructura TI', 'Racks, energia, respaldo, computo y equipos empresariales con soporte tecnico.', 'bi-hdd-rack', '#4f46e5', 3),
        ('renting_home_solutions', 'Solucion con operador', 'Equipo, transporte, instalacion, configuracion, capacitacion y operador especializado.', 'bi-person-workspace', '#0f766e', 4),
        ('renting_home_use_cases', 'Eventos', '', 'bi-music-note-beamed', '#3730a3', 1),
        ('renting_home_use_cases', 'Construccion', '', 'bi-cone-striped', '#3730a3', 2),
        ('renting_home_use_cases', 'Hospitales', '', 'bi-hospital', '#3730a3', 3),
        ('renting_home_use_cases', 'Centros comerciales', '', 'bi-shop-window', '#3730a3', 4),
        ('renting_home_use_cases', 'Empresas', '', 'bi-buildings', '#3730a3', 5),
        ('renting_home_use_cases', 'Condominios', '', 'bi-house-gear', '#3730a3', 6),
        ('renting_home_availability', 'Modalidad', 'Horas o dias', 'bi-clock-history', '#0369a1', 1),
        ('renting_home_availability', 'Siguiente fecha', 'Motor de disponibilidad', 'bi-calendar-check', '#0369a1', 2),
        ('renting_home_availability', 'Logistica', 'Entrega y recogida', 'bi-truck', '#0369a1', 3),
        ('renting_home_availability', 'Paquetes', 'Solo equipo a premium', 'bi-box-seam', '#0369a1', 4),
        ('renting_home_process', 'Seleccionar', '', 'bi-check2-square', '#166534', 1),
        ('renting_home_process', 'Reservar', '', 'bi-calendar2-check', '#166534', 2),
        ('renting_home_process', 'Pagar', '', 'bi-credit-card', '#166534', 3),
        ('renting_home_process', 'Entregar', '', 'bi-truck', '#166534', 4),
        ('renting_home_process', 'Instalar', '', 'bi-tools', '#166534', 5),
        ('renting_home_process', 'Usar', '', 'bi-play-circle', '#166534', 6),
        ('renting_home_process', 'Recoger', '', 'bi-arrow-return-left', '#166534', 7),
        ('renting_home_process', 'Cerrar', '', 'bi-clipboard-check', '#166534', 8),
        ('renting_home_brands', 'Hikvision', '', 'bi-hdd-network', '#475569', 1),
        ('renting_home_brands', 'Dahua', '', 'bi-hdd-network', '#475569', 2),
        ('renting_home_brands', 'Ubiquiti', '', 'bi-router', '#475569', 3),
        ('renting_home_brands', 'Cisco', '', 'bi-diagram-3', '#475569', 4),
        ('renting_home_brands', 'Dell', '', 'bi-pc-display', '#475569', 5),
        ('renting_home_brands', 'APC', '', 'bi-lightning-charge', '#475569', 6),
    ]

    for group_name, title, description, icon_class, color, order in cards:
        HomeCard.objects.get_or_create(
            group_name=group_name,
            title=title,
            defaults={
                'description': description,
                'icon_class': icon_class,
                'background_color': color,
                'display_order': order,
                'is_active': True,
                'card_type': 'premium' if group_name == 'renting_home_solutions' else 'compact',
            },
        )


def seed_renting_home_cards_noop_reverse(apps, schema_editor):
    """Copiada de 0019_seed_renting_home_cards.py (era noop_reverse)."""
    pass


def backfill_footer_groups(apps, schema_editor):
    """Copiada de 0024_backfill_footer_groups.py."""
    FooterLink = apps.get_model('core', 'FooterLink')
    FooterGroup = apps.get_model('core', 'FooterGroup')

    # Cubre TODAS las filas (incluidas category='social' e is_deleted=True) porque
    # `group` pasa a ser NOT NULL en la migracion siguiente -- filas legadas/soft-deleted
    # tambien necesitan un grupo valido o el ALTER falla con IntegrityError.
    links = FooterLink.objects.all().order_by('group_name', 'display_order')
    distinct_names = []
    for link in links:
        name = link.group_name or 'Otros'
        if name not in distinct_names:
            distinct_names.append(name)

    groups_by_name = {}
    for index, name in enumerate(distinct_names):
        groups_by_name[name] = FooterGroup.objects.create(title=name, display_order=index)

    for link in links:
        name = link.group_name or 'Otros'
        link.group = groups_by_name[name]
        link.save(update_fields=['group'])


def backfill_footer_groups_noop_reverse(apps, schema_editor):
    """Irreversible a proposito (copiada de 0024_backfill_footer_groups.py)."""
    pass


class Migration(migrations.Migration):

    replaces = [('core', '0001_initial'), ('core', '0002_remove_homebanner_core_homebanner_uuid_idx_and_more'), ('core', '0003_homebanner_video'), ('core', '0004_homecard'), ('core', '0005_homecard_media'), ('core', '0006_footer_models'), ('core', '0007_homemoduleconfig_custom_fields'), ('core', '0008_homemoduleconfig_background_image'), ('core', '0009_sitebrandconfig_navbarlink'), ('core', '0010_alter_navbarlink_updated_at_and_more'), ('core', '0011_homecardgroup'), ('core', '0012_visual_builder'), ('core', '0013_homebanner_visual_fields'), ('core', '0014_footer_cta_config'), ('core', '0015_expand_display_choices'), ('core', '0016_alter_companycontactinfo_address_and_more'), ('core', '0017_migrate_company_data_to_organization'), ('core', '0018_delete_companycontactinfo_delete_sitebrandconfig'), ('core', '0019_seed_renting_home_cards'), ('core', '0020_homecard_badge_text_homecardgroup_glass_and_more'), ('core', '0021_alter_homecardgroup_layout_type'), ('core', '0022_brandsliderconfig_brandslideritem'), ('core', '0023_footergroup'), ('core', '0024_backfill_footer_groups'), ('core', '0025_footerlink_finalize_group'), ('core', '0026_aboutusconfig_aboutusvalue')]

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('phone', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.CharField(blank=True, default='', max_length=254)),
                ('address', models.CharField(blank=True, default='', max_length=500)),
                ('working_hours', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'informacion de contacto',
                'verbose_name_plural': 'informacion de contacto',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FooterCTAConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('eyebrow', models.CharField(blank=True, default='Empieza hoy', max_length=150)),
                ('title_prefix', models.CharField(blank=True, default='Impulsa tu empresa con', max_length=255)),
                ('title_highlighted', models.CharField(blank=True, default='Sintel Technology', max_length=255)),
                ('subtitle', models.CharField(blank=True, default='Soluciones tecnologicas, equipos y servicios profesionales en un solo lugar.', max_length=500)),
                ('btn_primary_label', models.CharField(blank=True, default='Solicitar cotizacion', max_length=150)),
                ('btn_primary_url', models.CharField(blank=True, default='/cotizar', max_length=300)),
                ('btn_ghost_label', models.CharField(blank=True, default='Explorar catalogo', max_length=150)),
                ('btn_ghost_url', models.CharField(blank=True, default='/tienda', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'config CTA final',
                'verbose_name_plural': 'config CTA final',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('social', 'Red Social'), ('nav', 'Navegacion')], db_index=True, default='nav', max_length=10)),
                ('group_name', models.CharField(blank=True, default='', max_length=150)),
                ('icon_class', models.CharField(blank=True, default='', max_length=100)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'enlace del footer',
                'verbose_name_plural': 'enlaces del footer',
                'ordering': ['category', 'group_name', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, default='', max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home_banners/images/')),
                ('link_url', models.CharField(blank=True, default='', max_length=500)),
                ('link_label', models.CharField(blank=True, default='', max_length=150)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('video', models.FileField(blank=True, null=True, upload_to='home_banners/videos/')),
                ('eyebrow', models.CharField(blank=True, default='', max_length=150)),
                ('background_color', models.CharField(blank=True, default='', max_length=30)),
                ('cta_ghost_label', models.CharField(blank=True, default='', max_length=150)),
                ('cta_ghost_url', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'verbose_name': 'banner de inicio',
                'verbose_name_plural': 'banners de inicio',
                'ordering': ['display_order', '-created_at'],
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='HomeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('group_name', models.CharField(db_index=True, max_length=150)),
                ('icon_class', models.CharField(default='bi-star', max_length=100)),
                ('background_color', models.CharField(default='#3b82f6', max_length=30)),
                ('redirect_url', models.CharField(blank=True, default='', max_length=500)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home_cards/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='home_cards/videos/')),
                ('card_type', models.CharField(choices=[('vertical', 'Vertical'), ('horizontal', 'Horizontal'), ('premium', 'Premium'), ('compact', 'Compacta'), ('glass', 'Glass'), ('dark', 'Dark'), ('gradient', 'Gradient'), ('image_bg', 'Imagen de fondo')], default='vertical', max_length=30)),
                ('animation', models.CharField(blank=True, default='', max_length=30)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('priority', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'tarjeta de inicio',
                'verbose_name_plural': 'tarjetas de inicio',
                'ordering': ['group_name', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='HomeCardGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_visible', models.BooleanField(db_index=True, default=True)),
                ('subtitle', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('bg_color', models.CharField(blank=True, default='', max_length=30)),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='home_groups/')),
                ('layout_type', models.CharField(choices=[('grid', 'Grid'), ('slider', 'Slider'), ('cards', 'Cards'), ('timeline', 'Timeline'), ('tabs', 'Tabs'), ('accordion', 'Accordion')], default='grid', max_length=30)),
                ('padding', models.CharField(choices=[('none', 'Sin padding'), ('sm', 'Pequeno'), ('normal', 'Normal'), ('lg', 'Grande'), ('xl', 'Extra grande')], default='normal', max_length=20)),
                ('divider', models.BooleanField(default=False)),
                ('columns', models.PositiveSmallIntegerField(default=3)),
            ],
            options={
                'verbose_name': 'grupo de tarjetas',
                'verbose_name_plural': 'grupos de tarjetas',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HomeModuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('module_key', models.CharField(max_length=40, unique=True)),
                ('is_visible', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('featured_items_limit', models.PositiveIntegerField(default=8)),
                ('custom_label', models.CharField(blank=True, default='', max_length=255)),
                ('custom_icon', models.CharField(blank=True, default='', max_length=100)),
                ('custom_url', models.CharField(blank=True, default='', max_length=300)),
                ('custom_color', models.CharField(blank=True, default='', max_length=30)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='home_modules/images/')),
                ('display_type', models.CharField(choices=[('grid', 'Grid'), ('grid_modern', 'Grid moderno'), ('slider', 'Slider'), ('carousel', 'Carrusel'), ('cards_h', 'Cards Horizontales'), ('cards_v', 'Cards Verticales'), ('hero', 'Hero'), ('banner', 'Banner'), ('list', 'Lista'), ('timeline', 'Timeline'), ('accordion', 'Accordion'), ('tabs', 'Tabs'), ('masonry', 'Masonry'), ('highlight', 'Destacados'), ('premium', 'Premium Cards'), ('compact', 'Compacto'), ('split', 'Split Layout'), ('minimal', 'Minimalista')], default='grid', max_length=30)),
                ('layout_config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'configuracion de modulo en home',
                'verbose_name_plural': 'configuracion de modulos en home',
                'ordering': ['display_order'],
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='NavbarLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('label', models.CharField(max_length=150)),
                ('url', models.CharField(max_length=300)),
                ('icon_class', models.CharField(blank=True, default='', max_length=100)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_visible', models.BooleanField(db_index=True, default=True)),
                ('open_in_new_tab', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'enlace del navbar',
                'verbose_name_plural': 'enlaces del navbar',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='SiteBrandConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('site_name', models.CharField(default='Sintel', max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand/')),
                ('tagline', models.CharField(blank=True, default='', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'configuracion de marca',
                'verbose_name_plural': 'configuracion de marca',
            },
        ),
        migrations.RunPython(
            code=copy_data_forward,
            reverse_code=copy_data_backward,
        ),
        migrations.DeleteModel(
            name='CompanyContactInfo',
        ),
        migrations.DeleteModel(
            name='SiteBrandConfig',
        ),
        migrations.RunPython(
            code=seed_renting_home_cards,
            reverse_code=seed_renting_home_cards_noop_reverse,
        ),
        migrations.AddField(
            model_name='homecard',
            name='badge_text',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='homecardgroup',
            name='glass',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homecardgroup',
            name='hover',
            field=models.CharField(choices=[('lift', 'Elevar'), ('scale', 'Escalar'), ('glow', 'Resplandor'), ('none', 'Ninguno')], default='lift', max_length=20),
        ),
        migrations.AlterField(
            model_name='homecard',
            name='card_type',
            field=models.CharField(choices=[('vertical', 'Vertical'), ('horizontal', 'Horizontal'), ('premium', 'Premium'), ('compact', 'Compacta'), ('glass', 'Glass'), ('dark', 'Dark'), ('gradient', 'Gradient'), ('image_bg', 'Imagen de fondo'), ('logo', 'Logo de cliente')], default='vertical', max_length=30),
        ),
        migrations.AlterField(
            model_name='homecardgroup',
            name='layout_type',
            field=models.CharField(choices=[('grid', 'Grid'), ('slider', 'Slider'), ('cards', 'Cards'), ('timeline', 'Timeline'), ('tabs', 'Tabs'), ('accordion', 'Accordion'), ('logos', 'Logos de clientes'), ('marquee', 'Marquee (rotacion automatica)')], default='grid', max_length=30),
        ),
        migrations.CreateModel(
            name='BrandSliderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(blank=True, default='Marcas y clientes', max_length=255)),
                ('subtitle', models.CharField(blank=True, default='', max_length=500)),
                ('autoplay', models.BooleanField(default=True)),
                ('speed', models.PositiveIntegerField(default=3500)),
                ('direction', models.CharField(choices=[('left', 'Izquierda'), ('right', 'Derecha')], default='left', max_length=10)),
                ('loop', models.BooleanField(default=True)),
                ('pause_on_hover', models.BooleanField(default=True)),
                ('items_desktop', models.PositiveSmallIntegerField(default=6)),
                ('items_tablet', models.PositiveSmallIntegerField(default=4)),
                ('items_mobile', models.PositiveSmallIntegerField(default=2)),
                ('background_color', models.CharField(blank=True, default='', max_length=30)),
                ('padding_top', models.CharField(choices=[('none', 'Sin padding'), ('sm', 'Pequeno'), ('normal', 'Normal'), ('lg', 'Grande'), ('xl', 'Extra grande')], default='normal', max_length=20)),
                ('padding_bottom', models.CharField(choices=[('none', 'Sin padding'), ('sm', 'Pequeno'), ('normal', 'Normal'), ('lg', 'Grande'), ('xl', 'Extra grande')], default='normal', max_length=20)),
                ('is_visible', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'config de slider de marcas',
                'verbose_name_plural': 'config de slider de marcas',
            },
        ),
        migrations.CreateModel(
            name='BrandSliderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand_slider/logos/')),
                ('website', models.CharField(blank=True, default='', max_length=500)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('open_new_tab', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'logo de slider de marcas',
                'verbose_name_plural': 'logos de slider de marcas',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FooterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=150)),
                ('icon_class', models.CharField(blank=True, default='bi-folder', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('background_color', models.CharField(blank=True, default='', max_length=30)),
                ('text_color', models.CharField(blank=True, default='', max_length=30)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'grupo del footer',
                'verbose_name_plural': 'grupos del footer',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.AlterModelOptions(
            name='footerlink',
            options={'ordering': ['category', 'display_order'], 'verbose_name': 'enlace del footer', 'verbose_name_plural': 'enlaces del footer'},
        ),
        migrations.AddField(
            model_name='footerlink',
            name='open_new_tab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='footerlink',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.footergroup'),
        ),
        migrations.RunPython(
            code=backfill_footer_groups,
            reverse_code=backfill_footer_groups_noop_reverse,
        ),
        migrations.RemoveField(
            model_name='footerlink',
            name='group_name',
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.footergroup'),
        ),
        migrations.CreateModel(
            name='AboutUsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(blank=True, default='Sobre Nosotros', max_length=255)),
                ('subtitle', models.CharField(blank=True, default='', max_length=500)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='about_us/hero/')),
                ('history', models.TextField(blank=True, default='')),
                ('mission', models.TextField(blank=True, default='')),
                ('vision', models.TextField(blank=True, default='')),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'config de Sobre Nosotros',
                'verbose_name_plural': 'config de Sobre Nosotros',
            },
        ),
        migrations.CreateModel(
            name='AboutUsValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('icon_class', models.CharField(default='bi-gem', max_length=100)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'valor institucional',
                'verbose_name_plural': 'valores institucionales',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
