# Generated by Django 5.2.13 on 2026-06-22 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='homebanner',
            name='core_homebanner_uuid_idx',
        ),
        migrations.RemoveIndex(
            model_name='homebanner',
            name='core_homebanner_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='homemoduleconfig',
            name='core_homemoduleconfig_uuid_idx',
        ),
        migrations.RemoveIndex(
            model_name='homemoduleconfig',
            name='core_homemoduleconfig_created_idx',
        ),
    ]
