# Generated by Django 5.2.13 on 2026-06-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_sitebrandconfig_navbarlink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navbarlink",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="sitebrandconfig",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
