# Generated by Django 5.2.13 on 2026-06-30 19:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_footer_cta_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerctaconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='footerctaconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='footerctaconfig',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='footerctaconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='footerctaconfig',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='homemoduleconfig',
            name='display_type',
            field=models.CharField(choices=[('grid', 'Grid'), ('grid_modern', 'Grid moderno'), ('slider', 'Slider'), ('carousel', 'Carrusel'), ('cards_h', 'Cards Horizontales'), ('cards_v', 'Cards Verticales'), ('hero', 'Hero'), ('banner', 'Banner'), ('list', 'Lista'), ('timeline', 'Timeline'), ('accordion', 'Accordion'), ('tabs', 'Tabs'), ('masonry', 'Masonry'), ('highlight', 'Destacados'), ('premium', 'Premium Cards'), ('compact', 'Compacto'), ('split', 'Split Layout'), ('minimal', 'Minimalista')], default='grid', max_length=30),
        ),
    ]
