# Generated by Django 5.2.13 on 2026-07-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_expand_display_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycontactinfo',
            name='address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='companycontactinfo',
            name='email',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='companycontactinfo',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='companycontactinfo',
            name='working_hours',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='footerctaconfig',
            name='btn_ghost_label',
            field=models.CharField(blank=True, default='Explorar catalogo', max_length=150),
        ),
        migrations.AlterField(
            model_name='footerctaconfig',
            name='btn_ghost_url',
            field=models.CharField(blank=True, default='/tienda', max_length=300),
        ),
        migrations.AlterField(
            model_name='footerctaconfig',
            name='btn_primary_label',
            field=models.CharField(blank=True, default='Solicitar cotizacion', max_length=150),
        ),
        migrations.AlterField(
            model_name='footerctaconfig',
            name='btn_primary_url',
            field=models.CharField(blank=True, default='/cotizar', max_length=300),
        ),
        migrations.AlterField(
            model_name='footerctaconfig',
            name='eyebrow',
            field=models.CharField(blank=True, default='Empieza hoy', max_length=150),
        ),
        migrations.AlterField(
            model_name='footerctaconfig',
            name='subtitle',
            field=models.CharField(blank=True, default='Soluciones tecnologicas, equipos y servicios profesionales en un solo lugar.', max_length=500),
        ),
        migrations.AlterField(
            model_name='footerctaconfig',
            name='title_highlighted',
            field=models.CharField(blank=True, default='Sintel Technology', max_length=255),
        ),
        migrations.AlterField(
            model_name='footerctaconfig',
            name='title_prefix',
            field=models.CharField(blank=True, default='Impulsa tu empresa con', max_length=255),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='group_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='icon_class',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='cta_ghost_label',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='eyebrow',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='link_label',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='homecard',
            name='group_name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='homecard',
            name='icon_class',
            field=models.CharField(default='bi-star', max_length=100),
        ),
        migrations.AlterField(
            model_name='homecard',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='homecard',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='homecardgroup',
            name='name',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='homecardgroup',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='homecardgroup',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='homemoduleconfig',
            name='custom_icon',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='homemoduleconfig',
            name='custom_label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='homemoduleconfig',
            name='custom_url',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='navbarlink',
            name='icon_class',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='navbarlink',
            name='label',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='navbarlink',
            name='url',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='sitebrandconfig',
            name='site_name',
            field=models.CharField(default='Sintel', max_length=150),
        ),
        migrations.AlterField(
            model_name='sitebrandconfig',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
