# Generated by Django 5.2.13 on 2026-07-12 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_migrate_company_data_to_organization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyContactInfo',
        ),
        migrations.DeleteModel(
            name='SiteBrandConfig',
        ),
    ]
