# Generated by Django 5.2.13 on 2026-07-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_seed_renting_home_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecard',
            name='badge_text',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='homecardgroup',
            name='glass',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homecardgroup',
            name='hover',
            field=models.CharField(choices=[('lift', 'Elevar'), ('scale', 'Escalar'), ('glow', 'Resplandor'), ('none', 'Ninguno')], default='lift', max_length=20),
        ),
        migrations.AlterField(
            model_name='homecard',
            name='card_type',
            field=models.CharField(choices=[('vertical', 'Vertical'), ('horizontal', 'Horizontal'), ('premium', 'Premium'), ('compact', 'Compacta'), ('glass', 'Glass'), ('dark', 'Dark'), ('gradient', 'Gradient'), ('image_bg', 'Imagen de fondo'), ('logo', 'Logo de cliente')], default='vertical', max_length=30),
        ),
        migrations.AlterField(
            model_name='homecardgroup',
            name='layout_type',
            field=models.CharField(choices=[('grid', 'Grid'), ('slider', 'Slider'), ('cards', 'Cards'), ('timeline', 'Timeline'), ('tabs', 'Tabs'), ('accordion', 'Accordion'), ('logos', 'Logos de clientes')], default='grid', max_length=30),
        ),
    ]
