# Generated by Django 5.2.13 on 2026-07-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_homecard_badge_text_homecardgroup_glass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecardgroup',
            name='layout_type',
            field=models.CharField(choices=[('grid', 'Grid'), ('slider', 'Slider'), ('cards', 'Cards'), ('timeline', 'Timeline'), ('tabs', 'Tabs'), ('accordion', 'Accordion'), ('logos', 'Logos de clientes'), ('marquee', 'Marquee (rotacion automatica)')], default='grid', max_length=30),
        ),
    ]
