# Generated by Django 5.2.13 on 2026-07-15 14:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_homecardgroup_layout_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandSliderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(blank=True, default='Marcas y clientes', max_length=255)),
                ('subtitle', models.CharField(blank=True, default='', max_length=500)),
                ('autoplay', models.BooleanField(default=True)),
                ('speed', models.PositiveIntegerField(default=3500)),
                ('direction', models.CharField(choices=[('left', 'Izquierda'), ('right', 'Derecha')], default='left', max_length=10)),
                ('loop', models.BooleanField(default=True)),
                ('pause_on_hover', models.BooleanField(default=True)),
                ('items_desktop', models.PositiveSmallIntegerField(default=6)),
                ('items_tablet', models.PositiveSmallIntegerField(default=4)),
                ('items_mobile', models.PositiveSmallIntegerField(default=2)),
                ('background_color', models.CharField(blank=True, default='', max_length=30)),
                ('padding_top', models.CharField(choices=[('none', 'Sin padding'), ('sm', 'Pequeno'), ('normal', 'Normal'), ('lg', 'Grande'), ('xl', 'Extra grande')], default='normal', max_length=20)),
                ('padding_bottom', models.CharField(choices=[('none', 'Sin padding'), ('sm', 'Pequeno'), ('normal', 'Normal'), ('lg', 'Grande'), ('xl', 'Extra grande')], default='normal', max_length=20)),
                ('is_visible', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'config de slider de marcas',
                'verbose_name_plural': 'config de slider de marcas',
            },
        ),
        migrations.CreateModel(
            name='BrandSliderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand_slider/logos/')),
                ('website', models.CharField(blank=True, default='', max_length=500)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('open_new_tab', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'logo de slider de marcas',
                'verbose_name_plural': 'logos de slider de marcas',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
