# Generated by Django 5.2.13 on 2026-07-15 16:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_brandsliderconfig_brandslideritem'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=150)),
                ('icon_class', models.CharField(blank=True, default='bi-folder', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('background_color', models.CharField(blank=True, default='', max_length=30)),
                ('text_color', models.CharField(blank=True, default='', max_length=30)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'grupo del footer',
                'verbose_name_plural': 'grupos del footer',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.AlterModelOptions(
            name='footerlink',
            options={'ordering': ['category', 'display_order'], 'verbose_name': 'enlace del footer', 'verbose_name_plural': 'enlaces del footer'},
        ),
        migrations.AddField(
            model_name='footerlink',
            name='open_new_tab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='footerlink',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.footergroup'),
        ),
    ]
