# Generated by Django 5.2.13 on 2026-07-19 18:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_footerlink_finalize_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(blank=True, default='Sobre Nosotros', max_length=255)),
                ('subtitle', models.CharField(blank=True, default='', max_length=500)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='about_us/hero/')),
                ('history', models.TextField(blank=True, default='')),
                ('mission', models.TextField(blank=True, default='')),
                ('vision', models.TextField(blank=True, default='')),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'config de Sobre Nosotros',
                'verbose_name_plural': 'config de Sobre Nosotros',
            },
        ),
        migrations.CreateModel(
            name='AboutUsValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('icon_class', models.CharField(default='bi-gem', max_length=100)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'valor institucional',
                'verbose_name_plural': 'valores institucionales',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
