# Generated by Django 5.2.13 on 2026-08-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial_squashed_0026_aboutusconfig_aboutusvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusconfig',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='brandsliderconfig',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
