# Generated by Django 5.2.13 on 2026-08-06 21:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_aboutusconfig_is_active_brandsliderconfig_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureBannerSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('subtitle', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('is_visible', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('corporate', 'Corporate'), ('minimal', 'Minimal'), ('glass', 'Glass')], default='light', max_length=20)),
                ('background_type', models.CharField(choices=[('color', 'Color solido'), ('gradient', 'Gradiente'), ('image', 'Imagen')], default='color', max_length=20)),
                ('background_color', models.CharField(blank=True, default='', max_length=30)),
                ('background_gradient_from', models.CharField(blank=True, default='', max_length=30)),
                ('background_gradient_to', models.CharField(blank=True, default='', max_length=30)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='home_feature_banner/backgrounds/')),
                ('overlay_enabled', models.BooleanField(default=False)),
                ('overlay_opacity', models.PositiveSmallIntegerField(default=45)),
                ('padding', models.CharField(choices=[('none', 'Sin padding'), ('sm', 'Pequeno'), ('normal', 'Normal'), ('lg', 'Grande'), ('xl', 'Extra grande')], default='normal', max_length=20)),
            ],
            options={
                'verbose_name': 'seccion de feature banner',
                'verbose_name_plural': 'secciones de feature banner',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureBannerBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('layout_type', models.CharField(choices=[('image_left', 'Imagen izquierda'), ('image_right', 'Imagen derecha'), ('fifty_fifty', '50 / 50'), ('sixty_forty', '60 / 40'), ('forty_sixty', '40 / 60'), ('full_image', 'Imagen completa (overlay)'), ('text_centered', 'Texto centrado (sin imagen)')], default='image_left', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('title_highlighted', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='home_feature_banner/blocks/')),
                ('image_alt', models.CharField(blank=True, default='', max_length=255)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('stats', models.JSONField(blank=True, default=list)),
                ('badge_text', models.CharField(blank=True, default='', max_length=50)),
                ('badge_color', models.CharField(blank=True, default='#f59e0b', max_length=30)),
                ('btn_primary_text', models.CharField(blank=True, default='', max_length=100)),
                ('btn_primary_icon', models.CharField(blank=True, default='', max_length=100)),
                ('btn_primary_color', models.CharField(blank=True, default='#2563eb', max_length=30)),
                ('btn_primary_style', models.CharField(choices=[('filled', 'Filled'), ('outline', 'Outline'), ('ghost', 'Ghost'), ('minimal', 'Minimal')], default='filled', max_length=20)),
                ('btn_primary_url', models.CharField(blank=True, default='', max_length=500)),
                ('btn_primary_url_type', models.CharField(choices=[('INTERNA', 'Interna'), ('EXTERNA', 'Externa'), ('ANCHOR', 'Ancla')], default='INTERNA', max_length=10)),
                ('btn_primary_target', models.CharField(choices=[('_self', 'Misma pestaña'), ('_blank', 'Nueva pestaña')], default='_self', max_length=10)),
                ('btn_secondary_text', models.CharField(blank=True, default='', max_length=100)),
                ('btn_secondary_icon', models.CharField(blank=True, default='', max_length=100)),
                ('btn_secondary_color', models.CharField(blank=True, default='#2563eb', max_length=30)),
                ('btn_secondary_style', models.CharField(choices=[('filled', 'Filled'), ('outline', 'Outline'), ('ghost', 'Ghost'), ('minimal', 'Minimal')], default='outline', max_length=20)),
                ('btn_secondary_url', models.CharField(blank=True, default='', max_length=500)),
                ('btn_secondary_url_type', models.CharField(choices=[('INTERNA', 'Interna'), ('EXTERNA', 'Externa'), ('ANCHOR', 'Ancla')], default='INTERNA', max_length=10)),
                ('btn_secondary_target', models.CharField(choices=[('_self', 'Misma pestaña'), ('_blank', 'Nueva pestaña')], default='_self', max_length=10)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.featurebannersection')),
            ],
            options={
                'verbose_name': 'bloque de feature banner',
                'verbose_name_plural': 'bloques de feature banner',
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
