# Generated by Django 5.2.13 on 2026-08-06 22:18

from django.db import migrations, models


def backfill_url_type(apps, schema_editor):
    """
    url_type reemplaza la inferencia por regex que hacia CardItem.vue::navigate()
    (redirect_url.startsWith('http')) -- se aplica la MISMA regla una sola vez sobre
    las tarjetas existentes para que el campo nuevo no quede en un estado ambiguo.
    """
    HomeCard = apps.get_model('core', 'HomeCard')
    HomeCard.objects.filter(redirect_url__startswith='http').update(url_type='EXTERNA')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_featurebannersection_featurebannerblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecard',
            name='badge_color',
            field=models.CharField(blank=True, default='#2563eb', max_length=30),
        ),
        migrations.AddField(
            model_name='homecard',
            name='secondary_icon',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='homecard',
            name='secondary_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='homecard',
            name='secondary_target',
            field=models.CharField(choices=[('_self', 'Misma pestaña'), ('_blank', 'Nueva pestaña')], default='_self', max_length=10),
        ),
        migrations.AddField(
            model_name='homecard',
            name='secondary_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='homecard',
            name='secondary_url_type',
            field=models.CharField(choices=[('INTERNA', 'Interna'), ('EXTERNA', 'Externa'), ('ANCHOR', 'Ancla')], default='INTERNA', max_length=10),
        ),
        migrations.AddField(
            model_name='homecard',
            name='stats',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='homecard',
            name='url_target',
            field=models.CharField(choices=[('_self', 'Misma pestaña'), ('_blank', 'Nueva pestaña')], default='_self', max_length=10),
        ),
        migrations.AddField(
            model_name='homecard',
            name='url_type',
            field=models.CharField(choices=[('INTERNA', 'Interna'), ('EXTERNA', 'Externa'), ('ANCHOR', 'Ancla')], default='INTERNA', max_length=10),
        ),
        migrations.AddField(
            model_name='homecardgroup',
            name='carousel_autoplay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homecardgroup',
            name='carousel_loop',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homecardgroup',
            name='carousel_speed',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AddField(
            model_name='homecardgroup',
            name='columns_mobile',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='homecardgroup',
            name='columns_tablet',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='homecardgroup',
            name='gap',
            field=models.DecimalField(decimal_places=2, default=1.25, max_digits=4),
        ),
        migrations.AddField(
            model_name='homecardgroup',
            name='show_arrows',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homecardgroup',
            name='show_indicators',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(backfill_url_type, noop_reverse),
    ]
