# Generated by Django 6.0.4 on 2026-04-14 17:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('wompi_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('amount_in_cents', models.BigIntegerField()),
                ('currency', models.CharField(default='COP', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobada'), ('DECLINED', 'Declinada'), ('VOIDED', 'Anulada'), ('ERROR', 'Error en pasarela')], default='PENDING', max_length=20)),
                ('payment_method_type', models.CharField(blank=True, max_length=50, null=True)),
                ('redirect_url', models.URLField(blank=True, max_length=500, null=True)),
                ('integrity_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.order')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['uuid'], name='wompi_trans_uuid_78d39c_idx'), models.Index(fields=['-created_at'], name='wompi_trans_created_845684_idx')],
            },
        ),
    ]
