# Generated by Django 5.2.13 on 2026-06-25 14:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_payment_method'),
        ('payment', '0002_transaction_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmado'), ('DELIVERED', 'Entregado'), ('CANCELLED', 'Cancelado')], db_index=True, default='CONFIRMED', max_length=20)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Transaccion COD',
                'verbose_name_plural': 'Transacciones COD',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NequiTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('phone_number', models.CharField(max_length=20)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('ERROR', 'Error')], db_index=True, default='PENDING', max_length=20)),
            ],
            options={
                'verbose_name': 'Transaccion Nequi',
                'verbose_name_plural': 'Transacciones Nequi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Transaccion Wompi', 'verbose_name_plural': 'Transacciones Wompi'},
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='wompi_trans_uuid_78d39c_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='wompi_trans_created_845684_idx',
        ),
        migrations.AddField(
            model_name='codtransaction',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cod_transaction', to='orders.order'),
        ),
        migrations.AddField(
            model_name='nequitransaction',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nequi_transactions', to='orders.order'),
        ),
    ]
