# Generated by Django 5.2.13 on 2026-06-25 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_payment_method'),
        ('renting', '0008_multipayment'),
        ('payment', '0003_codtransaction_nequitransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nequitransaction',
            name='rental_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nequi_transactions', to='renting.rentalrequest'),
        ),
        migrations.AlterField(
            model_name='nequitransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nequi_transactions', to='orders.order'),
        ),
    ]
