# Generated by Django 5.2.13 on 2026-07-02 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_fulfillment_models'),
        ('payment', '0005_tokenizedcard'),
        ('renting', '0010_rentalprojectattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='rental_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wompi_transactions', to='renting.rentalrequest'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.order'),
        ),
    ]
