# Generated by Django 5.2.13 on 2026-07-03 22:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_status'),
        ('payment', '0006_transaction_rental_request_alter_transaction_order'),
        ('renting', '0011_remove_equipmentimage_renting_equ_uuid_dafff2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobada'), ('DECLINED', 'Declinada'), ('VOIDED', 'Anulada'), ('ERROR', 'Error en pasarela')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='nequitransaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('order__isnull', False), ('rental_request__isnull', True)), models.Q(('order__isnull', True), ('rental_request__isnull', False)), _connector='OR'), name='payment_nequitransaction_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='tokenizedcard',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True), ('is_deleted', False)), fields=('user',), name='payment_tokenizedcard_one_default_per_user'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('order__isnull', False), ('rental_request__isnull', True)), models.Q(('order__isnull', True), ('rental_request__isnull', False)), _connector='OR'), name='payment_transaction_exactly_one_target'),
        ),
    ]
