# Generated by Django 5.2.13 on 2026-07-13 17:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_seed_reconcile_periodic_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='correlation_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.CreateModel(
            name='TransactionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('source', models.CharField(choices=[('WEBHOOK', 'Webhook de Wompi'), ('API_SYNC', 'Sincronizacion via API (polling)'), ('API_CREATE', 'Creacion sincrona via API')], db_index=True, max_length=20)),
                ('previous_status', models.CharField(blank=True, default='', max_length=20)),
                ('new_status', models.CharField(blank=True, default='', max_length=20)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('processed', models.BooleanField(default=True)),
                ('error_detail', models.TextField(blank=True, default='')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='payment.transaction')),
            ],
            options={
                'verbose_name': 'evento de transaccion Wompi',
                'verbose_name_plural': 'eventos de transaccion Wompi',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'source'], name='payment_tra_created_bbcd0b_idx')],
            },
        ),
    ]
