# Generated by Django 5.2.13 on 2026-07-13 17:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_transaction_correlation_id_transactionevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentFeatureFlags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('card_api_flow_enabled', models.BooleanField(default=True, help_text='Si esta activo, el checkout ofrece "Tarjeta" (flujo backend directo via WompiApiClient, sin abrir el Widget) ademas de "PSE / Otros". Si se desactiva, el checkout solo ofrece "PSE / Otros" (Widget completo de Wompi, que ya incluye tarjeta) -- reversion instantanea sin deploy si el flujo nuevo da problemas en produccion.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'flags de pagos',
                'verbose_name_plural': 'flags de pagos',
            },
        ),
    ]
