# Generated by Django 5.2.13 on 2026-07-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_seed_notify_declined_payments_periodic_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='initiation_channel',
            field=models.CharField(blank=True, choices=[('CARD_API', 'Tarjeta (API directa)'), ('WIDGET', 'Widget Wompi (PSE/Otros)')], db_index=True, max_length=20, null=True),
        ),
    ]
