# Generated by Django 5.2.13 on 2026-07-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_transaction_initiation_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentfeatureflags',
            name='widget_flow_enabled',
            field=models.BooleanField(default=True, help_text='Si esta activo, el checkout ofrece "PSE / Otros" (Widget completo de Wompi -- PSE, Nequi, Bancolombia, etc.). Si se desactiva, ese boton se oculta y el checkout solo permite pagar con Tarjeta via API -- util si Wompi reporta una incidencia puntual con su Widget.'),
        ),
    ]
